const fs = require("fs");
const assert = require("assert");
const path = `/tmp/quench-node-stage-118-${process.pid}`;
fs.writeFileSync(path, "abcd");
const fd = fs.openSync(path, "w+");
fs.writevSync(fd, [Buffer.from("ab"), Buffer.from("cd")]);
fs.closeSync(fd);
const contents = fs.readFileSync(path);
assert.strictEqual(Buffer.from("abcd").equals(contents), true);
assert.strictEqual(contents.equals(Buffer.from("abce")), false);
fs.rmSync(path);
