//! Code generator: High-level IR → Rust source code
//!
//! This module transforms the HIR (High-Level IR) into idiomatic Rust code
//! that compiles to efficient native binaries.

use super::hir::*;
use anyhow::{anyhow, Result};

/// Code generator for producing Rust source from HIR
pub struct CodeGenerator {
    /// Generated imports to include
    imports: Vec<String>,
    /// Current indent level
    indent: usize,
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            imports: vec![
                "use runts_lib::runtime::prelude::*;".to_string(),
                "use serde::{Serialize, Deserialize};".to_string(),
            ],
            indent: 0,
        }
    }

    /// Generate indented output
    fn indent(&self) -> String {
        "    ".repeat(self.indent)
    }

    /// Generate Rust code for a module
    pub fn generate_module(&mut self, module: &Module) -> Result<String> {
        let mut output = String::new();

        output.push_str("//! Generated by runts\n");
        if !module.source.is_empty() {
            output.push_str(&format!("//! Source: {}\n", module.source));
        }
        output.push('\n');

        for item in &module.items {
            if let ModuleItem::Decl(Decl::Type(t)) = item {
                let type_code = self.generate_type_decl(t)?;
                if !type_code.trim().is_empty() {
                    output.push_str(&type_code);
                    output.push_str("\n");
                }
            }
        }

        for item in &module.items {
            if let ModuleItem::Decl(decl) = item {
                if matches!(decl, Decl::Type(_)) {
                    continue;
                }
                let decl_code = self.generate_decl(decl)?;
                if !decl_code.trim().is_empty() {
                    output.push_str(&decl_code);
                    output.push_str("\n\n");
                }
            }
            
            if let ModuleItem::Export(Export::Default { expr }) = item {
                if let Expr::Function { decl } = expr {
                    let fn_code = self.generate_function(decl, false)?;
                    if !fn_code.trim().is_empty() {
                        output.push_str(&fn_code);
                        output.push_str("\n\n");
                    }
                }
            }
        }

        Ok(output)
    }

    pub fn generate_type_decl(&self, decl: &TypeDecl) -> Result<String> {
        let name = &decl.name;
        let generics_str = if !decl.generics.is_empty() {
            format!("<{}>", decl.generics.iter().map(|g| g.name.clone()).collect::<Vec<_>>().join(", "))
        } else {
            String::new()
        };

        let rust_type = self.type_to_rust(&decl.type_);
        
        if let Type::Object { members } = &decl.type_ {
            let mut out = String::new();
            out.push_str("#[derive(Clone, PartialEq, Serialize, Deserialize)]\n");
            out.push_str(&format!("pub struct {}{} {{\n", name, generics_str));
            for member in members {
                let field_type = self.type_to_rust(&member.type_);
                out.push_str(&format!("    pub {}: {},\n", self.to_snake_case(&member.key), field_type));
            }
            out.push_str("}\n");
            return Ok(out);
        }

        Ok(format!("pub type {}{} = {};\n", name, generics_str, rust_type))
    }

    pub fn type_to_rust(&self, t: &Type) -> String {
        match t {
            Type::String => "String".to_string(),
            Type::Number => "f64".to_string(),
            Type::Boolean => "bool".to_string(),
            Type::Null | Type::Undefined | Type::Void => "()".to_string(),
            Type::Never => "!".to_string(),
            Type::Unknown | Type::Any => "serde_json::Value".to_string(),
            Type::BigInt => "i64".to_string(),
            Type::Symbol => "()".to_string(),
            Type::Ref { name, generics } => {
                let args = if !generics.is_empty() {
                    format!("<{}>", generics.iter().map(|g| self.type_to_rust(g)).collect::<Vec<_>>().join(", "))
                } else {
                    String::new()
                };
                match name.as_str() {
                    "PageProps" | "HandlerContext" | "Request" | "Response" => name.clone() + &args,
                    _ => self.to_snake_case(name) + &args,
                }
            }
            Type::Union { types } => {
                if types.len() == 2 {
                    if let Some(null_pos) = types.iter().position(|t| matches!(t, Type::Null | Type::Undefined)) {
                        let non_null = types.iter().enumerate()
                            .filter(|(i, _)| *i != null_pos)
                            .map(|(_, t)| self.type_to_rust(t))
                            .collect::<Vec<_>>()
                            .join(" | ");
                        return format!("Option<{}>", non_null);
                    }
                }
                types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(" | ")
            }
            Type::Intersection { types } => {
                types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(" + ")
            }
            Type::Array { elem } => format!("Vec<{}>", self.type_to_rust(elem)),
            Type::Tuple { types } => {
                format!("({})", types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(", "))
            }
            Type::Object { members } => {
                if members.is_empty() {
                    "()".to_string()
                } else {
                    let fields: Vec<String> = members.iter().map(|m| {
                        format!("pub {}: {}", self.to_snake_case(&m.key), self.type_to_rust(&m.type_))
                    }).collect();
                    format!("{{{}}}", fields.join(", "))
                }
            }
            Type::Function { params, ret, .. } => {
                let param_str = params.iter().map(|p| self.type_to_rust(p)).collect::<Vec<_>>().join(", ");
                let ret_str = self.type_to_rust(ret);
                format!("Box<dyn Fn({}) -> {} + Send + Sync>", param_str, ret_str)
            }
            Type::Paren { type_ } => self.type_to_rust(type_),
            Type::Index { obj, index } => {
                format!("std::collections::HashMap<{}, {}>", self.type_to_rust(obj), self.type_to_rust(index))
            }
            Type::Conditional { true_type, false_type, .. } => {
                format!("if _ {{ {} }} else {{ {} }}", self.type_to_rust(true_type), self.type_to_rust(false_type))
            }
            Type::Mapped { type_, .. } => {
                format!("std::collections::HashMap<String, {}>", self.type_to_rust(type_))
            }
            Type::Template { parts } => {
                let parts_str: Vec<String> = parts.iter().map(|p| match p {
                    TemplatePart::String(s) => format!("{:?}", s),
                    TemplatePart::Type(t) => self.type_to_rust(t),
                }).collect();
                parts_str.join(" + ")
            }
        }
    }

    fn generate_decl(&mut self, decl: &Decl) -> Result<String> {
        match decl {
            Decl::Function(f) => {
                let is_component = f.name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);
                self.generate_function(f, is_component)
            }
            Decl::Variable(v) => self.generate_variable(v),
            Decl::Type(t) => self.generate_type_decl(t),
            Decl::Class(c) => Err(anyhow!("Class components are not supported: {}", c.name)),
        }
    }

    pub fn generate_function(&self, f: &FunctionDecl, force_component: bool) -> Result<String> {
        let rust_name = self.to_snake_case(&f.name);
        let is_component = force_component 
            || rust_name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);

        let mut output = String::new();

        if is_component {
            output.push_str("#[component]\n");
        }

        let params: Vec<String> = f.params.iter().map(|p| {
            let type_str = p.type_.as_ref()
                .map(|t| self.type_to_rust(t))
                .unwrap_or_else(|| "()".to_string());
            let param_name = self.to_snake_case(&p.name);
            let default_suffix = p.default.as_ref()
                .map(|d| format!(" = {}", self.expr_to_rust(d)))
                .unwrap_or_default();
            format!("{}: {}{}", param_name, type_str, default_suffix)
        }).collect();

        let return_type = if is_component {
            "VNode".to_string()
        } else {
            f.return_type.as_ref()
                .map(|t| self.type_to_rust(t))
                .unwrap_or_else(|| "()".to_string())
        };

        let generics_str = if !f.generics.is_empty() {
            format!("<{}>", f.generics.iter().map(|g| g.name.clone()).collect::<Vec<_>>().join(", "))
        } else {
            String::new()
        };

        output.push_str(&format!(
            "pub fn {}{}({}) -> {} {{\n",
            rust_name, generics_str, params.join(", "), return_type
        ));

        if let Some(body) = &f.body {
            for stmt in &body.0 {
                let stmt_code = self.stmt_to_rust(stmt)?;
                if !stmt_code.trim().is_empty() {
                    output.push_str("    ");
                    output.push_str(&stmt_code);
                    output.push('\n');
                }
            }
        }

        output.push_str("}\n");

        Ok(output)
    }

    fn generate_variable(&self, var: &VariableDecl) -> Result<String> {
        let name = self.to_snake_case(&var.name);
        let type_suffix = var.type_.as_ref()
            .map(|t| format!(": {}", self.type_to_rust(t)))
            .unwrap_or_default();
        
        let init = if let Some(expr) = &var.init {
            self.expr_to_rust(expr)
        } else {
            "()".to_string()
        };
        
        let keyword = match var.kind {
            VariableKind::Const => "let",
            VariableKind::Let => "let mut",
            VariableKind::Var => "let mut",
        };
        
        Ok(format!("{} {}: {} = {};\n", keyword, name, type_suffix, init))
    }

    fn stmt_to_rust(&self, stmt: &Stmt) -> Result<String> {
        match stmt {
            Stmt::Empty => Ok(String::new()),
            Stmt::Block(stmts) => {
                let mut output = "{\n".to_string();
                for s in stmts {
                    output.push_str(&format!("    {}\n", self.stmt_to_rust(s)?));
                }
                output.push_str("}");
                Ok(output)
            }
            Stmt::Expr { expr } => Ok(format!("{};", self.expr_to_rust(expr))),
            Stmt::Return { arg } => {
                if let Some(e) = arg {
                    Ok(format!("return {};", self.expr_to_rust(e)))
                } else {
                    Ok("return;".to_string())
                }
            }
            Stmt::If { test, consequent, alternate } => {
                let test_code = self.expr_to_rust(test);
                let then_code = self.stmt_to_rust(consequent)?;
                if let Some(alt) = alternate {
                    let else_code = self.stmt_to_rust(alt)?;
                    Ok(format!("if {} {{ {} }} else {{ {} }}", test_code, then_code, else_code))
                } else {
                    Ok(format!("if {} {{ {} }}", test_code, then_code))
                }
            }
            Stmt::While { test, body } => {
                let test_code = self.expr_to_rust(test);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("while {} {{ {} }}", test_code, body_code))
            }
            Stmt::For { init, test, update, body, .. } => {
                let init_code = init.as_ref().map(|i| self.for_init_to_rust(i)).unwrap_or_default();
                let test_code = test.as_ref().map(|t| self.expr_to_rust(t)).unwrap_or_default();
                let update_code = update.as_ref().map(|u| self.expr_to_rust(u)).unwrap_or_default();
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {}; {}; {} {{ {} }}", init_code, test_code, update_code, body_code))
            }
            Stmt::ForIn { left, right, body, .. } => {
                let left_code = self.for_init_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
            }
            Stmt::ForOf { left, right, body, .. } => {
                let left_code = self.for_init_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
            }
            Stmt::Switch { discriminant, cases } => {
                let disc_code = self.expr_to_rust(discriminant);
                let mut output = format!("match {} {{\n", disc_code);
                for case in cases {
                    let test_code = case.test.as_ref()
                        .map(|t| self.expr_to_rust(t))
                        .unwrap_or_else(|| "_".to_string());
                    let cons_code = self.stmt_to_rust(&Stmt::Block(case.consequent.clone()))?;
                    output.push_str(&format!("    {} => {{ {} }}\n", test_code, cons_code));
                }
                output.push_str("}");
                Ok(output)
            }
            Stmt::Break { .. } => Ok("break;".to_string()),
            Stmt::Continue { .. } => Ok("continue;".to_string()),
            Stmt::Throw { arg } => Ok(format!("panic!(\"{}\");", self.expr_to_rust(arg))),
            Stmt::Try { block, handler, finalizer } => {
                let block_code = self.stmt_to_rust(block)?;
                let mut output = format!("let __result = (|| {{ {} }})();\n", block_code);
                if let Some(h) = handler {
                    let handler_code = self.stmt_to_rust(h)?;
                    output.push_str(&handler_code);
                }
                if let Some(f) = finalizer {
                    let final_code = self.stmt_to_rust(f)?;
                    output.push_str(&final_code);
                }
                Ok(output)
            }
            Stmt::Debugger => Ok(String::new()),
            Stmt::With { .. } => Err(anyhow!("with statement is not supported")),
            Stmt::Label { .. } => Err(anyhow!("labeled statement is not supported")),
            Stmt::DoWhile { .. } => Err(anyhow!("do-while statement is not supported")),
            Stmt::Variable { decl } => self.generate_variable(decl),
            Stmt::Function { decl } => self.generate_function(decl, false),
            Stmt::Class { decl } => Err(anyhow!("class {} is not supported", decl.name)),
        }
    }

    fn for_init_to_rust(&self, init: &ForInit) -> String {
        match init {
            ForInit::Variable(v) => self.generate_variable(v).unwrap_or_default(),
            ForInit::Expr(e) => self.expr_to_rust(e),
        }
    }

    pub fn expr_to_rust(&self, expr: &Expr) -> String {
        match expr {
            Expr::Ident { name } => self.to_snake_case(name),
            Expr::String(s) => format!("{:?}", s),
            Expr::Number(n) => n.to_string(),
            Expr::BigInt(n) => n.to_string(),
            Expr::Boolean(b) => b.to_string(),
            Expr::Null => "None".to_string(),
            Expr::Undefined => "()".to_string(),
            Expr::RegExp { .. } => "()".to_string(),
            Expr::Template { parts, exprs } => {
                let mut result = String::new();
                for (i, part) in parts.iter().enumerate() {
                    if let TemplatePart::String(s) = part {
                        result.push_str(s);
                    }
                    if i < exprs.len() {
                        result.push_str(&format!("{{{}}}", self.expr_to_rust(&exprs[i])));
                    }
                }
                result
            }
            Expr::Bin { left, op, right } => {
                let left_code = self.expr_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let rust_op = match op {
                    BinaryOp::Eq | BinaryOp::EqStrict => "==",
                    BinaryOp::Ne | BinaryOp::NeStrict => "!=",
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    BinaryOp::Ge => ">=",
                    BinaryOp::BitAnd => "&",
                    BinaryOp::BitOr => "|",
                    BinaryOp::BitXor => "^",
                    BinaryOp::LeftShift => "<<",
                    BinaryOp::RightShift => ">>",
                    BinaryOp::In => "in",
                    BinaryOp::InstanceOf => "is",
                    _ => "+",
                };
                format!("({} {} {})", left_code, rust_op, right_code)
            }
            Expr::Unary { op, arg, .. } => {
                let arg_code = self.expr_to_rust(arg);
                let rust_op = match op {
                    UnaryOp::Minus => "-",
                    UnaryOp::Plus => "+",
                    UnaryOp::Not => "!",
                    UnaryOp::BitNot => "!",
                    UnaryOp::TypeOf => "std::any::type_name",
                    UnaryOp::Void => "()",
                };
                format!("({}{})", rust_op, arg_code)
            }
            Expr::Update { op, arg, .. } => {
                let arg_code = if let Expr::Ident { name } = arg.as_ref() {
                    self.to_snake_case(name)
                } else {
                    self.expr_to_rust(arg)
                };
                match op {
                    UpdateOp::Increment => format!("{} += 1", arg_code),
                    UpdateOp::Decrement => format!("{} -= 1", arg_code),
                }
            }
            Expr::Logical { left, op, right } => {
                let left_code = self.expr_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let rust_op = match op {
                    LogicalOp::And => "&&",
                    LogicalOp::Or => "||",
                    LogicalOp::NullishCoalesce => "unwrap_or",
                };
                format!("({} {} {})", left_code, rust_op, right_code)
            }
            Expr::Cond { test, consequent, alternate } => {
                let test_code = self.expr_to_rust(test);
                let cons_code = self.expr_to_rust(consequent);
                let alt_code = self.expr_to_rust(alternate);
                format!("if {} {{ {} }} else {{ {} }}", test_code, cons_code, alt_code)
            }
            Expr::Call { callee, args, .. } => {
                let callee_code = self.expr_to_rust(callee);
                let args_code: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                format!("{}({})", callee_code, args_code.join(", "))
            }
            Expr::New { callee, args, .. } => {
                let callee_code = self.expr_to_rust(callee);
                let args_code: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                format!("{}::new({})", callee_code, args_code.join(", "))
            }
            Expr::Await { arg } => format!("{}.await", self.expr_to_rust(arg)),
            Expr::Yield { arg, .. } => {
                if let Some(a) = arg {
                    format!("yield {}", self.expr_to_rust(a))
                } else {
                    "yield".to_string()
                }
            }
            Expr::Member { object, property, computed, .. } => {
                let obj_code = self.expr_to_rust(object);
                let prop_code = if *computed {
                    self.expr_to_rust(property)
                } else {
                    if let Expr::Ident { name } = property.as_ref() {
                        name.clone()
                    } else {
                        self.expr_to_rust(property)
                    }
                };
                format!("{}.{}", obj_code, prop_code)
            }
            Expr::Object { props } => {
                let fields: Vec<String> = props.iter().map(|p| {
                    match p {
                        ObjectProp::Init { key, value } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(e) => self.expr_to_rust(e),
                            };
                            let v = self.expr_to_rust(value);
                            format!("{}: {}", self.to_snake_case(&k), v)
                        }
                        ObjectProp::Method { key, value: _ } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            format!("{}(_) {{}}", self.to_snake_case(&k))
                        }
                        ObjectProp::Shorthand { name } => self.to_snake_case(name),
                        ObjectProp::Spread { value } => format!("..{{{}}}", self.expr_to_rust(value)),
                        ObjectProp::Get { key, .. } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            format!("get {}() {{}}", self.to_snake_case(&k))
                        }
                        ObjectProp::Set { key, value, .. } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            let t = value.params.first()
                                .and_then(|p| p.type_.as_ref())
                                .map(|t| self.type_to_rust(t))
                                .unwrap_or_else(|| "serde_json::Value".to_string());
                            format!("set {}(_: {}) {{}}", self.to_snake_case(&k), t)
                        }
                    }
                }).collect();
                format!("{{{}}}", fields.join(", "))
            }
            Expr::Array { elems } => {
                let elems_code: Vec<String> = elems.iter().map(|e| {
                    e.as_ref().map(|e| self.expr_to_rust(e)).unwrap_or_default()
                }).collect();
                format!("vec![{}]", elems_code.join(", "))
            }
            Expr::Arrow { params, body, .. } => {
                let params_code: Vec<String> = params.iter().map(|p| {
                    let name = self.to_snake_case(&p.name);
                    p.type_.as_ref()
                        .map(|t| format!("{}: {}", name, self.type_to_rust(t)))
                        .unwrap_or(name)
                }).collect();
                
                // Handle block body vs expression body
                let body_code = match body.as_ref() {
                    Stmt::Block(stmts) => {
                        let inner: Vec<String> = stmts.iter()
                            .map(|s| self.stmt_to_rust(s).unwrap_or_default())
                            .filter(|s| !s.trim().is_empty())
                            .collect();
                        if inner.is_empty() {
                            "{}".to_string()
                        } else {
                            format!("{{ {} }}", inner.join("; "))
                        }
                    }
                    Stmt::Return { arg } => {
                        if let Some(expr) = arg {
                            format!("{{ {} }}", self.expr_to_rust(expr))
                        } else {
                            "{}".to_string()
                        }
                    }
                    other => self.stmt_to_rust(other).unwrap_or_default(),
                };
                
                format!("|{}| {}", params_code.join(", "), body_code)
            }
            Expr::Function { decl } => {
                let params: Vec<String> = decl.params.iter().map(|p| {
                    let name = self.to_snake_case(&p.name);
                    p.type_.as_ref()
                        .map(|t| format!("{}: {}", name, self.type_to_rust(t)))
                        .unwrap_or(name)
                }).collect();
                
                if let Some(body) = &decl.body {
                    let body_code = body.0.iter().map(|s| self.stmt_to_rust(s).unwrap_or_default()).collect::<Vec<_>>().join("\n");
                    format!("|{}| {{\n{}}}", params.join(", "), body_code)
                } else {
                    format!("|{}| {{}}", params.join(", "))
                }
            }
            Expr::Assign { left, right, .. } => {
                let left_code = if let Expr::Ident { name } = left.as_ref() {
                    self.to_snake_case(name)
                } else {
                    self.expr_to_rust(left)
                };
                let right_code = self.expr_to_rust(right);
                match (left.as_ref(), right.as_ref()) {
                    (Expr::Ident { .. }, _) => format!("{} = {}", left_code, right_code),
                    _ => format!("{} = {}", left_code, right_code),
                }
            }
            Expr::Seq { exprs } => {
                exprs.iter().map(|e| self.expr_to_rust(e)).collect::<Vec<_>>().join(", ")
            }
            Expr::Class { .. } => "()".to_string(),
            Expr::TaggedTemplate { tag, .. } => {
                format!("{}(...)", self.expr_to_rust(tag))
            }
            Expr::JSX(x) => self.jsx_to_rust(x),
            Expr::TSAs { expr, .. } => self.expr_to_rust(expr),
            Expr::Spread { arg } => format!("..{}", self.expr_to_rust(arg)),
            Expr::MetaProp { kind } => match kind {
                MetaPropKind::NewTarget => "__rt__.new_target",
                MetaPropKind::ImportMeta => "__rt__.import_meta",
            }.to_string(),
        }
    }

    pub fn jsx_to_rust(&self, x: &JSXExpr) -> String {
        let tag_name = match &x.opening.name {
            JSXName::Ident(s) => s.clone(),
            JSXName::Member { object, property } => format!("{}_{}", object, property),
            JSXName::Namespaced { ns, name } => format!("{}_{}", ns, name),
            JSXName::Dynamic(_) => "Dynamic".to_string(),
        };

        let attrs: Vec<String> = x.opening.attrs.iter().filter_map(|a| {
            match a {
                JSXAttr::Attr { name, value } => {
                    let rust_name = self.jsx_attr_to_rust(name);
                    let value_code = value.as_ref()
                        .map(|v| self.jsx_attr_value_to_rust(v))
                        .unwrap_or_else(|| "true".to_string());
                    Some(format!("{}: {}", rust_name, value_code))
                }
                JSXAttr::Spread { expr } => {
                    Some(format!("..{{{}}}", self.expr_to_rust(expr)))
                }
                JSXAttr::Event { name, handler } => {
                    let rust_name = self.jsx_attr_to_rust(name);
                    Some(format!("{}: {}", rust_name, self.expr_to_rust(handler)))
                }
                JSXAttr::Bool { name } => {
                    Some(format!("{}: {}", self.jsx_attr_to_rust(name), "true"))
                }
                JSXAttr::Expr { name, expr } => {
                    if let Some(n) = name {
                        let rust_name = self.jsx_attr_to_rust(n);
                        Some(format!("{}: {}", rust_name, self.expr_to_rust(expr)))
                    } else {
                        Some(self.expr_to_rust(expr))
                    }
                }
            }
        }).collect();

        let children: Vec<String> = x.children.iter().map(|c| self.jsx_child_to_rust(c)).collect();

        let attrs_str = if attrs.is_empty() {
            String::new()
        } else {
            format!(" {}", attrs.join(" "))
        };

        if x.opening.self_closing {
            format!("html!(<{}{}/>)", self.to_snake_case(&tag_name), attrs_str)
        } else {
            format!(
                "html!(<{}{}>{}</{}>)",
                self.to_snake_case(&tag_name),
                attrs_str,
                children.join(""),
                self.to_snake_case(&tag_name)
            )
        }
    }

    fn jsx_attr_value_to_rust(&self, v: &JSXAttrValue) -> String {
        match v {
            JSXAttrValue::String(s) => format!("{:?}", s),
            JSXAttrValue::Expr(e) => self.expr_to_rust(e),
        }
    }

    fn jsx_child_to_rust(&self, child: &JSXChild) -> String {
        match child {
            JSXChild::Text(s) => format!("{:?}", s),
            JSXChild::Expr(e) => self.expr_to_rust(e),
            JSXChild::JSX(x) => self.jsx_to_rust(x),
            JSXChild::Fragment { children } => {
                let inner: Vec<String> = children.iter().map(|c| self.jsx_child_to_rust(c)).collect();
                format!("<>{}</>", inner.join(""))
            }
            JSXChild::Fragment { children } => {
                // Fragment children are concatenated directly (JSX fragments don't need <> wrapper in Rust html!)
                let inner: Vec<String> = children.iter().map(|c| self.jsx_child_to_rust(c)).collect();
                inner.join(" ")
            }
            JSXChild::Spread { expr } => self.expr_to_rust(expr),
        }
    }

    pub fn jsx_attr_to_rust(&self, name: &str) -> String {
        match name {
            "class" | "className" => "class_name".to_string(),
            "for" | "htmlFor" => "for_id".to_string(),
            "tabindex" => "tab_index".to_string(),
            _ if name.starts_with("on") && name.len() > 2 && name.chars().nth(2).map(|c| c.is_uppercase()).unwrap_or(false) => {
                // Event handlers like onClick -> on_click, onChange -> on_change
                let event_part = &name[2..];
                format!("on_{}", self.to_snake_case(event_part))
            }
            _ => {
                if name.contains('-') {
                    self.to_snake_case(name)
                } else {
                    name.to_string()
                }
            }
        }
    }

    pub fn to_snake_case(&self, s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_snake_case() {
        let cg = CodeGenerator::new();
        assert_eq!(cg.to_snake_case("useState"), "use_state");
        assert_eq!(cg.to_snake_case("onClick"), "on_click");
        assert_eq!(cg.to_snake_case("className"), "class_name");
    }
}
