//! Code generator: High-level IR → Rust source code
//!
//! This module transforms the HIR (High-Level IR) into idiomatic Rust code
//! that compiles to efficient native binaries.

use super::hir::*;
use anyhow::{anyhow, Result};

/// Code generator for producing Rust source from HIR
pub struct CodeGenerator {
    /// Generated imports to include (for future use)
    #[allow(dead_code)]
    imports: Vec<String>,
    /// Current indent level (for future pretty-printing)
    #[allow(dead_code)]
    indent: usize,
    /// Whether to generate route handlers for default-export components
    generate_handlers: bool,
}

impl Default for CodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            imports: vec![
                "use runts_lib::runtime::prelude::*;".to_string(),
                "use serde::{Serialize, Deserialize};".to_string(),
            ],
            indent: 0,
            generate_handlers: true,
        }
    }

    /// Set whether to generate route handlers for default-export components.
    pub fn set_generate_handlers(&mut self, value: bool) {
        self.generate_handlers = value;
    }

    /// Generate indented output
    fn indent(&self) -> String {
        "    ".repeat(self.indent)
    }

    /// Generate Rust code for a module
    pub fn generate_module(&mut self, module: &Module) -> Result<String> {
        let mut output = String::new();

        output.push_str("//! Generated by runts\n");
        if !module.source.is_empty() {
            output.push_str(&format!("//! Source: {}\n", module.source));
        }
        output.push('\n');
        output.push_str("use runts_lib::runtime::prelude::*;\n");
        output.push_str("use serde::{Serialize, Deserialize};\n");
        output.push_str("use axum::{response::IntoResponse, body::Body};\n");
        output.push('\n');

        for item in &module.items {
            if let ModuleItem::Decl(Decl::Type(t)) = item {
                let type_code = self.generate_type_decl(t)?;
                if !type_code.trim().is_empty() {
                    output.push_str(&type_code);
                    output.push_str("\n");
                }
            }
        }

        let mut default_component_name: Option<String> = None;
        let mut has_handler_export = false;

        for item in &module.items {
            if let ModuleItem::Decl(decl) = item {
                if matches!(decl, Decl::Type(_)) {
                    continue;
                }
                let decl_code = self.generate_decl(decl)?;
                if !decl_code.trim().is_empty() {
                    output.push_str(&decl_code);
                    output.push_str("\n\n");
                }
            }
            
            if let ModuleItem::Export(export) = item {
                match export {
                    Export::Default { expr } => {
                        if let Expr::Function { decl } = expr {
                            default_component_name = Some(decl.name.clone());
                            let fn_code = self.generate_function(decl, true)?;
                            if !fn_code.trim().is_empty() {
                                output.push_str(&fn_code);
                                output.push_str("\n\n");
                            }
                        }
                    }
                    Export::NamedWithValue { name, value } => {
                        // Handle route handlers: export const handler = { GET: async (req, ctx) => { ... } }
                        if name == "handler" {
                            has_handler_export = true;
                            let handler_code = self.generate_route_handler(value)?;
                            if !handler_code.trim().is_empty() {
                                output.push_str(&handler_code);
                                output.push_str("\n\n");
                            }
                        } else {
                            // Other named exports with values
                            let value_code = self.expr_to_rust(value);
                            output.push_str(&format!("pub const {}: () = {};\n\n", name, value_code));
                        }
                    }
                    _ => {}
                }
            }
        }

        // If there's a default export component but no explicit handler,
        // generate a default GET handler that renders the component.
        if self.generate_handlers {
            if let Some(component_name) = default_component_name {
                if !has_handler_export {
                    let fn_name = self.to_snake_case(&component_name);
                    output.push_str(&format!(
                        "pub async fn handle_get() -> impl IntoResponse {{\n    {}()\n}}\n",
                        fn_name
                    ));
                }
            }
        }

        Ok(output)
    }
    
    /// Generate Rust route handler from an object literal
    fn generate_route_handler(&self, expr: &Expr) -> Result<String> {
        // Handler should be an object: { GET, POST, etc. }
        if let Expr::Object { props } = expr {
            let mut output = String::new();
            
            for prop in props {
                let (method_name, value) = match prop {
                    ObjectProp::Init { key, value } => {
                        let name = match key {
                            PropKey::Ident(s) => s.clone(),
                            PropKey::String(s) => s.clone(),
                            _ => continue,
                        };
                        (name, value.clone())
                    }
                    ObjectProp::Method { key, value } => {
                        let name = match key {
                            PropKey::Ident(s) => s.clone(),
                            PropKey::String(s) => s.clone(),
                            _ => continue,
                        };
                        (name, Expr::Function { decl: value.clone() })
                    }
                    _ => continue,
                };
                
                // Generate handler function for this method
                let handler_fn = self.generate_handler_method(&method_name, &value)?;
                output.push_str(&handler_fn);
                output.push_str("\n\n");
            }
            
            Ok(output)
        } else {
            Ok(String::new())
        }
    }
    
    /// Generate a single handler method (GET, POST, etc.)
    fn generate_handler_method(&self, method: &str, value: &Expr) -> Result<String> {
        let method_lower = method.to_lowercase();
        let handler_name = format!("handle_{}", method_lower);
        
        let (is_async, params, body) = match value {
            Expr::Arrow { params, body, is_async } => (*is_async, params.clone(), body.clone()),
            Expr::Function { decl } => {
                let body_stmt = decl.body.as_ref()
                    .map(|b| Stmt::Block(b.0.clone()))
                    .unwrap_or(Stmt::Block(vec![]));
                (decl.is_async, decl.params.clone(), Box::new(body_stmt))
            }
            _ => {
                return Ok(format!(
                    "pub fn {}() -> impl Fn(Request, HandlerContext) -> Response {{
    |_, _| {{
        Response::builder().status(501).body(Body::from(\"Not Implemented\")).unwrap()
    }}
}}",
                    handler_name
                ));
            }
        };

        let async_prefix = if is_async { "async " } else { "" };
        let params_str = params.iter().map(|p| {
            let name = self.to_snake_case(&p.name);
            p.type_.as_ref()
                .map(|t| format!("{}: {}", name, self.type_to_rust(t)))
                .unwrap_or_else(|| name)
        }).collect::<Vec<_>>().join(", ");
        
        let body_str = match body.as_ref() {
            Stmt::Block(stmts) => {
                let mut lines = Vec::new();
                for stmt in stmts {
                    let code = self.stmt_to_rust(stmt)?;
                    if !code.trim().is_empty() {
                        lines.push(code.trim().to_string());
                    }
                }
                if lines.is_empty() {
                    "{ Response::builder().status(501).body(Body::from(\"Not Implemented\")).unwrap() }".to_string()
                } else {
                    format!("{{ {} }}", lines.join("; "))
                }
            }
            Stmt::Return { arg } => {
                if let Some(e) = arg {
                    let expr_str = self.expr_to_rust(e);
                    format!("{{ return {}; }}", expr_str)
                } else {
                    "{}".to_string()
                }
            }
            _ => "{ Response::builder().status(501).body(Body::from(\"Not Implemented\")).unwrap() }".to_string(),
        };
        
        Ok(format!(
            r#"pub {}fn {}({}) -> impl IntoResponse {{
    {} // Handler body
}}"#,
            async_prefix,
            handler_name,
            params_str,
            body_str
        ))
    }

    /// Generate Response::builder() code from new Response(body, init) args
    fn generate_new_response(&self, args: &[Expr]) -> String {
        let body = args.first().map(|a| self.expr_to_rust(a)).unwrap_or_default();
        let mut lines = vec![
            "{".to_string(),
            format!("    let __body = {};", body),
            "    let mut __resp = Response::builder();".to_string(),
        ];

        // Parse init options object if present
        if let Some(init_expr) = args.get(1) {
            if let Expr::Object { props } = init_expr {
                for prop in props {
                    match prop {
                        ObjectProp::Init { key, value } => {
                            let k = match key {
                                PropKey::Ident(s) | PropKey::String(s) => s.as_str(),
                                _ => continue,
                            };
                            match k {
                                "status" | "statusCode" => {
                                    let v = self.expr_to_rust(value);
                                    lines.push(format!("    __resp = __resp.status({});", v));
                                }
                                "headers" => {
                                    if let Expr::Object { props: header_props } = value {
                                        for hp in header_props {
                                            match hp {
                                                ObjectProp::Init { key: hk, value: hv } => {
                                                    let header_name = match hk {
                                                        PropKey::Ident(s) | PropKey::String(s) => s.clone(),
                                                        _ => continue,
                                                    };
                                                    let header_val = self.expr_to_rust(hv);
                                                    lines.push(format!(
                                                        "    __resp = __resp.header(\"{}\", {});",
                                                        header_name, header_val
                                                    ));
                                                }
                                                _ => {}
                                            }
                                        }
                                    }
                                }
                                _ => {}
                            }
                        }
                        _ => {}
                    }
                }
            }
        }

        lines.push("    __resp.body(Body::from(__body)).unwrap()".to_string());
        lines.push("}".to_string());
        lines.join("\n")
    }

    pub fn generate_type_decl(&self, decl: &TypeDecl) -> Result<String> {
        let name = &decl.name;
        let generics_str = if !decl.generics.is_empty() {
            format!("<{}>", decl.generics.iter().map(|g| g.name.clone()).collect::<Vec<_>>().join(", "))
        } else {
            String::new()
        };

        let rust_type = self.type_to_rust(&decl.type_);
        
        if let Type::Object { members } = &decl.type_ {
            let mut out = String::new();
            out.push_str("#[derive(Clone, PartialEq, Serialize, Deserialize)]\n");
            out.push_str(&format!("pub struct {}{} {{\n", name, generics_str));
            for member in members {
                let field_type = self.type_to_rust(&member.type_);
                out.push_str(&format!("    pub {}: {},\n", self.to_snake_case(&member.key), field_type));
            }
            out.push_str("}\n");
            return Ok(out);
        }

        Ok(format!("pub type {}{} = {};\n", name, generics_str, rust_type))
    }

    pub fn type_to_rust(&self, t: &Type) -> String {
        match t {
            Type::String => "String".to_string(),
            Type::Number => "f64".to_string(),
            Type::Boolean => "bool".to_string(),
            Type::Null | Type::Undefined | Type::Void => "()".to_string(),
            Type::Never => "!".to_string(),
            Type::Unknown | Type::Any => "serde_json::Value".to_string(),
            Type::BigInt => "i64".to_string(),
            Type::Symbol => "()".to_string(),
            Type::Ref { name, generics } => {
                let args = if !generics.is_empty() {
                    format!("<{}>", generics.iter().map(|g| self.type_to_rust(g)).collect::<Vec<_>>().join(", "))
                } else {
                    String::new()
                };
                match name.as_str() {
                    "PageProps" | "HandlerContext" | "Request" | "Response" => name.clone() + &args,
                    "Record" => format!("std::collections::HashMap{}", args),
                    "Promise" => format!("std::pin::Pin<Box<dyn std::future::Future<Output = {}> + Send>>", args.trim_start_matches('<').trim_end_matches('>')),
                    "Array" => format!("Vec{}", args),
                    "Map" => format!("std::collections::HashMap{}", args),
                    "Set" => format!("std::collections::HashSet{}", args),
                    _ => name.clone() + &args,
                }
            }
            Type::Union { types } => {
                if types.len() == 2 {
                    if let Some(null_pos) = types.iter().position(|t| matches!(t, Type::Null | Type::Undefined)) {
                        let non_null = types.iter().enumerate()
                            .filter(|(i, _)| *i != null_pos)
                            .map(|(_, t)| self.type_to_rust(t))
                            .collect::<Vec<_>>()
                            .join(" | ");
                        return format!("Option<{}>", non_null);
                    }
                }
                types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(" | ")
            }
            Type::Intersection { types } => {
                types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(" + ")
            }
            Type::Array { elem } => format!("Vec<{}>", self.type_to_rust(elem)),
            Type::Tuple { types } => {
                format!("({})", types.iter().map(|t| self.type_to_rust(t)).collect::<Vec<_>>().join(", "))
            }
            Type::Object { members } => {
                if members.is_empty() {
                    "()".to_string()
                } else {
                    let fields: Vec<String> = members.iter().map(|m| {
                        format!("pub {}: {}", self.to_snake_case(&m.key), self.type_to_rust(&m.type_))
                    }).collect();
                    format!("{{{}}}", fields.join(", "))
                }
            }
            Type::Function { params, ret, .. } => {
                let param_str = params.iter().map(|p| self.type_to_rust(p)).collect::<Vec<_>>().join(", ");
                let ret_str = self.type_to_rust(ret);
                format!("Box<dyn Fn({}) -> {} + Send + Sync>", param_str, ret_str)
            }
            Type::Paren { type_ } => self.type_to_rust(type_),
            Type::Index { obj, index } => {
                format!("std::collections::HashMap<{}, {}>", self.type_to_rust(obj), self.type_to_rust(index))
            }
            Type::Conditional { true_type, false_type, .. } => {
                format!("if _ {{ {} }} else {{ {} }}", self.type_to_rust(true_type), self.type_to_rust(false_type))
            }
            Type::Mapped { type_, .. } => {
                format!("std::collections::HashMap<String, {}>", self.type_to_rust(type_))
            }
            Type::Template { parts } => {
                let parts_str: Vec<String> = parts.iter().map(|p| match p {
                    TemplatePart::String(s) => format!("{:?}", s),
                    TemplatePart::Type(t) => self.type_to_rust(t),
                }).collect();
                parts_str.join(" + ")
            }
        }
    }

    fn generate_decl(&mut self, decl: &Decl) -> Result<String> {
        match decl {
            Decl::Function(f) => {
                let is_component = f.name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);
                self.generate_function(f, is_component)
            }
            Decl::Variable(v) => self.generate_variable(v),
            Decl::Type(t) => self.generate_type_decl(t),
            Decl::Class(c) => Err(anyhow!("Class components are not supported: {}", c.name)),
        }
    }

    pub fn generate_function(&self, f: &FunctionDecl, force_component: bool) -> Result<String> {
        let rust_name = self.to_snake_case(&f.name);
        let is_component = force_component 
            || rust_name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);

        let mut output = String::new();

        if is_component {
            output.push_str("#[component]\n");
        }

        // Check if any params have destructuring patterns
        let has_destructuring = f.params.iter().any(|p| p.pattern.is_some());
        
        let params: Vec<String> = f.params.iter().map(|p| {
            let type_str = p.type_.as_ref()
                .map(|t| self.type_to_rust(t))
                .unwrap_or_else(|| "()".to_string());
            // For destructured params, use a simple name (not the pattern name)
            let param_name = if p.pattern.is_some() {
                "_props".to_string()
            } else {
                self.to_snake_case(&p.name)
            };
            // For components, capitalize the type name
            let type_str = if is_component && p.pattern.is_some() {
                // Convert counter_props -> CounterProps
                let capitalized: String = type_str.chars()
                    .map(|c| if c == '_' { ' ' } else { c })
                    .collect::<String>()
                    .split_whitespace()
                    .map(|word| {
                        let mut chars = word.chars();
                        match chars.next() {
                            None => String::new(),
                            Some(first) => first.to_uppercase().chain(chars).collect(),
                        }
                    })
                    .collect::<Vec<_>>()
                    .join("");
                capitalized
            } else {
                type_str
            };
            // Don't include default for destructured params - we'll handle defaults in destructuring
            let default_suffix = if p.pattern.is_none() {
                p.default.as_ref()
                    .map(|d| format!(" = {}", self.expr_to_rust(d)))
                    .unwrap_or_default()
            } else {
                String::new()
            };
            format!("{}: {}{}", param_name, type_str, default_suffix)
        }).collect();

        // For components, always return VNode (even if body is empty)
        let return_type = if is_component {
            "VNode".to_string()
        } else {
            f.return_type.as_ref()
                .map(|t| self.type_to_rust(t))
                .unwrap_or_else(|| "()".to_string())
        };

        let generics_str = if !f.generics.is_empty() {
            format!("<{}>", f.generics.iter().map(|g| g.name.clone()).collect::<Vec<_>>().join(", "))
        } else {
            String::new()
        };

        output.push_str(&format!(
            "pub fn {}{}({}) -> {} {{\n",
            rust_name, generics_str, params.join(", "), return_type
        ));
        
        // Generate destructuring code at the start of the function body
        if has_destructuring {
            for p in &f.params {
                if let Some(ref pattern) = p.pattern {
                    // Source name is the parameter name (_props)
                    let source = "_props";
                    let destructured = self.pat_to_rust(pattern, source);
                    for binding in destructured {
                        output.push_str(&format!("    let {};\n", binding));
                    }
                }
            }
        }

        if let Some(body) = &f.body {
            for stmt in &body.0 {
                let stmt_code = self.stmt_to_rust(stmt)?;
                if !stmt_code.trim().is_empty() {
                    output.push_str("    ");
                    output.push_str(&stmt_code);
                    output.push('\n');
                }
            }
        }

        output.push_str("}\n");

        Ok(output)
    }
    
    /// Convert a destructuring pattern to Rust let bindings
    /// Returns a list of individual let bindings since Rust doesn't support
    /// JavaScript-style object destructuring syntax.
    fn pat_to_rust(&self, pat: &Pat, source_name: &str) -> Vec<String> {
        match pat {
            Pat::Object { props, .. } => {
                let mut bindings = Vec::new();
                for prop in props {
                    match prop {
                        ObjectPatProp::Init { key, value } => {
                            if let Pat::Ident { name, .. } = value {
                                // Generate: let name = source.key;
                                bindings.push(format!(
                                    "{} = {}.{}",
                                    self.to_snake_case(name),
                                    source_name,
                                    self.to_snake_case(key)
                                ));
                            }
                        }
                        ObjectPatProp::Rest { arg } => {
                            if let Pat::Ident { name, .. } = arg.as_ref() {
                                // For rest props, we use a HashMap subset
                                bindings.push(format!(
                                    "{} = std::collections::HashMap::new()",
                                    self.to_snake_case(name)
                                ));
                            }
                        }
                    }
                }
                bindings
            }
            Pat::Array { elems, rest } => {
                // For array destructuring like [a, b, ...rest] = tuple
                // Generate individual let bindings for each element
                let mut bindings = Vec::new();
                
                for (i, elem) in elems.iter().enumerate() {
                    if let Some(Pat::Ident { name, .. }) = elem {
                        let rust_name = self.to_snake_case(name);
                        bindings.push(format!("{} = {}.{}", rust_name, source_name, i));
                    }
                }
                
                if let Some(rest) = rest {
                    if let Pat::Ident { name, .. } = rest.as_ref() {
                        let rust_name = self.to_snake_case(name);
                        bindings.push(format!(
                            "{} = {}.into_iter().skip({}).collect::<Vec<_>>()",
                            rust_name,
                            source_name,
                            elems.len()
                        ));
                    }
                }
                
                bindings
            }
            Pat::Ident { name, .. } => {
                vec![format!("{} = {}", self.to_snake_case(name), source_name)]
            }
            _ => vec![],
        }
    }

    fn generate_variable(&self, var: &VariableDecl) -> Result<String> {
        let keyword = match var.kind {
            VariableKind::Const => "let",
            VariableKind::Let => "let mut",
            VariableKind::Var => "let mut",
        };

        let type_hint = var.type_.as_ref();

        let init = if let Some(expr) = &var.init {
            // If the init is an object literal and we have a struct type hint,
            // prefix the object literal with the struct name.
            if let (Expr::Object { .. }, Some(Type::Ref { name, .. })) = (expr, type_hint) {
                let obj_code = self.expr_to_rust(expr);
                // obj_code is like "{ a: 1, b: 2 }" — prefix with struct name
                format!("{} {}", name, obj_code)
            } else {
                self.expr_to_rust(expr)
            }
        } else {
            "()".to_string()
        };

        // Handle destructuring patterns (e.g., const [a, b] = useState())
        if let Some(ref pattern) = var.pattern {
            let bindings = self.pat_to_rust(pattern, &init);
            if bindings.is_empty() {
                Ok(String::new())
            } else if bindings.len() == 1 {
                Ok(format!("{} {};\n", keyword, bindings[0]))
            } else {
                // Multiple bindings: evaluate init once into a temp, then destructure
                use std::sync::atomic::{AtomicUsize, Ordering};
                static COUNTER: AtomicUsize = AtomicUsize::new(0);
                let tmp = format!("__runts_tmp_{}", COUNTER.fetch_add(1, Ordering::Relaxed));
                let mut stmts = vec![format!("let {} = {};\n", tmp, init)];
                let rebound = self.pat_to_rust(pattern, &tmp);
                for b in rebound {
                    stmts.push(format!("{} {};\n", keyword, b));
                }
                Ok(stmts.join(""))
            }
        } else {
            let name = self.to_snake_case(&var.name);

            // Only add type annotation if present
            if let Some(t) = type_hint {
                Ok(format!("{} {}: {} = {};\n", keyword, name, self.type_to_rust(t), init))
            } else {
                Ok(format!("{} {} = {};\n", keyword, name, init))
            }
        }
    }

    fn stmt_to_rust(&self, stmt: &Stmt) -> Result<String> {
        match stmt {
            Stmt::Empty => Ok(String::new()),
            Stmt::Block(stmts) => {
                let mut output = "{\n".to_string();
                for s in stmts {
                    output.push_str(&format!("    {}\n", self.stmt_to_rust(s)?));
                }
                output.push_str("}");
                Ok(output)
            }
            Stmt::Expr { expr } => Ok(format!("{};", self.expr_to_rust(expr))),
            Stmt::Return { arg } => {
                if let Some(e) = arg {
                    Ok(format!("return {};", self.expr_to_rust(e)))
                } else {
                    Ok("return;".to_string())
                }
            }
            Stmt::If { test, consequent, alternate } => {
                let test_code = self.expr_to_rust(test);
                let then_code = self.stmt_to_rust(consequent)?;
                if let Some(alt) = alternate {
                    let else_code = self.stmt_to_rust(alt)?;
                    Ok(format!("if {} {{ {} }} else {{ {} }}", test_code, then_code, else_code))
                } else {
                    Ok(format!("if {} {{ {} }}", test_code, then_code))
                }
            }
            Stmt::While { test, body } => {
                let test_code = self.expr_to_rust(test);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("while {} {{ {} }}", test_code, body_code))
            }
            Stmt::For { init, test, update, body, .. } => {
                let init_code = init.as_ref().map(|i| self.for_init_to_rust(i)).unwrap_or_default();
                let test_code = test.as_ref().map(|t| self.expr_to_rust(t)).unwrap_or_default();
                let update_code = update.as_ref().map(|u| self.expr_to_rust(u)).unwrap_or_default();
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {}; {}; {} {{ {} }}", init_code, test_code, update_code, body_code))
            }
            Stmt::ForIn { left, right, body, .. } => {
                let left_code = self.for_init_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
            }
            Stmt::ForOf { left, right, body, .. } => {
                let left_code = self.for_init_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let body_code = self.stmt_to_rust(body)?;
                Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
            }
            Stmt::Switch { discriminant, cases } => {
                let disc_code = self.expr_to_rust(discriminant);
                let mut output = format!("match {} {{\n", disc_code);
                for case in cases {
                    let test_code = case.test.as_ref()
                        .map(|t| self.expr_to_rust(t))
                        .unwrap_or_else(|| "_".to_string());
                    let cons_code = self.stmt_to_rust(&Stmt::Block(case.consequent.clone()))?;
                    output.push_str(&format!("    {} => {{ {} }}\n", test_code, cons_code));
                }
                output.push_str("}");
                Ok(output)
            }
            Stmt::Break { .. } => Ok("break;".to_string()),
            Stmt::Continue { .. } => Ok("continue;".to_string()),
            Stmt::Throw { arg } => Ok(format!("panic!(\"{}\");", self.expr_to_rust(arg))),
            Stmt::Try { block, handler, finalizer } => {
                let block_code = self.stmt_to_rust(block)?;
                let mut output = format!("let __result = (|| {{ {} }})();\n", block_code);
                if let Some(h) = handler {
                    let handler_code = self.stmt_to_rust(h)?;
                    output.push_str(&handler_code);
                }
                if let Some(f) = finalizer {
                    let final_code = self.stmt_to_rust(f)?;
                    output.push_str(&final_code);
                }
                Ok(output)
            }
            Stmt::Debugger => Ok(String::new()),
            Stmt::With { .. } => Err(anyhow!("with statement is not supported")),
            Stmt::Label { .. } => Err(anyhow!("labeled statement is not supported")),
            Stmt::DoWhile { .. } => Err(anyhow!("do-while statement is not supported")),
            Stmt::Variable { decl } => {
                // For variable statements, remove the trailing newline
                let mut code = self.generate_variable(decl)?;
                code.pop(); // Remove trailing newline
                Ok(code)
            }
            Stmt::Function { decl } => self.generate_function(decl, false),
            Stmt::Class { decl } => Err(anyhow!("class {} is not supported", decl.name)),
        }
    }

    fn for_init_to_rust(&self, init: &ForInit) -> String {
        match init {
            ForInit::Variable(v) => self.generate_variable(v).unwrap_or_default(),
            ForInit::Expr(e) => self.expr_to_rust(e),
        }
    }

    pub fn expr_to_rust(&self, expr: &Expr) -> String {
        match expr {
            Expr::Ident { name } => self.to_snake_case(name),
            Expr::String(s) => format!("{:?}", s),
            Expr::Number(n) => {
                let s = n.to_string();
                if s.contains('.') || s.contains('e') || s == "inf" || s == "nan" {
                    s
                } else {
                    format!("{}.0", s)
                }
            }
            Expr::BigInt(n) => n.to_string(),
            Expr::Boolean(b) => b.to_string(),
            Expr::Null => "None".to_string(),
            Expr::Undefined => "()".to_string(),
            Expr::RegExp { .. } => "()".to_string(),
            Expr::Template { parts, exprs } => {
                let mut result = String::new();
                for (i, part) in parts.iter().enumerate() {
                    if let TemplatePart::String(s) = part {
                        result.push_str(s);
                    }
                    if i < exprs.len() {
                        result.push_str(&format!("{{{}}}", self.expr_to_rust(&exprs[i])));
                    }
                }
                result
            }
            Expr::Bin { left, op, right } => {
                let left_code = self.expr_to_rust(left);
                let right_code = self.expr_to_rust(right);
                let rust_op = match op {
                    BinaryOp::Eq | BinaryOp::EqStrict => "==",
                    BinaryOp::Ne | BinaryOp::NeStrict => "!=",
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Lt => "<",
                    BinaryOp::Le => "<=",
                    BinaryOp::Gt => ">",
                    BinaryOp::Ge => ">=",
                    BinaryOp::BitAnd => "&",
                    BinaryOp::BitOr => "|",
                    BinaryOp::BitXor => "^",
                    BinaryOp::LeftShift => "<<",
                    BinaryOp::RightShift => ">>",
                    BinaryOp::In => "in",
                    BinaryOp::InstanceOf => "is",
                    _ => "+",
                };
                format!("({} {} {})", left_code, rust_op, right_code)
            }
            Expr::Unary { op, arg, .. } => {
                let arg_code = self.expr_to_rust(arg);
                let rust_op = match op {
                    UnaryOp::Minus => "-",
                    UnaryOp::Plus => "+",
                    UnaryOp::Not => "!",
                    UnaryOp::BitNot => "!",
                    UnaryOp::TypeOf => "std::any::type_name",
                    UnaryOp::Void => "()",
                };
                format!("({}{})", rust_op, arg_code)
            }
            Expr::Update { op, arg, .. } => {
                let arg_code = if let Expr::Ident { name } = arg.as_ref() {
                    self.to_snake_case(name)
                } else {
                    self.expr_to_rust(arg)
                };
                match op {
                    UpdateOp::Increment => format!("{} += 1", arg_code),
                    UpdateOp::Decrement => format!("{} -= 1", arg_code),
                }
            }
            Expr::Logical { left, op, right } => {
                let left_code = self.expr_to_rust(left);
                let right_code = self.expr_to_rust(right);
                match op {
                    LogicalOp::And => {
                        // For && with JSX in right side, we need conditional rendering
                        // a && <jsx> becomes if a { Some(html!(...)) } else { None }
                        format!("if {} {{ Some({}) }} else {{ None }}", left_code, right_code)
                    }
                    LogicalOp::Or => {
                        // For ||, use unwrap_or for nullish coalescing pattern
                        format!("({}.unwrap_or({}))", left_code, right_code)
                    }
                    LogicalOp::NullishCoalesce => {
                        format!("({}.unwrap_or({}))", left_code, right_code)
                    }
                }
            }
            Expr::Cond { test, consequent, alternate } => {
                let test_code = self.expr_to_rust(test);
                let cons_code = self.expr_to_rust(consequent);
                let alt_code = self.expr_to_rust(alternate);
                format!("if {} {{ {} }} else {{ {} }}", test_code, cons_code, alt_code)
            }
            Expr::Call { callee, args, .. } => {
                // Special-case: JSON.stringify(arg) → serde_json::to_string(&arg).unwrap()
                if let Expr::Member { object, property, .. } = callee.as_ref() {
                    if let Expr::Ident { name: obj_name } = object.as_ref() {
                        if obj_name == "JSON" {
                            if let Expr::Ident { name: prop_name } = property.as_ref() {
                                if prop_name == "stringify" && !args.is_empty() {
                                    let arg = self.expr_to_rust(&args[0]);
                                    return format!("serde_json::to_string(&{}).unwrap()", arg);
                                }
                            }
                        }
                        if obj_name == "Date" {
                            if let Expr::Ident { name: prop_name } = property.as_ref() {
                                if prop_name == "now" {
                                    return format!(
                                        "std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_millis() as f64"
                                    );
                                }
                            }
                        }
                        if obj_name == "Math" {
                            if let Expr::Ident { name: prop_name } = property.as_ref() {
                                match prop_name.as_str() {
                                    "random" => return "rand::random::<f64>()".to_string(),
                                    "floor" if !args.is_empty() => {
                                        let arg = self.expr_to_rust(&args[0]);
                                        return format!("({}).floor()", arg);
                                    }
                                    "ceil" if !args.is_empty() => {
                                        let arg = self.expr_to_rust(&args[0]);
                                        return format!("({}).ceil()", arg);
                                    }
                                    "round" if !args.is_empty() => {
                                        let arg = self.expr_to_rust(&args[0]);
                                        return format!("({}).round()", arg);
                                    }
                                    "abs" if !args.is_empty() => {
                                        let arg = self.expr_to_rust(&args[0]);
                                        return format!("({}).abs()", arg);
                                    }
                                    "max" if args.len() >= 2 => {
                                        let a = self.expr_to_rust(&args[0]);
                                        let b = self.expr_to_rust(&args[1]);
                                        return format!("if {} > {} {{ {} }} else {{ {} }}", a, b, a, b);
                                    }
                                    "min" if args.len() >= 2 => {
                                        let a = self.expr_to_rust(&args[0]);
                                        let b = self.expr_to_rust(&args[1]);
                                        return format!("if {} < {} {{ {} }} else {{ {} }}", a, b, a, b);
                                    }
                                    _ => {}
                                }
                            }
                        }
                        if obj_name == "console" {
                            if let Expr::Ident { name: prop_name } = property.as_ref() {
                                let level = match prop_name.as_str() {
                                    "log" => "info",
                                    "warn" => "warn",
                                    "error" => "error",
                                    "debug" => "debug",
                                    _ => "info",
                                };
                                let args_code: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                                return format!("tracing::{}!({})", level, args_code.join(", "));
                            }
                        }
                        if obj_name == "performance" {
                            if let Expr::Ident { name: prop_name } = property.as_ref() {
                                if prop_name == "now" {
                                    return format!(
                                        "std::time::Instant::now().elapsed().as_secs_f64() * 1000.0"
                                    );
                                }
                            }
                        }
                    }
                    // Array / string method translation
                    if let Expr::Ident { name: method_name } = property.as_ref() {
                        let obj_code = self.expr_to_rust(object);
                        match method_name.as_str() {
                            // Array methods
                            "map" if !args.is_empty() => {
                                let closure = self.expr_to_rust(&args[0]);
                                return format!("{}.iter().map({}).collect::<Vec<_>>()", obj_code, closure);
                            }
                            "filter" if !args.is_empty() => {
                                let closure = self.expr_to_rust(&args[0]);
                                return format!("{}.iter().filter({}).cloned().collect::<Vec<_>>()", obj_code, closure);
                            }
                            "find" if !args.is_empty() => {
                                let closure = self.expr_to_rust(&args[0]);
                                return format!("{}.iter().find({}).cloned()", obj_code, closure);
                            }
                            "reduce" if !args.is_empty() => {
                                let init = self.expr_to_rust(&args[0]);
                                if args.len() > 1 {
                                    let closure = self.expr_to_rust(&args[1]);
                                    return format!("{}.iter().fold({}, {})", obj_code, init, closure);
                                } else {
                                    return format!("{}.iter().fold(None, |acc, x| acc.or(Some(x.clone()))).unwrap_or_default()", obj_code);
                                }
                            }
                            "includes" if !args.is_empty() => {
                                let item = self.expr_to_rust(&args[0]);
                                return format!("{}.contains(&{})", obj_code, item);
                            }
                            "join" if !args.is_empty() => {
                                let sep = self.expr_to_rust(&args[0]);
                                return format!("{}.join(&{})", obj_code, sep);
                            }
                            "push" if !args.is_empty() => {
                                let item = self.expr_to_rust(&args[0]);
                                return format!("{{ let mut __tmp = {}; __tmp.push({}); __tmp }}", obj_code, item);
                            }
                            "sort" => {
                                if args.is_empty() {
                                    return format!("{{ let mut __tmp = {}; __tmp.sort(); __tmp }}", obj_code);
                                } else {
                                    let cmp = self.expr_to_rust(&args[0]);
                                    return format!("{{ let mut __tmp = {}; __tmp.sort_by({}); __tmp }}", obj_code, cmp);
                                }
                            }
                            "forEach" if !args.is_empty() => {
                                let closure = self.expr_to_rust(&args[0]);
                                return format!("{{ for item in {} {{ {}(item); }} }}", obj_code, closure);
                            }
                            // String methods
                            "split" if !args.is_empty() => {
                                let sep = self.expr_to_rust(&args[0]);
                                return format!("{}.split(&{}).collect::<Vec<_>>()", obj_code, sep);
                            }
                            "trim" => return format!("{}.trim()", obj_code),
                            "startsWith" if !args.is_empty() => {
                                let prefix = self.expr_to_rust(&args[0]);
                                return format!("{}.starts_with(&{})", obj_code, prefix);
                            }
                            "endsWith" if !args.is_empty() => {
                                let suffix = self.expr_to_rust(&args[0]);
                                return format!("{}.ends_with(&{})", obj_code, suffix);
                            }
                            "replace" if args.len() >= 2 => {
                                let from = self.expr_to_rust(&args[0]);
                                let to = self.expr_to_rust(&args[1]);
                                return format!("{}.replace(&{}, &{})", obj_code, from, to);
                            }
                            "toLowerCase" => return format!("{}.to_lowercase()", obj_code),
                            "toUpperCase" => return format!("{}.to_uppercase()", obj_code),
                            "slice" if !args.is_empty() => {
                                let start = self.expr_to_rust(&args[0]);
                                if args.len() > 1 {
                                    let end = self.expr_to_rust(&args[1]);
                                    return format!("{}[{}..{}]", obj_code, start, end);
                                } else {
                                    return format!("{}[{}..]", obj_code, start);
                                }
                            }
                            "substring" if !args.is_empty() => {
                                let start = self.expr_to_rust(&args[0]);
                                if args.len() > 1 {
                                    let end = self.expr_to_rust(&args[1]);
                                    return format!("{}[{}..{}]", obj_code, start, end);
                                } else {
                                    return format!("{}[{}..]", obj_code, start);
                                }
                            }
                            "indexOf" if !args.is_empty() => {
                                let item = self.expr_to_rust(&args[0]);
                                return format!("{}.iter().position(|x| x == &{}).unwrap_or(usize::MAX) as f64", obj_code, item);
                            }
                            _ => {}
                        }
                    }
                }
                let callee_code = self.expr_to_rust(callee);
                let args_code: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                format!("{}({})", callee_code, args_code.join(", "))
            }
            Expr::New { callee, args, .. } => {
                // Special-case: new Response(body, init) → Response::builder()...
                if let Expr::Ident { name } = callee.as_ref() {
                    if name == "Response" {
                        return self.generate_new_response(args);
                    }
                }
                let callee_code = self.expr_to_rust(callee);
                let args_code: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                format!("{}::new({})", callee_code, args_code.join(", "))
            }
            Expr::Await { arg } => format!("{}.await", self.expr_to_rust(arg)),
            Expr::Yield { arg, .. } => {
                if let Some(a) = arg {
                    format!("yield {}", self.expr_to_rust(a))
                } else {
                    "yield".to_string()
                }
            }
            Expr::Member { object, property, computed, .. } => {
                let obj_code = self.expr_to_rust(object);
                let prop_code = if *computed {
                    // Array/object index access: arr[0], obj[key]
                    self.expr_to_rust(property)
                } else {
                    if let Expr::Ident { name } = property.as_ref() {
                        // Transform JavaScript property names to Rust equivalents
                        let rust_name = match name.as_str() {
                            "length" => "len()".to_string(),
                            "name" => "name".to_string(),
                            "value" => "value".to_string(),
                            "innerHTML" => "inner_html".to_string(),
                            "className" => "class_name".to_string(),
                            "nodeName" => "node_name".to_string(),
                            "textContent" => "text_content".to_string(),
                            "innerText" => "inner_text".to_string(),
                            _ if name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) => {
                                // Method call like .push() -> .push()
                                name.clone()
                            }
                            _ => name.clone(),
                        };
                        rust_name
                    } else {
                        self.expr_to_rust(property)
                    }
                };
                if *computed {
                    format!("{}[{}]", obj_code, prop_code)
                } else {
                    format!("{}.{}", obj_code, prop_code)
                }
            }
            Expr::Object { props } => {
                let fields: Vec<String> = props.iter().map(|p| {
                    match p {
                        ObjectProp::Init { key, value } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(e) => self.expr_to_rust(e),
                            };
                            let v = self.expr_to_rust(value);
                            format!("{}: {}", self.to_snake_case(&k), v)
                        }
                        ObjectProp::Method { key, value: _ } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            format!("{}(_) {{}}", self.to_snake_case(&k))
                        }
                        ObjectProp::Shorthand { name } => self.to_snake_case(name),
                        ObjectProp::Spread { value } => format!("..{{{}}}", self.expr_to_rust(value)),
                        ObjectProp::Get { key, .. } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            format!("get {}() {{}}", self.to_snake_case(&k))
                        }
                        ObjectProp::Set { key, value, .. } => {
                            let k = match key {
                                PropKey::Ident(s) => s.clone(),
                                PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => n.to_string(),
                                PropKey::Computed(_) => "unknown".to_string(),
                            };
                            let t = value.params.first()
                                .and_then(|p| p.type_.as_ref())
                                .map(|t| self.type_to_rust(t))
                                .unwrap_or_else(|| "serde_json::Value".to_string());
                            format!("set {}(_: {}) {{}}", self.to_snake_case(&k), t)
                        }
                    }
                }).collect();
                format!("{{{}}}", fields.join(", "))
            }
            Expr::Array { elems } => {
                // Handle spread operator: [a, ...rest, b] 
                // If spread is present, we need to build the array differently
                let has_spread = elems.iter().any(|e| matches!(e, Some(Expr::Spread { .. })));
                
                if has_spread {
                    // For spread, we need to build the array dynamically
                    // [a, ...rest, b] -> {
                    //     let mut __arr = vec![a];
                    //     __arr.extend(rest.iter().cloned());
                    //     __arr.push(b);
                    //     __arr
                    // }
                    let mut push_calls: Vec<String> = Vec::new();
                    let mut iterators: Vec<String> = Vec::new();
                    
                    for elem in elems {
                        match elem {
                            Some(Expr::Spread { arg }) => {
                                let spread_code = self.expr_to_rust(arg);
                                iterators.push(format!("{}.iter().cloned()", spread_code));
                            }
                            Some(e) => {
                                let elem_code = self.expr_to_rust(e);
                                push_calls.push(format!("__arr.push({});", elem_code));
                            }
                            None => {
                                // Elision - skip
                            }
                        }
                    }
                    
                    // Build the result
                    let mut result = String::from("{ let mut __arr: Vec<_> = Vec::new(); ");
                    for iter in &iterators {
                        result.push_str(&format!("__arr.extend({}); ", iter));
                    }
                    for push in &push_calls {
                        result.push_str(push);
                        result.push(' ');
                    }
                    result.push_str("__arr }");
                    result
                } else {
                    // No spread - simple vec!
                    let elems_code: Vec<String> = elems.iter().filter_map(|e| {
                        e.as_ref().map(|e| self.expr_to_rust(e))
                    }).collect();
                    format!("vec![{}]", elems_code.join(", "))
                }
            }
            Expr::Arrow { params, body, .. } => {
                let params_code: Vec<String> = params.iter().map(|p| {
                    let name = self.to_snake_case(&p.name);
                    // Skip type annotations for closures - Rust will infer types
                    name
                }).collect();
                
                // Handle block body vs expression body
                let body_code = match body.as_ref() {
                    Stmt::Block(stmts) => {
                        // Handle multiple statements - strip trailing semicolons before joining
                        let mut lines: Vec<String> = Vec::new();
                        for stmt in stmts {
                            let stmt_code = self.stmt_to_rust(stmt).unwrap_or_default();
                            if !stmt_code.trim().is_empty() {
                                // Strip trailing semicolon and newline, then add it back properly
                                let trimmed = stmt_code.trim().trim_end_matches(';').trim_end().to_string();
                                if !trimmed.is_empty() {
                                    lines.push(trimmed);
                                }
                            }
                        }
                        if lines.is_empty() {
                            "{}".to_string()
                        } else {
                            format!("{{ {} }}", lines.join("; "))
                        }
                    }
                    Stmt::Return { arg } => {
                        if let Some(expr) = arg {
                            format!("{{ {} }}", self.expr_to_rust(expr))
                        } else {
                            "{}".to_string()
                        }
                    }
                    Stmt::Expr { expr } => {
                        // Single expression statement
                        format!("{{ {} }}", self.expr_to_rust(expr))
                    }
                    other => self.stmt_to_rust(other).unwrap_or_else(|_: anyhow::Error| "{}".to_string()),
                };
                
                format!("|{}| {}", params_code.join(", "), body_code)
            }
            Expr::Function { decl } => {
                let params: Vec<String> = decl.params.iter().map(|p| {
                    let name = self.to_snake_case(&p.name);
                    p.type_.as_ref()
                        .map(|t| format!("{}: {}", name, self.type_to_rust(t)))
                        .unwrap_or(name)
                }).collect();
                
                if let Some(body) = &decl.body {
                    let body_code = body.0.iter().map(|s| self.stmt_to_rust(s).unwrap_or_default()).collect::<Vec<_>>().join("\n");
                    format!("|{}| {{\n{}}}", params.join(", "), body_code)
                } else {
                    format!("|{}| {{}}", params.join(", "))
                }
            }
            Expr::Assign { left, right, .. } => {
                let left_code = if let Expr::Ident { name } = left.as_ref() {
                    self.to_snake_case(name)
                } else {
                    self.expr_to_rust(left)
                };
                let right_code = self.expr_to_rust(right);
                match (left.as_ref(), right.as_ref()) {
                    (Expr::Ident { .. }, _) => format!("{} = {}", left_code, right_code),
                    _ => format!("{} = {}", left_code, right_code),
                }
            }
            Expr::Seq { exprs } => {
                exprs.iter().map(|e| self.expr_to_rust(e)).collect::<Vec<_>>().join(", ")
            }
            Expr::Class { .. } => "()".to_string(),
            Expr::TaggedTemplate { tag, .. } => {
                format!("{}(...)", self.expr_to_rust(tag))
            }
            Expr::JSX(x) => self.jsx_to_rust(x),
            Expr::TSAs { expr, .. } => self.expr_to_rust(expr),
            Expr::Spread { arg } => format!("..{}", self.expr_to_rust(arg)),
            Expr::MetaProp { kind } => match kind {
                MetaPropKind::NewTarget => "__rt__.new_target",
                MetaPropKind::ImportMeta => "__rt__.import_meta",
            }.to_string(),
        }
    }

    /// Generate JSX element as Rust code (for top-level use)
    pub fn jsx_to_rust(&self, x: &JSXExpr) -> String {
        let inner = self.jsx_element_inner(x);
        format!("html!({})", inner)
    }
    
    /// Generate just the inner content of a JSX element (for use as children)
    fn jsx_element_inner(&self, x: &JSXExpr) -> String {
        let tag_name = match &x.opening.name {
            JSXName::Ident(s) => s.clone(),
            JSXName::Member { object, property } => format!("{}_{}", object, property),
            JSXName::Namespaced { ns, name } => format!("{}_{}", ns, name),
            JSXName::Dynamic(_) => "Dynamic".to_string(),
        };

        let attrs: Vec<String> = x.opening.attrs.iter().filter_map(|a| {
            match a {
                JSXAttr::Attr { name, value } => {
                    let rust_name = self.jsx_attr_to_rust(name);
                    let value_code = value.as_ref()
                        .map(|v| self.jsx_attr_value_to_rust(v))
                        .unwrap_or_else(|| "true".to_string());
                    // Check if value_code is a simple literal or needs braces
                    if value_code.starts_with('"') || value_code.starts_with("r#") {
                        Some(format!("{} = {}", rust_name, value_code))
                    } else if value_code.parse::<f64>().is_ok() {
                        Some(format!("{} = {}", rust_name, value_code))
                    } else if value_code == "true" || value_code == "false" {
                        Some(format!("{} = {}", rust_name, value_code))
                    } else {
                        Some(format!("{} = {{{}}}", rust_name, value_code))
                    }
                }
                JSXAttr::Spread { expr } => {
                    Some(format!("..{{{}}}", self.expr_to_rust(expr)))
                }
                JSXAttr::Event { name, handler } => {
                    let rust_name = self.jsx_attr_to_rust(name);
                    Some(format!("{} = {{{}}}", rust_name, self.expr_to_rust(handler)))
                }
                JSXAttr::Bool { name } => {
                    Some(format!("{} = true", self.jsx_attr_to_rust(name)))
                }
                JSXAttr::Expr { name, expr } => {
                    if let Some(n) = name {
                        let rust_name = self.jsx_attr_to_rust(n);
                        Some(format!("{} = {{{}}}", rust_name, self.expr_to_rust(expr)))
                    } else {
                        Some(format!("{{{}}}", self.expr_to_rust(expr)))
                    }
                }
            }
        }).collect();

        let children: Vec<String> = x.children.iter().map(|c| self.jsx_child_to_rust(c)).collect();

        let attrs_str = if attrs.is_empty() {
            String::new()
        } else {
            format!(" {}", attrs.join(" "))
        };

        let children_str = children.join(" ");
        
        // PascalCase tags are components, not HTML elements
        let rust_tag = if tag_name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
            // Component - use PascalCase
            tag_name.clone()
        } else {
            // HTML element - lowercase
            tag_name.to_lowercase()
        };
        
        if x.opening.self_closing {
            format!("<{}{}/>", rust_tag, attrs_str)
        } else {
            format!("<{}{}>{}</{}>", rust_tag, attrs_str, children_str, rust_tag)
        }
    }

    fn jsx_attr_value_to_rust(&self, v: &JSXAttrValue) -> String {
        match v {
            JSXAttrValue::String(s) => format!("{:?}", s),
            JSXAttrValue::Expr(e) => self.expr_to_rust(e),
        }
    }

    fn jsx_child_to_rust(&self, child: &JSXChild) -> String {
        match child {
            JSXChild::Text(s) => {
                // Text content should be quoted for html! macro
                if s.trim().is_empty() {
                    String::new()
                } else {
                    format!("{:?}", s)
                }
            }
            JSXChild::Expr(e) => {
                // Expressions need to be wrapped in {} for html!
                let expr_str = self.expr_to_rust(e);
                format!("{{{}}}", expr_str)
            }
            JSXChild::JSX(x) => {
                // Use inner content for children (no nested html!())
                self.jsx_element_inner(x)
            }
            JSXChild::Fragment { children } => {
                // Fragment children are concatenated directly
                let inner: Vec<String> = children.iter().map(|c| self.jsx_child_to_rust(c)).collect();
                inner.join(" ")
            }
            JSXChild::Spread { expr } => {
                // Spread in children
                format!("..{{{}}}", self.expr_to_rust(expr))
            }
        }
    }


    pub fn jsx_attr_to_rust(&self, name: &str) -> String {
        match name {
            "class" | "className" => "class_name".to_string(),
            "for" | "htmlFor" => "for_id".to_string(),
            "tabindex" => "tab_index".to_string(),
            _ if name.starts_with("on") && name.len() > 2 && name.chars().nth(2).map(|c| c.is_uppercase()).unwrap_or(false) => {
                // Event handlers like onClick -> on_click, onChange -> on_change
                let event_part = &name[2..];
                format!("on_{}", self.to_snake_case(event_part))
            }
            _ => {
                if name.contains('-') {
                    self.to_snake_case(name)
                } else {
                    name.to_string()
                }
            }
        }
    }

    pub fn to_snake_case(&self, s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_snake_case() {
        let cg = CodeGenerator::new();
        assert_eq!(cg.to_snake_case("useState"), "use_state");
        assert_eq!(cg.to_snake_case("onClick"), "on_click");
        assert_eq!(cg.to_snake_case("className"), "class_name");
    }
}
