//! Build script for Quench
//!
//! 1. Compiles JavaScript to QuickJS bytecode (placeholder).
//! 2. Lints Rust sources against project rules:
//!    - File length: max 500 lines
//!    - Function length: max 40 lines
//!    - Cyclomatic complexity: max 10
//!
//! **Enforcement:**
//! - Compiler module (src/compiler/): Panic on violations (fully compliant)
//! - Other modules: Warning only (pending refactoring)

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const MAX_FILE_LINES: usize = 500;
const MAX_FUNCTION_LINES: usize = 40;
const MAX_COMPLEXITY: usize = 10;

fn main() {
    generate_bytecode_bundle();
    run_linter();
}

fn generate_bytecode_bundle() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("bundle_qbc.rs");
    let bundle_path = env::var("QUENCH_BUNDLE")
        .unwrap_or_else(|_| "dist/bundle.js".to_string());

    println!("cargo::rustc-check-cfg=cfg(has_bytecode_bundle)");
    println!("cargo:rerun-if-changed=build.rs");

    if !Path::new(&bundle_path).exists() {
        let declaration = r#"// No bundle - using runtime.js only
pub static BUNDLE_BYTECODE: &[u8] = &[];

pub fn get_bundle_size() -> usize { 0 }
"#;
        fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
        return;
    }

    println!("cargo:rerun-if-changed={}", bundle_path);
    let bundle = fs::read_to_string(&bundle_path).expect("Failed to read bundle");
    let bytecode = bundle.as_bytes().to_vec();
    let len = bytecode.len();
    let declaration = format!(
        r#"// Auto-generated by build.rs
use std::include_bytes;

pub static BUNDLE_BYTECODE: &[u8] = include_bytes!("../{bundle_path}");

pub fn get_bundle_size() -> usize {{ {len} }}
"#,
        bundle_path = bundle_path.replace('\\', "/")
    );
    fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
}

fn run_linter() {
    if let Err(e) = lint_rust_sources(Path::new("src")) {
        for line in e.lines() {
            println!("cargo:warning={}", line);
        }
    }
}

// ===================================================================
// Linter
// ===================================================================

#[derive(Debug)]
struct Violation {
    file: PathBuf,
    line: usize,
    kind: String,
    message: String,
}

fn lint_rust_sources(src_dir: &Path) -> Result<(), String> {
    let mut violations = Vec::new();
    let mut strict_violations = Vec::new();
    let files = collect_rs_files(src_dir)?;

    for path in files {
        let content = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        let lines: Vec<&str> = content.lines().collect();
        
        // Check if this is a compiler module (strict enforcement)
        let is_compiler = path.components().any(|c| c.as_os_str() == "compiler");
        let target_vec = if is_compiler { &mut strict_violations } else { &mut violations };
        
        check_file_length(&path, &lines, target_vec);
        check_functions(&path, &lines, target_vec);
    }

    // Compiler module violations are fatal
    if !strict_violations.is_empty() {
        panic!("Compiler module lint violations:\n{}", format_violations(&strict_violations));
    }

    if violations.is_empty() {
        Ok(())
    } else {
        Err(format_violations(&violations))
    }
}

fn collect_rs_files(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_rs_files_rec(dir, &mut files)?;
    Ok(files)
}

fn collect_rs_files_rec(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries: Vec<_> = fs::read_dir(dir).map_err(|e| e.to_string())?.collect();
    // Sort alphabetically for deterministic line numbers
    entries.sort_by(|a, b| {
        let name_a = a.as_ref().unwrap().file_name();
        let name_b = b.as_ref().unwrap().file_name();
        name_a.cmp(&name_b)
    });
    for entry in entries {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        if path.is_dir() {
            collect_rs_files_rec(&path, files)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            files.push(path);
        }
    }
    Ok(())
}

fn check_file_length(path: &Path, lines: &[&str], violations: &mut Vec<Violation>) {
    if lines.len() > MAX_FILE_LINES {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: lines.len(),
            kind: "file-length".to_string(),
            message: format!("file has {} lines (max {})", lines.len(), MAX_FILE_LINES),
        });
    }
}

fn format_violations(violations: &[Violation]) -> String {
    let mut msg = String::from("Lint violations found:\n");
    for v in violations {
        msg.push_str(&format!(
            "  [{}] {}:{} - {}\n",
            v.kind,
            v.file.display(),
            v.line,
            v.message
        ));
    }
    msg
}

// ===================================================================
// Function scanning
// ===================================================================

fn check_functions(path: &Path, lines: &[&str], violations: &mut Vec<Violation>) {
    let mut i = 0;
    while i < lines.len() {
        if !is_function_start(lines[i]) {
            i += 1;
            continue;
        }
        let Some((open_line, open_col)) = find_open_brace(lines, i) else {
            i += 1;
            continue;
        };
        let Some(close_line) = find_close_brace(lines, open_line, open_col) else {
            i = open_line + 1;
            continue;
        };

        let body_start = open_line + 1;
        let body_end = close_line;
        if body_end > body_start {
            let body = &lines[body_start..body_end];
            check_function_length(path, i + 1, body, violations);
            check_function_complexity(path, i + 1, body, violations);
        }
        i = close_line + 1;
    }
}

fn is_function_start(line: &str) -> bool {
    let t = line.trim_start();
    t.starts_with("fn ")
        || prefix_then_fn(t, "pub ")
        || prefix_then_fn(t, "unsafe ")
        || prefix_then_fn(t, "async ")
        || prefix_then_fn(t, "const ")
}

fn prefix_then_fn(trimmed: &str, prefix: &str) -> bool {
    trimmed.starts_with(prefix)
        && trimmed[prefix.len()..].trim_start().starts_with("fn ")
}

fn find_open_brace(lines: &[&str], start: usize) -> Option<(usize, usize)> {
    if let Some(c) = lines[start].find('{') {
        return Some((start, c));
    }
    for (j, line) in lines.iter().enumerate().skip(start + 1) {
        if let Some(c) = line.find('{') {
            return Some((j, c));
        }
    }
    None
}

fn find_close_brace(lines: &[&str], open_line: usize, open_col: usize) -> Option<usize> {
    let mut depth: isize = 1;
    for (j, line) in lines.iter().enumerate().skip(open_line) {
        let start = if j == open_line { open_col + 1 } else { 0 };
        let mut in_string = false;
        let mut string_delim = '\0';
        let mut prev_char = '\0';
        let mut raw_string_hashes: usize = 0; // >0 when inside r#"..."#
        
        for (idx, ch) in line.chars().enumerate() {
            if idx < start {
                // Detect raw-string start before `start` so we know if we're inside one
                if let Some(rest) = line.get(idx..) {
                    if raw_string_hashes == 0 && !in_string {
                        if let Some(h) = raw_string_prefix_len(rest) {
                            raw_string_hashes = h;
                        }
                    }
                }
                continue;
            }
            
            // Raw string literals: r#"..."#
            if raw_string_hashes > 0 {
                if prev_char != '\\' && ch == '"' {
                    // Check if followed by exactly raw_string_hashes '#' characters
                    let trailing = line.chars().skip(idx + 1);
                    let hash_count = trailing.take(raw_string_hashes).take_while(|c| *c == '#').count();
                    if hash_count == raw_string_hashes {
                        raw_string_hashes = 0;
                    }
                }
                prev_char = ch;
                continue;
            }
            
            // Handle string delimiters
            if !in_string && (ch == '"' || ch == '\'') {
                in_string = true;
                string_delim = ch;
            } else if in_string && ch == string_delim && prev_char != '\\' {
                in_string = false;
                string_delim = '\0';
            }
            
            // Skip braces inside strings
            if in_string {
                prev_char = ch;
                continue;
            }
            
            // Detect raw string start
            if let Some(rest) = line.get(idx..) {
                if let Some(h) = raw_string_prefix_len(rest) {
                    raw_string_hashes = h;
                    prev_char = ch;
                    continue;
                }
            }
            
            // Handle escape sequences
            if prev_char == '\\' {
                prev_char = '\0'; // Next char is escaped, don't process
                continue;
            }
            
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(j);
                    }
                }
                _ => {}
            }
            prev_char = ch;
        }
    }
    None
}

/// If `s` starts with a raw string prefix `r#*"`, return the number of `#` characters.
fn raw_string_prefix_len(s: &str) -> Option<usize> {
    let bytes = s.as_bytes();
    if bytes.is_empty() || bytes[0] != b'r' {
        return None;
    }
    let mut i = 1;
    while i < bytes.len() && bytes[i] == b'#' {
        i += 1;
    }
    if i < bytes.len() && bytes[i] == b'"' && i >= 1 {
        Some(i - 1)
    } else {
        None
    }
}

fn check_function_length(
    path: &Path,
    decl_line: usize,
    body: &[&str],
    violations: &mut Vec<Violation>,
) {
    if body.len() > MAX_FUNCTION_LINES {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: decl_line,
            kind: "function-length".to_string(),
            message: format!("function body has {} lines (max {})", body.len(), MAX_FUNCTION_LINES),
        });
    }
}

fn check_function_complexity(
    path: &Path,
    decl_line: usize,
    body: &[&str],
    violations: &mut Vec<Violation>,
) {
    let complexity = check_cyclomatic(body);
    if complexity > MAX_COMPLEXITY {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: decl_line,
            kind: "complexity".to_string(),
            message: format!("function complexity is {} (max {})", complexity, MAX_COMPLEXITY),
        });
    }
}

fn strip_comment(line: &str) -> &str {
    if line.starts_with("//") || line.starts_with("/*") || line.starts_with("*") {
        return "";
    }
    match line.find("//") {
        Some(idx) => &line[..idx],
        None => line,
    }
}

fn count_decisions(code: &str) -> usize {
    let mut n = 0;
    for kw in [" if ", " match ", " while ", " for ", " loop ", " else if "] {
        n += code.matches(kw).count();
    }
    if code.starts_with("if ")
        || code.starts_with("match ")
        || code.starts_with("while ")
        || code.starts_with("for ")
        || code.starts_with("loop ")
    {
        n += 1;
    }
    n += code.matches(" && ").count();
    n += code.matches(" || ").count();
    n + code.matches('?').count()
}

#[allow(clippy::needless_borrow)]
fn check_cyclomatic(body: &[&str]) -> usize {
    let mut score = 1;
    for line in body {
        let code = strip_comment(line.trim());
        if code.is_empty() {
            continue;
        }
        score += count_decisions(code);
    }
    score
}
