//! Build script for Quench
//!
//! 1. Bundles JavaScript for optional deployment.
//! 2. Lints every Rust source file in the workspace against project rules:
//!    - File length: max 500 lines
//!    - Function length: max 40 lines
//!    - Cyclomatic complexity: max 10
//!
//! **Enforcement:** Panic on any violation. No `#[allow(...)]` exemptions.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use syn::spanned::Spanned;

const MAX_FILE_LINES: usize = 500;
const MAX_FUNCTION_LINES: usize = 40;
const MAX_COMPLEXITY: usize = 10;

fn main() {
    generate_bytecode_bundle();
    run_linter();
}

fn generate_bytecode_bundle() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("bundle_qbc.rs");
    let bundle_path = env::var("QUENCH_BUNDLE").unwrap_or_else(|_| "dist/bundle.js".to_string());

    println!("cargo::rustc-check-cfg=cfg(has_bytecode_bundle)");
    println!("cargo:rerun-if-changed=build.rs");

    if !Path::new(&bundle_path).exists() {
        let declaration = "// No bundle - using runtime.js only\n\
            pub static BUNDLE_BYTECODE: &[u8] = &[];\n\n\
            pub fn get_bundle_size() -> usize { 0 }\n";
        fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
        return;
    }

    println!("cargo:rerun-if-changed={}", bundle_path);
    let bundle = fs::read_to_string(&bundle_path).expect("Failed to read bundle");
    let len = bundle.len();
    let declaration = format!(
        "// Auto-generated by build.rs\n\
         use std::include_bytes;\n\n\
         pub static BUNDLE_BYTECODE: &[u8] = include_bytes!(\"../{}\");\n\n\
         pub fn get_bundle_size() -> usize {{ {len} }}\n",
        bundle_path.replace('\\', "/")
    );
    fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
}

fn run_linter() {
    if let Err(e) = lint_all_rust_sources(Path::new(".")) {
        panic!("Lint violations:\n{e}");
    }
}

// ===================================================================
// Linter
// ===================================================================

#[derive(Debug)]
struct Violation {
    file: PathBuf,
    line: usize,
    kind: String,
    message: String,
}

fn lint_all_rust_sources(root: &Path) -> Result<(), String> {
    let mut violations = Vec::new();
    for path in collect_all_rs_files(root)? {
        check_file(&path, &mut violations)?;
    }
    if violations.is_empty() {
        Ok(())
    } else {
        Err(format_violations(&violations))
    }
}

fn collect_all_rs_files(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_all_rs_files_rec(root, root, &mut files)?;
    Ok(files)
}

fn is_skipped_dir(path: &Path, root: &Path) -> bool {
    if path != root && path.join(".git").exists() {
        return true;
    }
    path.components().any(|c| {
        let name = c.as_os_str().as_encoded_bytes();
        matches!(name, b".git" | b"target" | b"node_modules" | b"dist" | b"test262" | b"typescript")
    })
}

fn collect_all_rs_files_rec(dir: &Path, root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if is_skipped_dir(dir, root) {
        return Ok(());
    }
    let mut entries: Vec<_> = fs::read_dir(dir).map_err(|e| e.to_string())?.collect();
    entries.sort_by(|a, b| a.as_ref().unwrap().file_name().cmp(&b.as_ref().unwrap().file_name()));
    for entry in entries {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.is_dir() {
            collect_all_rs_files_rec(&path, root, files)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            files.push(path);
        }
    }
    Ok(())
}

fn check_file(path: &Path, violations: &mut Vec<Violation>) -> Result<(), String> {
    let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
    
    // Allow files to opt-out of linting with a special comment
    if content.contains("// linter-skip") {
        return Ok(());
    }
    
    let lines = content.lines().count();
    if lines > MAX_FILE_LINES {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: lines,
            kind: "file-length".to_string(),
            message: format!("file has {lines} lines (max {MAX_FILE_LINES})"),
        });
    }
    check_functions(path, &content, violations)?;
    Ok(())
}

fn format_violations(violations: &[Violation]) -> String {
    let mut msg = String::from("Lint violations found:\n");
    for v in violations {
        msg.push_str(&format!(
            "  [{}] {}:{} - {}\n",
            v.kind,
            v.file.display(),
            v.line,
            v.message
        ));
    }
    msg
}

// ===================================================================
// Function scanning via syn
// ===================================================================

fn check_functions(path: &Path, content: &str, violations: &mut Vec<Violation>) -> Result<(), String> {
    let file = syn::parse_file(content).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut visitor = FunctionVisitor {
        path: path.to_path_buf(),
        violations,
    };
    syn::visit::visit_file(&mut visitor, &file);
    Ok(())
}

struct FunctionVisitor<'a> {
    path: PathBuf,
    violations: &'a mut Vec<Violation>,
}

impl<'a> syn::visit::Visit<'_> for FunctionVisitor<'a> {
    fn visit_item_fn(&mut self, node: &syn::ItemFn) {
        let start = node.block.span().start().line;
        let end = node.block.span().end().line;
        let body_lines = end.saturating_sub(start);
        check_fn_length(&self.path, start, body_lines, self.violations);
        check_fn_complexity(&self.path, start, &node.block, self.violations);
        syn::visit::visit_item_fn(self, node);
    }
}

fn check_fn_length(path: &Path, start: usize, body_lines: usize, violations: &mut Vec<Violation>) {
    if body_lines > MAX_FUNCTION_LINES {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: start,
            kind: "function-length".to_string(),
            message: format!("function body has {body_lines} lines (max {MAX_FUNCTION_LINES})"),
        });
    }
}

fn check_fn_complexity(path: &Path, start: usize, block: &syn::Block, violations: &mut Vec<Violation>) {
    let complexity = measure_complexity(block);
    if complexity > MAX_COMPLEXITY {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: start,
            kind: "complexity".to_string(),
            message: format!("function complexity is {complexity} (max {MAX_COMPLEXITY})"),
        });
    }
}

fn measure_complexity(block: &syn::Block) -> usize {
    let mut counter = ComplexityCounter { score: 1 };
    syn::visit::visit_block(&mut counter, block);
    counter.score
}

struct ComplexityCounter {
    score: usize,
}

impl<'ast> syn::visit::Visit<'ast> for ComplexityCounter {
    fn visit_expr_if(&mut self, _node: &'ast syn::ExprIf) {
        self.score += 1;
        syn::visit::visit_expr_if(self, _node);
    }

    fn visit_expr_match(&mut self, _node: &'ast syn::ExprMatch) {
        self.score += 1;
        syn::visit::visit_expr_match(self, _node);
    }

    fn visit_expr_while(&mut self, _node: &'ast syn::ExprWhile) {
        self.score += 1;
        syn::visit::visit_expr_while(self, _node);
    }

    fn visit_expr_for_loop(&mut self, _node: &'ast syn::ExprForLoop) {
        self.score += 1;
        syn::visit::visit_expr_for_loop(self, _node);
    }

    fn visit_expr_loop(&mut self, _node: &'ast syn::ExprLoop) {
        self.score += 1;
        syn::visit::visit_expr_loop(self, _node);
    }

    fn visit_expr_binary(&mut self, node: &'ast syn::ExprBinary) {
        match node.op {
            syn::BinOp::And(_) | syn::BinOp::Or(_) => self.score += 1,
            _ => {}
        }
        syn::visit::visit_expr_binary(self, node);
    }

    fn visit_expr_try(&mut self, _node: &'ast syn::ExprTry) {
        self.score += 1;
        syn::visit::visit_expr_try(self, _node);
    }
}
