//! Build script for Quench
//!
//! 1. Bundles JavaScript for optional deployment.
//! 2. Lints every Rust source file in the workspace against project rules:
//!    - File length: max 500 lines
//!
//! **Enforcement:** Panic on file-length violations. Function-length and
//! complexity checks are deferred per docs/deferred-linting-rules.md.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

// =============================================================================
// Lint limit: max 500 lines/file
// Function-length and complexity checks are deferred.
// =============================================================================

const MAX_FILE_LINES: usize = 500;

fn main() {
    generate_bytecode_bundle();
    run_linter();
}

fn generate_bytecode_bundle() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("bundle_qbc.rs");
    let bundle_path = env::var("QUENCH_BUNDLE").unwrap_or_else(|_| "dist/bundle.js".to_string());

    println!("cargo::rustc-check-cfg=cfg(has_bytecode_bundle)");
    println!("cargo:rerun-if-changed=build.rs");

    if !Path::new(&bundle_path).exists() {
        let declaration = "// No bundle - using runtime.js only\n\
            pub static BUNDLE_BYTECODE: &[u8] = &[];\n\n\
            pub fn get_bundle_size() -> usize { 0 }\n";
        fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
        return;
    }

    println!("cargo:rerun-if-changed={}", bundle_path);
    let bundle = fs::read_to_string(&bundle_path).expect("Failed to read bundle");
    let len = bundle.len();
    let declaration = format!(
        "// Auto-generated by build.rs\n\
         use std::include_bytes;\n\n\
         pub static BUNDLE_BYTECODE: &[u8] = include_bytes!(\"../{}\");\n\n\
         pub fn get_bundle_size() -> usize {{ {len} }}\n",
        bundle_path.replace('\\', "/")
    );
    fs::write(&dest_path, declaration).expect("Failed to write bundle_qbc.rs");
}

fn run_linter() {
    if let Err(e) = lint_all_rust_sources(Path::new(".")) {
        panic!("Lint violations:\n{e}");
    }
}

// =============================================================================
// Linter
// =============================================================================

#[derive(Debug)]
struct Violation {
    file: PathBuf,
    line: usize,
    kind: String,
    message: String,
}

fn lint_all_rust_sources(root: &Path) -> Result<(), String> {
    let mut violations = Vec::new();
    for path in collect_all_rs_files(root)? {
        check_file(&path, &mut violations)?;
    }
    if violations.is_empty() {
        Ok(())
    } else {
        Err(format_violations(&violations))
    }
}

fn collect_all_rs_files(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_all_rs_files_rec(root, root, &mut files)?;
    Ok(files)
}

fn is_skipped_dir(path: &Path, root: &Path) -> bool {
    if path != root && path.join(".git").exists() {
        return true;
    }
    is_out_of_scope(path)
}

fn is_out_of_scope(path: &Path) -> bool {
    let path_str = path.to_string_lossy();

    if is_under_src(&path_str) {
        return true;
    }
    if is_under_examples(&path_str) || is_under_xtask(&path_str) || is_under_tests(&path_str) {
        return true;
    }
    path.components().any(|c| {
        let name = c.as_os_str().as_encoded_bytes();
        matches!(name, b".git" | b"target" | b"node_modules" | b"dist")
    })
}

fn is_under_src(path_str: &str) -> bool {
    (path_str.contains("/src/") || path_str.ends_with("/src"))
        && !path_str.contains("crates/quench-runtime/src")
}

fn is_under_examples(path_str: &str) -> bool {
    path_str.contains("/examples/") || path_str.ends_with("/examples")
}

fn is_under_xtask(path_str: &str) -> bool {
    path_str.contains("/xtask/") || path_str.ends_with("/xtask")
}

fn is_under_tests(path_str: &str) -> bool {
    if path_str.contains("/tests_runner") || path_str.ends_with("/tests_runner") {
        return true;
    }
    if path_str.contains("/tests/test262") || path_str.contains("/tests/typescript") {
        return true;
    }
    if path_str.contains("crates/quench-runtime/tests") {
        return true;
    }
    if path_str.starts_with("./tests/") || path_str.starts_with("tests/") {
        return true;
    }
    false
}

fn collect_all_rs_files_rec(dir: &Path, root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if is_skipped_dir(dir, root) {
        return Ok(());
    }
    let mut entries: Vec<_> = fs::read_dir(dir).map_err(|e| e.to_string())?.collect();
    entries.sort_by_key(|a| a.as_ref().unwrap().file_name());
    for entry in entries {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.is_dir() {
            collect_all_rs_files_rec(&path, root, files)?;
        } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            files.push(path);
        }
    }
    Ok(())
}

fn check_file(path: &Path, violations: &mut Vec<Violation>) -> Result<(), String> {
    let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
    let lines = content.lines().count();

    if lines > MAX_FILE_LINES {
        violations.push(Violation {
            file: path.to_path_buf(),
            line: lines,
            kind: "file-length".to_string(),
            message: format!("file has {lines} lines (max {MAX_FILE_LINES})"),
        });
    }
    Ok(())
}

fn format_violations(violations: &[Violation]) -> String {
    let mut msg = String::from("Lint violations found:\n");
    for v in violations {
        msg.push_str(&format!(
            "  [{}] {}:{} - {}\n",
            v.kind,
            v.file.display(),
            v.line,
            v.message
        ));
    }
    msg
}
