use super::*;

impl<H: Host> Vm<H> {
    pub fn new(host: H) -> Self {
        Self {
            host,
            specialized: true,
            heap: Heap::new(),
            globals: Value::NULL,
            object_proto: Value::NULL,
            function_proto: Value::NULL,
            array_proto: Value::NULL,
            array_buffer_proto: Value::NULL,
            uint8_array_proto: Value::NULL,
            uint8_clamped_array_proto: Value::NULL,
            uint16_array_proto: Value::NULL,
            uint32_array_proto: Value::NULL,
            int8_array_proto: Value::NULL,
            int16_array_proto: Value::NULL,
            int32_array_proto: Value::NULL,
            float32_array_proto: Value::NULL,
            float64_array_proto: Value::NULL,
            data_view_proto: Value::NULL,
            map_proto: Value::NULL,
            set_proto: Value::NULL,
            weak_map_proto: Value::NULL,
            weak_set_proto: Value::NULL,
            weak_ref_proto: Value::NULL,
            finalization_registry_proto: Value::NULL,
            iterator_proto: Value::NULL,
            regexp_proto: Value::NULL,
            constants: vec![],
            const_arrays: vec![],
            natives: vec![],
            frames: vec![],
            frame_pool: vec![],
            jobs: vec![],
            suspended: vec![],
            #[cfg(feature = "profile-aggregate")]
            profile: Profile::default(),
            #[cfg(not(feature = "profile-aggregate"))]
            profile: Profile,
            numeric_sites: FxHashMap::default(),
            shapes: vec![vec![]],
            shape_slots: vec![FxHashMap::default()],
            transitions: FxHashMap::default(),
            atom_text: AtomTable::default(),
            atoms: FxHashMap::default(),
            atom_collisions: FxHashMap::default(),
            dynamic_atoms: vec![],
            dynamic_strings: None,
            symbol_registry: FxHashMap::default(),
            well_known_symbols: FxHashMap::default(),
            string_concats: None,
            field_caches: vec![],
            megamorphic_field_indices: vec![],
            megamorphic_fields: vec![],
            length_atom: u32::MAX,
            size_atom: u32::MAX,
            to_fixed_atom: u32::MAX,
            to_precision_atom: u32::MAX,
            primitive_atoms: [u32::MAX; 8],
            method_caches: vec![],
            megamorphic_methods: vec![],
            #[cfg(feature = "profile-aggregate")]
            invalidated_methods: FxHashMap::default(),
            object_shapes: vec![],
            descriptors: FxHashMap::default(),
            symbol_properties: FxHashMap::default(),
            symbol_property_order: FxHashMap::default(),
            symbol_descriptors: FxHashMap::default(),
            random_state: 0x4d59_5df4_d0f3_3173,
        }
    }
}
