//! Module generation

use crate::transpile::codegen::CodeGenerator;
use crate::transpile::hir::*;
use anyhow::Result;

pub struct ModuleGen;

impl ModuleGen {
    pub fn generate_module(_cg: &mut CodeGenerator, _module: &Module) -> Result<String> {
        Ok("// Generated by runts\n".to_string())
    }
}
