//! Module generation

use anyhow::Result;
use crate::transpile::codegen::CodeGenerator;
use crate::transpile::hir::*;
use crate::transpile::codegen::function::FnGen;

pub struct ModuleGen;

impl ModuleGen {
    pub fn generate_module(cg: &mut CodeGenerator, module: &Module) -> Result<String> {
        let mut output = Self::header(module); Self::add_imports(cg, module, &mut output); cg.type_defs.clear(); Self::collect_type_defs(cg, module);
        for item in &module.items { if let ModuleItem::Decl(Decl::Type(t)) = item { let type_code = cg.generate_type_decl(t)?; if !type_code.trim().is_empty() { output.push_str(&type_code); output.push('\n'); } } }
        let mut default_component_name = None;
        for item in &module.items {
            if let ModuleItem::Decl(decl) = item { if !matches!(decl, Decl::Type(_)) { let decl_code = cg.generate_decl(decl)?; if !decl_code.trim().is_empty() { output.push_str(&decl_code); output.push_str("\n\n"); } } }
            if let ModuleItem::Export(Export::Default { expr }) = item { if let Expr::Function { decl } = expr { default_component_name = Some(decl.name.clone()); let fn_code = FnGen::generate_function(cg, decl, true)?; if !fn_code.trim().is_empty() { output.push_str(&fn_code); output.push_str("\n\n"); } } }
        }
        Ok(output)
    }

    fn header(_module: &Module) -> String { "// Generated by runts\n\n".to_string() }

    fn add_imports(cg: &mut CodeGenerator, module: &Module, output: &mut String) { for imp in module.items.iter().filter_map(|i| if let ModuleItem::Import(imp) = i { Some(imp) } else { None }) { output.push_str(&format!("use {};\n", imp.source)); } for imp in &cg.imports { output.push_str(&format!("{}\n", imp)); } output.push('\n'); }

    fn collect_type_defs(_cg: &mut CodeGenerator, _module: &Module) { }
}
