const assert = require('node:assert');
const quic = require('node:quic');
const receiver = quic.createSocket('udp4');
receiver.bind(0, '127.0.0.1');
const address = receiver.address();
assert.ok(address && typeof address.port === 'number' && address.port > 0);
const sender = quic.createSocket('udp4');
sender.bind(0, '127.0.0.1');
sender.send('quic-loopback', address.port, '127.0.0.1');
sender.close();
receiver.close();
console.log('quic loopback ok');
