const assert = require('assert');
const sqlite = require('node:sqlite');
const db = new sqlite.DatabaseSync(':memory:');
db.exec('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)');
const insert = db.prepare('INSERT INTO users(name) VALUES (?)');
insert.run('Ada');
const query = db.prepare('SELECT id, name FROM users WHERE id = ?');
const rows = query.all(1);
assert.strictEqual(rows.length, 1);
assert.strictEqual(rows[0].name, 'Ada');
db.close();
console.log('sqlite: ok');