globalThis.__quench_bootstrap_fragments.push(
  'const __quenchUnlinkRequire = globalThis.require;\nconst __quenchUnlinkFs = __quenchUnlinkRequire("fs");\nconst __quenchUnlinkPath = (value) => typeof value === "string" || value instanceof Uint8Array || value instanceof globalThis.__nodeURL;\nconst __quenchUnlinkError = () => { const error = new TypeError("The \\\"path\\\" argument must be of type string or an instance of Buffer or URL"); error.code = "ERR_INVALID_ARG_TYPE"; return error; };\nconst __quenchUnlinkSync = __quenchUnlinkFs.unlinkSync;\n__quenchUnlinkFs.unlinkSync = (value) => { if (!__quenchUnlinkPath(value)) throw __quenchUnlinkError(); return __quenchUnlinkSync(value); };\nconst __quenchUnlink = __quenchUnlinkFs.unlink;\n__quenchUnlinkFs.unlink = (value, callback) => { if (!__quenchUnlinkPath(value)) throw __quenchUnlinkError(); return __quenchUnlink(value, callback); };\n'
);
globalThis.__quench_bootstrap_fragments.push(
  'const __quenchUnlinkAsyncFs = globalThis.require("fs");\n__quenchUnlinkAsyncFs.unlink = (value, callback) => { if (typeof callback !== "function") throw new TypeError("The \\\"callback\\\" argument must be of type function"); if (!__quenchUnlinkPath(value)) throw __quenchUnlinkError(); queueMicrotask(() => { try { __quenchUnlinkAsyncFs.unlinkSync(value); callback(null); } catch (error) { callback(error); } }); };\n__quenchUnlinkAsyncFs.promises.unlink = (value) => new Promise((resolve, reject) => __quenchUnlinkAsyncFs.unlink(value, (error) => error ? reject(error) : resolve()));\n'
);
globalThis.__quench_bootstrap_fragments.push(
  'const __quenchUnlinkPromiseFs = globalThis.require("fs");\n__quenchUnlinkPromiseFs.promises.unlink = (value) => new Promise((resolve, reject) => __quenchUnlinkPromiseFs.unlink(value, (error) => error ? reject(error) : resolve()));\n'
);
