const assert = require("node:assert");
const { Assert } = require("node:assert");
const instance = new Assert({ diff: "full" });
assert.strictEqual(instance.diff, "full");
assert.strictEqual(new Assert().strict, true);
const strict = new Assert();
assert.strictEqual(strict.equal, strict.strictEqual);
assert.strictEqual(strict.deepEqual, strict.deepStrictEqual);
assert.strictEqual(strict.notEqual, strict.notStrictEqual);
assert.strictEqual(strict.notDeepEqual, strict.notDeepStrictEqual);
strict.equal(strict.equal, strict.strictEqual);
strict.equal(strict.deepEqual, strict.deepStrictEqual);
strict.equal(strict.notEqual, strict.notStrictEqual);
strict.equal(strict.notDeepEqual, strict.notDeepStrictEqual);
console.log("assert options passed");
