use super::*;

impl<H: Host> Vm<H> {
    pub(crate) fn new(host: H) -> Self {
        Self {
            host,
            specialized: true,
            heap: Heap::new(),
            realm: Realm {
                globals: Value::NULL,
                global_lexical_declarations: FxHashSet::default(),
                global_lexical_bindings: FxHashMap::default(),
                immutable_global_lexical_bindings: FxHashSet::default(),
                global_lexical_states: FxHashMap::default(),
                intrinsics: RealmIntrinsics::default(),
                jobs: vec![],
                template_objects: FxHashMap::default(),
                promise: Default::default(),
            },
            object_proto: Value::NULL,
            function_proto: Value::NULL,
            array_proto: Value::NULL,
            string_proto: Value::NULL,
            array_buffer_proto: Value::NULL,
            shared_array_buffer_proto: Value::NULL,
            array_iterator_proto: Value::NULL,
            typed_array_proto: Value::NULL,
            uint8_array_proto: Value::NULL,
            uint8_clamped_array_proto: Value::NULL,
            uint16_array_proto: Value::NULL,
            uint32_array_proto: Value::NULL,
            int8_array_proto: Value::NULL,
            int16_array_proto: Value::NULL,
            int32_array_proto: Value::NULL,
            bigint64_array_proto: Value::NULL,
            biguint64_array_proto: Value::NULL,
            float16_array_proto: Value::NULL,
            float32_array_proto: Value::NULL,
            float64_array_proto: Value::NULL,
            data_view_proto: Value::NULL,
            map_proto: Value::NULL,
            set_proto: Value::NULL,
            shadow_realm_proto: Value::NULL,
            map_iterator_proto: Value::NULL,
            set_iterator_proto: Value::NULL,
            weak_map_proto: Value::NULL,
            weak_set_proto: Value::NULL,
            weak_ref_proto: Value::NULL,
            finalization_registry_proto: Value::NULL,
            iterator_proto: Value::NULL,
            string_iterator_proto: Value::NULL,
            regexp_string_iterator_proto: Value::NULL,
            generator_proto: Value::NULL,
            iterator_helper_proto: Value::NULL,
            wrap_for_valid_iterator_proto: Value::NULL,
            async_iterator_proto: Value::NULL,
            async_generator_proto: Value::NULL,
            async_from_sync_iterator_proto: Value::NULL,
            regexp_proto: Value::NULL,
            temporal_plain_date_proto: Value::NULL,
            temporal_plain_time_proto: Value::NULL,
            temporal_plain_month_day_proto: Value::NULL,
            temporal_plain_year_month_proto: Value::NULL,
            natives: vec![],
            frames: vec![],
            frame_pool: vec![],
            active_call_roots: vec![],
            with_stack: vec![],
            suspended: vec![],
            suspended_free: vec![],
            test262_agent: Default::default(),
            programs: ProgramStore::default(),
            program_cache_layouts: Vec::new(),
            active_program: ProgramId::MAIN,
            #[cfg(feature = "profile-aggregate")]
            profile: Profile::default(),
            #[cfg(not(feature = "profile-aggregate"))]
            profile: Profile,
            shapes: vec![Shape::root()],
            transitions: FxHashMap::default(),
            atom_text: AtomTable::default(),
            atoms: FxHashMap::default(),
            atom_collisions: FxHashMap::default(),
            dynamic_atoms: vec![],
            regexp_subject: None,
            regexp_matchers: Default::default(),
            atom_classes: vec![],
            dynamic_strings: None,
            symbol_registry: FxHashMap::default(),
            well_known_symbols: FxHashMap::default(),
            string_concats: None,
            field_caches: vec![],
            field_add_caches: FxHashMap::default(),
            megamorphic_field_indices: vec![],
            megamorphic_fields: vec![],
            length_atom: u32::MAX,
            prototype_atom: super::builtins::NO_CACHED_ATOM,
            size_atom: u32::MAX,
            byte_length_atom: u32::MAX,
            byte_offset_atom: u32::MAX,
            buffer_atom: u32::MAX,
            to_fixed_atom: u32::MAX,
            to_precision_atom: u32::MAX,
            runtime_atoms: RuntimeAtoms::default(),
            method_caches: vec![],
            megamorphic_methods: vec![],
            #[cfg(feature = "profile-aggregate")]
            invalidated_methods: FxHashMap::default(),
            object_shapes: vec![],
            descriptors: FxHashMap::default(),
            function_values: FxHashMap::default(),
            direct_eval: false,
            direct_eval_var_program: None,
            parameter_eval: false,
            eval_script_context: false,
            deferred_dependency_batch: false,
            construct_target: None,
            random_state: DEFAULT_RANDOM_SEED,
        }
    }
}
