//! Fresh plugin implementation - minimal 0.1 proof-of-concept
//!
//! Architecture: codegen_module receives full HIR JSON and traverses it to find
//! Decl::Function items with JSX bodies. Uses codegen.rs helpers to generate
//! VNode-based Rust code.

use proc_macro2::TokenStream;
use runts_plugin::{CargoDep, DevAction, DevContext, DevState, Plugin, PluginError, RouteInfo};

use crate::codegen::{jsx_element, jsx_expr, jsx_fragment, jsx_text, page_component};

pub struct FreshPlugin;

struct FreshDevState;

impl DevState for FreshDevState {}

impl Plugin for FreshPlugin {
    fn name(&self) -> &str { "fresh" }
    fn help_text(&self) -> &str { "Fresh/Preact web framework" }

    fn codegen_module(&self, hir_str: &str) -> Result<String, PluginError> {
        let hir: runts_plugin::hir::Module = serde_json::from_str(hir_str)
            .map_err(|e| PluginError::codegen("fresh", "unknown", format!("failed to parse HIR: {e}")))?;

        // If we have HIR items, try to extract JSX and generate VNode code
        if let Some(items_json) = &hir.items_json {
            if let Some(jsx_code) = self.try_codegen_jsx(items_json, &hir) {
                return Ok(jsx_code);
            }
        }

        // Fall back to stub-based codegen
        let source_path = hir.source_path.as_deref().unwrap_or("");
        let route_info = hir.route_info.as_ref();

        if route_info.is_some() {
            self.codegen_route_module(source_path, route_info)
        } else if source_path.contains("/islands/") {
            self.codegen_island_module(source_path)
        } else if source_path.contains("/components/") {
            self.codegen_component_module(source_path)
        } else {
            Ok(self.codegen_generic_module())
        }
    }

    fn cargo_deps(&self) -> Vec<CargoDep> {
        vec![
            CargoDep { name: "axum".to_string(), version: Some("0.7".to_string()), path: None, features: vec!["macros".to_string()] },
            CargoDep { name: "tokio".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["full".to_string()] },
            CargoDep { name: "serde".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["derive".to_string()] },
            CargoDep { name: "serde_json".to_string(), version: Some("1.0".to_string()), path: None, features: vec![] },
        ]
    }

    fn codegen_entry(&self, modules: &[runts_plugin::hir::Module]) -> Result<String, PluginError> {
        self.generate_main_entry(modules)
    }

    fn dev_init(&self, _ctx: &mut DevContext) -> Result<Box<dyn DevState>, PluginError> {
        Ok(Box::new(FreshDevState))
    }
    fn dev_run_once(&self, _state: &mut dyn DevState) -> Result<DevAction, PluginError> {
        Ok(DevAction::Continue)
    }
    fn dev_reload(&self, _ctx: &mut DevContext, _state: &mut dyn DevState) -> Result<(), PluginError> {
        Ok(())
    }
}

impl FreshPlugin {
    fn codegen_route_module(&self, file_path: &str, route_info: Option<&RouteInfo>) -> Result<String, PluginError> {
        let path = route_info.map(|r| r.path.as_str()).unwrap_or("/");

        // Determine page type based on route path for more realistic stubs
        let (page_type, page_desc) = Self::classify_route(path);

        // Detect TSX features from file extension (crude proxy for actual HIR analysis)
        let tsx_features = Self::detect_tsx_features(file_path);

        Ok(format!(r#"//! Route module for {path}
//! Generated by runts-fresh 0.1
//! File: {file_path}
//! Detected TSX features: {tsx_features}
//! Full JSX→VNode codegen coming in v0.2

use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "page {page_type}")
        .child(VNode::element("h1").child(VNode::text("{page_desc}")))
        .child(VNode::element("p").child(VNode::text("Page: {path}")))
        .child(VNode::element("p").child(VNode::text("Generated by runts-fresh 0.1")))
        .child(VNode::element("a").attr("href", "/").child(VNode::text("Go Home")))
}}
"#, path = path, file_path = file_path, page_type = page_type, page_desc = page_desc, tsx_features = tsx_features))
    }

    fn codegen_island_module(&self, file_path: &str) -> Result<String, PluginError> {
        let name = file_path.split('/').last().unwrap_or("Island").replace(".tsx", "").replace(".ts", "");

        // Generate a more realistic island stub based on common patterns
        // For 0.1, we generate static VNode; interactivity comes in 0.2
        Ok(format!(r#"//! Island: {name}
//! Generated by runts-fresh 0.1
//! Islands are client-side interactive components.
//! Full island codegen (useState, event handlers) coming in v0.2.

use runts_lib::runtime::vdom::VNode;

#[deriveserde::Serialize, runts_lib::runtime::vdom::VNodeProps)]
pub struct {name}Props {{
    // Props will be injected at runtime
}}

pub fn render(props: {name}Props) -> VNode {{
    VNode::element("div")
        .attr("class", "island island-{name}")
        .child(VNode::element("span").child(VNode::text("Island: {name}")))
        .child(VNode::element("button")
            .attr("class", "island-btn")
            .child(VNode::text("Click me (interactive in 0.2)")))
}}
"#, name = name))
    }

    fn codegen_component_module(&self, file_path: &str) -> Result<String, PluginError> {
        let name = file_path.split('/').last().unwrap_or("Component").replace(".tsx", "").replace(".ts", "");

        Ok(format!(r#"//! Component: {name}
//! Generated by runts-fresh 0.1
//! Components are reusable UI pieces.
//! Full component codegen with props coming in v0.2.

use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "component component-{name}")
        .child(VNode::element("span").child(VNode::text("Component: {name}")))
}}
"#, name = name))
    }

    fn codegen_generic_module(&self) -> String {
        "// Generic module - auto-generated by runts-fresh 0.1\n".to_string()
    }

    fn generate_main_entry(&self, modules: &[runts_plugin::hir::Module]) -> Result<String, PluginError> {
        let routes = self.collect_routes(modules);
        let (imports, handlers, router_calls) = self.generate_route_code(&routes);
        self.format_main_rs(&imports, &handlers, &router_calls)
    }

    fn collect_routes<'a>(&self, modules: &'a [runts_plugin::hir::Module]) -> Vec<&'a RouteInfo> {
        let mut routes: Vec<&RouteInfo> = modules.iter().filter_map(|m| m.route_info.as_ref()).collect();
        routes.sort_by(|a, b| a.path.cmp(&b.path));
        routes
    }

    fn generate_route_code(&self, routes: &[&RouteInfo]) -> (String, String, String) {
        let mut imports = String::new();
        let mut handlers = String::new();
        let mut router_calls = String::new();

        for route in routes {
            let safe_name = self.module_name_from_path(&route.file_path);
            let axum_path = self.to_axum_path(&route.path);
            imports.push_str(&format!("mod {};\n", safe_name));
            handlers.push_str(&format!(
                "async fn {}_handler() -> axum::response::Html<String> {{ let v = {}::render(); axum::response::Html(v.to_html()) }}\n",
                safe_name, safe_name
            ));
            router_calls.push_str(&format!("        .route(\"{}\", axum::routing::get({}_handler))\n", axum_path, safe_name));
        }

        (imports, handlers, router_calls)
    }

    fn format_main_rs(&self, imports: &str, handlers: &str, router_calls: &str) -> Result<String, PluginError> {
        Ok(format!(r#"//! Auto-generated by runts-fresh plugin 0.1
use axum::Router;
use std::net::SocketAddr;

{}

{}

#[tokio::main]
async fn main() {{
    let app = Router::new()
{};
    let addr = SocketAddr::from(([0, 0, 0, 0], 8000));
    println!("Starting server on {{}}", addr);
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}}
"#, imports.trim(), handlers.trim(), router_calls.trim()))
    }

    fn module_name_from_path(&self, path: &str) -> String {
        // Convert path like "blog/[slug].tsx" or "blog/index.tsx" to Rust module name
        // Strip extension, remove brackets, replace slashes with __
        let without_ext = path.replace(".tsx", "").replace(".ts", "").replace(".jsx", "").replace(".js", "");
        let no_brackets = without_ext.replace("[", "").replace("]", "");
        let with_underscores = no_brackets.replace("/", "__");
        with_underscores.replace("-", "_").replace("\\", "__")
    }

    fn to_axum_path(&self, path: &str) -> String {
        let p = path.replace("[", ":").replace("]", "");
        if p.starts_with('/') { p } else { format!("/{}", p) }
    }

    /// Classify route path to generate more specific stubs
    fn classify_route(path: &str) -> (&'static str, &'static str) {
        if path == "/" { return ("home", "Welcome to runts-fresh"); }
        if path == "/about" { return ("about", "About Page"); }
        if path == "/contact" { return ("contact", "Contact Us"); }
        if path == "/blog" || path == "/blog/" || path == "/blog/index" {
            return ("blog-list", "Blog");
        }
        if path.starts_with("/blog/") && !path.contains('[') {
            return ("blog-post", "Blog Post");
        }
        if path.contains('[') { return ("dynamic", "Dynamic Route"); }
        ("page", "Page")
    }

    /// Detect TSX features from file path (crude proxy for actual HIR analysis)
    /// Full HIR-based detection coming in 0.2
    fn detect_tsx_features(file_path: &str) -> &'static str {
        if file_path.contains("/islands/") {
            "JSX elements, island interactivity, useState hooks"
        } else if file_path.contains("/components/") {
            "JSX elements, component composition"
        } else if file_path.ends_with(".tsx") {
            "JSX elements, default export function, handler"
        } else {
            "TypeScript statements"
        }
    }

    /// Try to codegen JSX from HIR items JSON.
    /// Returns Some(code) if JSX was detected and codegen succeeded, None otherwise.
    fn try_codegen_jsx(&self, items: &serde_json::Value, _hir: &runts_plugin::hir::Module) -> Option<String> {
        // Parse items as array
        let items_arr = items.as_array()?;

        for item in items_arr {
            // Find Decl::Function items
            if item.get("type")?.as_str()? != "Decl" {
                continue;
            }
            let decl = item.get("Decl")?;
            if decl.get("kind")?.as_str()? != "Function" {
                continue;
            }

            // Extract function name and body
            let name = decl.get("name")?.as_str()?;
            let body = decl.get("body")?;

            // Check if body is present and contains JSX
            if body.is_null() {
                continue;
            }
            let body_str = body.to_string();
            if !body_str.contains("\"opening\"") && !body_str.contains("JSX") {
                continue;
            }

            // Find JSX expression in the return statement
            if let Some(jsx_expr) = self.find_jsx_in_body(body) {
                let jsx_code = self.generate_jsx_vnode_code(jsx_expr)?;
                let page_fn = page_component(name, jsx_code);
                let code = self.wrap_page_module(name, &page_fn.to_string());
                return Some(code);
            }
        }

        None
    }

    /// Find JSX expression in function body.
    /// Returns the JSX expression JSON if found.
    fn find_jsx_in_body(&self, body: &serde_json::Value) -> Option<serde_json::Value> {
        // Body structure: { "Block": { "stmts": [...] } } or direct JSX
        if let Some(block) = body.get("Block") {
            let stmts = block.get("stmts")?.as_array()?;
            for stmt in stmts {
                if let Some(jsx) = self.find_jsx_in_stmt(stmt) {
                    return Some(jsx);
                }
            }
        } else if self.is_jsx_expr(body) {
            return Some(body.clone());
        }
        None
    }

    /// Find JSX in a statement.
    // allow:complexity,too_many_lines
    fn find_jsx_in_stmt(&self, stmt: &serde_json::Value) -> Option<serde_json::Value> {
        let kind = stmt.get("kind")?.as_str()?;
        match kind {
            "Return" => {
                // Direct return: return <expr>
                let arg = stmt.get("arg")?;
                if self.is_jsx_expr(arg) {
                    return Some(arg.clone());
                }
                // Check nested expressions
                return self.find_jsx_in_expr(arg);
            }
            "Expr" => {
                // Expression statement: <expr>
                let expr = stmt.get("expr")?;
                if self.is_jsx_expr(expr) {
                    return Some(expr.clone());
                }
                return self.find_jsx_in_expr(expr);
            }
            "Block" => {
                // Block - traverse statements
                if let Some(stmts) = stmt.get("stmts").and_then(|s| s.as_array()) {
                    for s in stmts {
                        if let Some(jsx) = self.find_jsx_in_stmt(s) {
                            return Some(jsx);
                        }
                    }
                }
            }
            "If" => {
                // If statement - check consequent and alternate
                if let Some(cons) = stmt.get("consequent") {
                    if let Some(jsx) = self.find_jsx_in_stmt(cons) {
                        return Some(jsx);
                    }
                }
                if let Some(alt) = stmt.get("alternate") {
                    return self.find_jsx_in_stmt(alt);
                }
            }
            _ => {}
        }
        None
    }

    /// Find JSX in an expression.
    fn find_jsx_in_expr(&self, expr: &serde_json::Value) -> Option<serde_json::Value> {
        let kind = expr.get("kind")?.as_str()?;
        match kind {
            "JSX" => return Some(expr.clone()),
            "Cond" => {
                // Ternary: test ? consequent : alternate
                if let Some(cons) = expr.get("consequent") {
                    if let Some(jsx) = self.find_jsx_in_expr(cons) {
                        return Some(jsx);
                    }
                }
                if let Some(alt) = expr.get("alternate") {
                    return self.find_jsx_in_expr(alt);
                }
            }
            _ => {}
        }
        None
    }

    /// Check if JSON value is a JSX expression.
    fn is_jsx_expr(&self, val: &serde_json::Value) -> bool {
        val.get("opening").is_some() && val.get("children").is_some()
    }

    /// Generate VNode code from JSX expression JSON.
    fn generate_jsx_vnode_code(&self, jsx: serde_json::Value) -> Option<TokenStream> {
        let opening = jsx.get("opening")?;
        let name = opening.get("name")?;
        let tag = self.jsx_name_to_tag(name)?;

        // Convert attributes
        let attrs = self.extract_jsx_attrs(opening.get("attrs")?)?;

        // Convert children
        let children = self.extract_jsx_children(jsx.get("children")?)?;

        Some(jsx_element(&tag, attrs, children))
    }

    /// Convert JSXName to tag string.
    fn jsx_name_to_tag(&self, name: &serde_json::Value) -> Option<String> {
        match name {
            serde_json::Value::String(s) => Some(s.clone()),
            serde_json::Value::Object(obj) => {
                if let Some(ident) = obj.get("Ident") {
                    return ident.as_str().map(String::from);
                }
                None
            }
            _ => None,
        }
    }

    /// Extract attributes from JSX opening element.
    fn extract_jsx_attrs(&self, attrs: &serde_json::Value) -> Option<Vec<(String, TokenStream)>> {
        let arr = attrs.as_array()?;
        let mut result = Vec::new();
        for attr in arr {
            if let Some(obj) = attr.get("Attr") {
                let name = obj.get("name")?.as_str()?.to_string();
                let value = self.jsx_attr_value_to_tokenstream(obj.get("value")?)?;
                result.push((name, value));
            }
            // Ignore Spread attributes for now
        }
        Some(result)
    }

    /// Convert JSX attribute value to TokenStream.
    // allow:complexity
    fn jsx_attr_value_to_tokenstream(&self, val: &serde_json::Value) -> Option<TokenStream> {
        match val {
            serde_json::Value::Null => None,
            serde_json::Value::String(s) => {
                let lit = proc_macro2::Literal::string(s);
                Some(quote::quote! { #lit })
            }
            serde_json::Value::Object(obj) => {
                // Expression value: { "Expr": <expr> }
                if let Some(expr_val) = obj.get("Expr") {
                    let kind = expr_val.get("kind")?.as_str()?;
                    match kind {
                        "Ident" => {
                            let name = expr_val.get("name")?.as_str()?;
                            Some(quote::quote! { #name })
                        }
                        "String" => {
                            let s = expr_val.get("0")?.as_str()?;
                            Some(quote::quote! { #s })
                        }
                        "Number" => {
                            let n = expr_val.get("0")?.as_f64()?;
                            Some(quote::quote! { #n })
                        }
                        _ => None,
                    }
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    /// Extract children from JSX element.
    fn extract_jsx_children(&self, children: &serde_json::Value) -> Option<Vec<TokenStream>> {
        let arr = children.as_array()?;
        let mut result = Vec::new();
        for child in arr {
            if let Some(ts) = self.jsx_child_to_tokenstream(child)? {
                result.push(ts);
            }
        }
        Some(result)
    }

    /// Convert a JSX child to TokenStream.
    // allow:complexity
    fn jsx_child_to_tokenstream(&self, child: &serde_json::Value) -> Option<Option<TokenStream>> {
        // Text child
        if let Some(text) = child.as_str() {
            return Some(Some(jsx_text(text)));
        }

        // Object child
        let kind = child.get("kind")?.as_str()?;
        match kind {
            "Text" => {
                let text = child.get("0")?.as_str()?;
                Some(Some(jsx_text(text)))
            }
            "JSX" => {
                let jsx_expr = child.get("JSX")?;
                self.generate_jsx_vnode_code(jsx_expr.clone()).map(Some)
            }
            "Fragment" => {
                // Fragment: { "Fragment": { "children": [...] } }
                let frag_children = child.get("Fragment")?.get("children")?;
                let children = self.extract_jsx_children(frag_children)?;
                Some(Some(jsx_fragment(children)))
            }
            "Expr" => {
                // Expression child: { "Expr": <expr> }
                let expr_val = child.get("Expr")?;
                if let Some(ts) = self.jsx_expr_to_tokenstream(expr_val)? {
                    Some(Some(ts))
                } else {
                    Some(None)
                }
            }
            "Spread" => {
                // Spread children - skip for v0.1
                Some(None)
            }
            _ => Some(None),
        }
    }

    /// Convert JSX expression to TokenStream.
    // allow:complexity
    fn jsx_expr_to_tokenstream(&self, expr: &serde_json::Value) -> Option<Option<TokenStream>> {
        let kind = expr.get("kind")?.as_str()?;
        match kind {
            "Ident" => {
                let name = expr.get("name")?.as_str()?;
                Some(Some(jsx_expr(quote::quote! { #name })))
            }
            "String" => {
                let s = expr.get("0")?.as_str()?;
                Some(Some(jsx_text(s)))
            }
            "Number" => {
                let n = expr.get("0")?.as_f64()?;
                Some(Some(jsx_expr(quote::quote! { #n })))
            }
            "Boolean" => {
                let b = expr.get("0")?.as_bool()?;
                Some(Some(jsx_expr(quote::quote! { #b })))
            }
            "Bin" => {
                // Binary expression - skip for v0.1
                Some(None)
            }
            "Call" => {
                // Function call - skip for v0.1
                Some(None)
            }
            _ => Some(None),
        }
    }

    /// Wrap page component code in a module.
    fn wrap_page_module(&self, name: &str, page_fn: &str) -> String {
        let fn_name_lower = name.to_lowercase();
        format!(
            r#"//! Page component: {name}
//! Generated by runts-fresh 0.1

use runts_lib::runtime::vdom::VNode;

{page_fn}

pub fn render() -> VNode {{
    {fn_name_lower}()
}}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn normalize(s: &str) -> String {
        let s = s.replace(" :: ", "::");
        let s = s.replace(" ::", "::");
        let s = s.replace(":: ", "::");
        s
    }

    #[test]
    fn test_try_codegen_jsx_with_simple_div() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "Hello",
                    "body": {
                        "Block": {
                            "stmts": [
                                {
                                    "kind": "Return",
                                    "arg": {
                                        "kind": "JSX",
                                        "opening": {
                                            "name": { "Ident": "div" },
                                            "attrs": [],
                                            "self_closing": false
                                        },
                                        "children": [
                                            { "kind": "Text", "0": "Hello World" }
                                        ],
                                        "closing": {
                                            "name": { "Ident": "div" }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_some(), "Should generate code for JSX");
        let code = result.unwrap();
        eprintln!("Generated code:\n{}", code);

        // Check for VNode generation
        assert!(code.contains("VNode::Element") || code.contains("VNode"), "Should contain VNode");
        assert!(code.contains("\"div\""), "Should contain div tag");
        assert!(code.contains("Hello World"), "Should contain text");
    }

    #[test]
    fn test_try_codegen_jsx_with_attributes() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "Home",
                    "body": {
                        "Block": {
                            "stmts": [
                                {
                                    "kind": "Return",
                                    "arg": {
                                        "kind": "JSX",
                                        "opening": {
                                            "name": { "Ident": "div" },
                                            "attrs": [
                                                {
                                                    "Attr": {
                                                        "name": "class",
                                                        "value": "home"
                                                    }
                                                }
                                            ],
                                            "self_closing": false
                                        },
                                        "children": [
                                            { "kind": "Text", "0": "Welcome" }
                                        ],
                                        "closing": {
                                            "name": { "Ident": "div" }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_some(), "Should generate code for JSX with attrs");
        let code = result.unwrap();
        eprintln!("Generated code with attrs:\n{}", code);

        assert!(code.contains("\"class\""), "Should contain class attribute");
    }

    #[test]
    fn test_try_codegen_jsx_no_jsx_returns_none() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "NoJsx",
                    "body": {
                        "Block": {
                            "stmts": [
                                {
                                    "kind": "Return",
                                    "arg": { "kind": "String", "0": "hello" }
                                }
                            ]
                        }
                    }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_none(), "Should return None for non-JSX functions");
    }

    #[test]
    fn test_try_codegen_jsx_nested_elements() {
        let plugin = FreshPlugin;
        // Simplified nested: just the inner JSX structure without the outer wrapper
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "Nested",
                    "body": {
                        "Block": {
                            "stmts": [
                                {
                                    "kind": "Return",
                                    "arg": {
                                        "kind": "JSX",
                                        "opening": {
                                            "name": { "Ident": "div" },
                                            "attrs": [],
                                            "self_closing": false
                                        },
                                        "children": [
                                            {
                                                "kind": "JSX",
                                                "JSX": {
                                                    "opening": {
                                                        "name": { "Ident": "span" },
                                                        "attrs": [],
                                                        "self_closing": false
                                                    },
                                                    "children": [
                                                        { "kind": "Text", "0": "nested" }
                                                    ],
                                                    "closing": {
                                                        "name": { "Ident": "span" }
                                                    }
                                                }
                                            }
                                        ],
                                        "closing": {
                                            "name": { "Ident": "div" }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);
        eprintln!("Result: {:?}", result);

        assert!(result.is_some(), "Should generate code for nested JSX");
        let code = result.unwrap();
        eprintln!("Generated nested code:\n{}", code);

        assert!(code.contains("\"div\""), "Should contain outer div");
        assert!(code.contains("\"span\""), "Should contain inner span");
    }

    #[test]
    fn test_try_codegen_jsx_with_expr_child() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "WithExpr",
                    "body": {
                        "Block": {
                            "stmts": [
                                {
                                    "kind": "Return",
                                    "arg": {
                                        "kind": "JSX",
                                        "opening": {
                                            "name": { "Ident": "div" },
                                            "attrs": [],
                                            "self_closing": false
                                        },
                                        "children": [
                                            {
                                                "kind": "Expr",
                                                "Expr": {
                                                    "kind": "Ident",
                                                    "name": "name"
                                                }
                                            }
                                        ],
                                        "closing": {
                                            "name": { "Ident": "div" }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_some(), "Should generate code for JSX with expression child");
        let code = result.unwrap();
        eprintln!("Generated expr code:\n{}", code);

        assert!(code.contains("\"div\""), "Should contain div");
    }

    #[test]
    fn test_try_codegen_jsx_no_body_returns_none() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Function",
                    "name": "NoBody",
                    "body": null
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_none(), "Should return None for function with null body");
    }

    #[test]
    fn test_try_codegen_jsx_not_function_decl_returns_none() {
        let plugin = FreshPlugin;
        let items_json = serde_json::json!([
            {
                "type": "Decl",
                "Decl": {
                    "kind": "Variable",
                    "name": "x",
                    "init": { "kind": "Number", "0": 42 }
                }
            }
        ]);

        let hir = runts_plugin::hir::Module::new();
        let result = plugin.try_codegen_jsx(&items_json, &hir);

        assert!(result.is_none(), "Should return None for non-function declarations");
    }
}
