//! Fresh plugin implementation - minimal 0.1 proof-of-concept
//!
//! Architecture: codegen_module receives full HIR JSON but currently only uses
//! source_path and route_info. Full JSX→VNode codegen (using codegen.rs) is
//! planned for 0.2 when the plugin trait is extended to pass HIR to codegen_route_module.
//!
//! Note: codegen.rs exists at crate root (src/codegen.rs) but cannot be imported from
//! plugin.rs due to Rust module resolution rules. Will be accessible once codegen_route_module
//! signature is extended to receive HIR directly.

use runts_plugin::{CargoDep, DevAction, DevContext, DevState, Plugin, PluginError, RouteInfo};

pub struct FreshPlugin;

struct FreshDevState;

impl DevState for FreshDevState {}

impl Plugin for FreshPlugin {
    fn name(&self) -> &str { "fresh" }
    fn help_text(&self) -> &str { "Fresh/Preact web framework" }

    fn codegen_module(&self, hir_str: &str) -> Result<String, PluginError> {
        let hir: runts_plugin::hir::Module = serde_json::from_str(hir_str)
            .map_err(|e| PluginError::codegen("fresh", "unknown", format!("failed to parse HIR: {e}")))?;
        let source_path = hir.source_path.as_deref().unwrap_or("");
        let route_info = hir.route_info.as_ref();

        if route_info.is_some() {
            self.codegen_route_module(source_path, route_info)
        } else if source_path.contains("/islands/") {
            self.codegen_island_module(source_path)
        } else if source_path.contains("/components/") {
            self.codegen_component_module(source_path)
        } else {
            Ok(self.codegen_generic_module())
        }
    }

    fn cargo_deps(&self) -> Vec<CargoDep> {
        vec![
            CargoDep { name: "axum".to_string(), version: Some("0.7".to_string()), path: None, features: vec!["macros".to_string()] },
            CargoDep { name: "tokio".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["full".to_string()] },
            CargoDep { name: "serde".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["derive".to_string()] },
            CargoDep { name: "serde_json".to_string(), version: Some("1.0".to_string()), path: None, features: vec![] },
        ]
    }

    fn codegen_entry(&self, modules: &[runts_plugin::hir::Module]) -> Result<String, PluginError> {
        self.generate_main_entry(modules)
    }

    fn dev_init(&self, _ctx: &mut DevContext) -> Result<Box<dyn DevState>, PluginError> {
        Ok(Box::new(FreshDevState))
    }
    fn dev_run_once(&self, _state: &mut dyn DevState) -> Result<DevAction, PluginError> {
        Ok(DevAction::Continue)
    }
    fn dev_reload(&self, _ctx: &mut DevContext, _state: &mut dyn DevState) -> Result<(), PluginError> {
        Ok(())
    }
}

impl FreshPlugin {
    fn codegen_route_module(&self, file_path: &str, route_info: Option<&RouteInfo>) -> Result<String, PluginError> {
        let path = route_info.map(|r| r.path.as_str()).unwrap_or("/");

        // Determine page type based on route path for more realistic stubs
        let (page_type, page_desc) = Self::classify_route(path);

        // Detect TSX features from file extension (crude proxy for actual HIR analysis)
        let tsx_features = Self::detect_tsx_features(file_path);

        Ok(format!(r#"//! Route module for {path}
//! Generated by runts-fresh 0.1
//! File: {file_path}
//! Detected TSX features: {tsx_features}
//! Full JSX→VNode codegen coming in v0.2

use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "page {page_type}")
        .child(VNode::element("h1").child(VNode::text("{page_desc}")))
        .child(VNode::element("p").child(VNode::text("Page: {path}")))
        .child(VNode::element("p").child(VNode::text("Generated by runts-fresh 0.1")))
        .child(VNode::element("a").attr("href", "/").child(VNode::text("Go Home")))
}}
"#, path = path, file_path = file_path, page_type = page_type, page_desc = page_desc, tsx_features = tsx_features))
    }

    fn codegen_island_module(&self, file_path: &str) -> Result<String, PluginError> {
        let name = file_path.split('/').last().unwrap_or("Island").replace(".tsx", "").replace(".ts", "");

        // Generate a more realistic island stub based on common patterns
        // For 0.1, we generate static VNode; interactivity comes in 0.2
        Ok(format!(r#"//! Island: {name}
//! Generated by runts-fresh 0.1
//! Islands are client-side interactive components.
//! Full island codegen (useState, event handlers) coming in v0.2.

use runts_lib::runtime::vdom::VNode;

#[deriveserde::Serialize, runts_lib::runtime::vdom::VNodeProps)]
pub struct {name}Props {{
    // Props will be injected at runtime
}}

pub fn render(props: {name}Props) -> VNode {{
    VNode::element("div")
        .attr("class", "island island-{name}")
        .child(VNode::element("span").child(VNode::text("Island: {name}")))
        .child(VNode::element("button")
            .attr("class", "island-btn")
            .child(VNode::text("Click me (interactive in 0.2)")))
}}
"#, name = name))
    }

    fn codegen_component_module(&self, file_path: &str) -> Result<String, PluginError> {
        let name = file_path.split('/').last().unwrap_or("Component").replace(".tsx", "").replace(".ts", "");

        Ok(format!(r#"//! Component: {name}
//! Generated by runts-fresh 0.1
//! Components are reusable UI pieces.
//! Full component codegen with props coming in v0.2.

use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "component component-{name}")
        .child(VNode::element("span").child(VNode::text("Component: {name}")))
}}
"#, name = name))
    }

    fn codegen_generic_module(&self) -> String {
        "// Generic module - auto-generated by runts-fresh 0.1\n".to_string()
    }

    fn generate_main_entry(&self, modules: &[runts_plugin::hir::Module]) -> Result<String, PluginError> {
        let routes = self.collect_routes(modules);
        let (imports, handlers, router_calls) = self.generate_route_code(&routes);
        self.format_main_rs(&imports, &handlers, &router_calls)
    }

    fn collect_routes<'a>(&self, modules: &'a [runts_plugin::hir::Module]) -> Vec<&'a RouteInfo> {
        let mut routes: Vec<&RouteInfo> = modules.iter().filter_map(|m| m.route_info.as_ref()).collect();
        routes.sort_by(|a, b| a.path.cmp(&b.path));
        routes
    }

    fn generate_route_code(&self, routes: &[&RouteInfo]) -> (String, String, String) {
        let mut imports = String::new();
        let mut handlers = String::new();
        let mut router_calls = String::new();

        for route in routes {
            let safe_name = self.module_name_from_path(&route.file_path);
            let axum_path = self.to_axum_path(&route.path);
            imports.push_str(&format!("mod {};\n", safe_name));
            handlers.push_str(&format!(
                "async fn {}_handler() -> axum::response::Html<String> {{ let v = {}::render(); axum::response::Html(v.to_html()) }}\n",
                safe_name, safe_name
            ));
            router_calls.push_str(&format!("        .route(\"{}\", axum::routing::get({}_handler))\n", axum_path, safe_name));
        }

        (imports, handlers, router_calls)
    }

    fn format_main_rs(&self, imports: &str, handlers: &str, router_calls: &str) -> Result<String, PluginError> {
        Ok(format!(r#"//! Auto-generated by runts-fresh plugin 0.1
use axum::Router;
use std::net::SocketAddr;

{}

{}

#[tokio::main]
async fn main() {{
    let app = Router::new()
{};
    let addr = SocketAddr::from(([0, 0, 0, 0], 8000));
    println!("Starting server on {{}}", addr);
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}}
"#, imports.trim(), handlers.trim(), router_calls.trim()))
    }

    fn module_name_from_path(&self, path: &str) -> String {
        // Convert path like "blog/[slug].tsx" or "blog/index.tsx" to Rust module name
        // Strip extension, remove brackets, replace slashes with __
        let without_ext = path.replace(".tsx", "").replace(".ts", "").replace(".jsx", "").replace(".js", "");
        let no_brackets = without_ext.replace("[", "").replace("]", "");
        let with_underscores = no_brackets.replace("/", "__");
        with_underscores.replace("-", "_").replace("\\", "__")
    }

    fn to_axum_path(&self, path: &str) -> String {
        let p = path.replace("[", ":").replace("]", "");
        if p.starts_with('/') { p } else { format!("/{}", p) }
    }

    /// Classify route path to generate more specific stubs
    fn classify_route(path: &str) -> (&'static str, &'static str) {
        match path {
            "/" => ("home", "Welcome to runts-fresh"),
            "/about" => ("about", "About Page"),
            "/contact" => ("contact", "Contact Us"),
            "/blog" => ("blog-list", "Blog"),
            "/blog/" | "/blog/index" => ("blog-list", "Blog"),
            _ if path.starts_with("/blog/") && !path.contains("[") => ("blog-post", "Blog Post"),
            _ if path.contains("[") => ("dynamic", "Dynamic Route"),
            _ => ("page", "Page"),
        }
    }

    /// Detect TSX features from file path (crude proxy for actual HIR analysis)
    /// Full HIR-based detection coming in 0.2
    fn detect_tsx_features(file_path: &str) -> &'static str {
        if file_path.contains("/islands/") {
            "JSX elements, island interactivity, useState hooks"
        } else if file_path.contains("/components/") {
            "JSX elements, component composition"
        } else if file_path.ends_with(".tsx") {
            "JSX elements, default export function, handler"
        } else {
            "TypeScript statements"
        }
    }
}
