//! Fresh plugin implementation - minimal 0.1 proof-of-concept

use runts_plugin::{CargoDep, DevAction, DevContext, DevState, Plugin, RouteInfo};

pub struct FreshPlugin;

struct FreshDevState;

impl DevState for FreshDevState {}

impl Plugin for FreshPlugin {
    fn name(&self) -> &str { "fresh" }
    fn help_text(&self) -> &str { "Fresh/Preact web framework" }

    fn codegen_module(&self, hir_str: &str) -> anyhow::Result<String> {
        let hir: runts_plugin::hir::Module = serde_json::from_str(hir_str)
            .unwrap_or_else(|_| runts_plugin::hir::Module::new());
        let source_path = hir.source_path.as_deref().unwrap_or("");
        let route_info = hir.route_info.as_ref();

        if route_info.is_some() {
            self.codegen_route_module(source_path, route_info)
        } else if source_path.contains("/islands/") {
            self.codegen_island_module(source_path)
        } else if source_path.contains("/components/") {
            self.codegen_component_module(source_path)
        } else {
            Ok(self.codegen_generic_module())
        }
    }

    fn cargo_deps(&self) -> Vec<CargoDep> {
        vec![
            CargoDep { name: "axum".to_string(), version: Some("0.7".to_string()), path: None, features: vec!["macros".to_string()] },
            CargoDep { name: "tokio".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["full".to_string()] },
            CargoDep { name: "serde".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["derive".to_string()] },
            CargoDep { name: "serde_json".to_string(), version: Some("1.0".to_string()), path: None, features: vec![] },
        ]
    }

    fn codegen_entry(&self, modules: &[runts_plugin::hir::Module]) -> anyhow::Result<String> {
        self.generate_main_entry(modules)
    }

    fn dev_init(&self, _ctx: &mut DevContext) -> anyhow::Result<Box<dyn DevState>> {
        Ok(Box::new(FreshDevState))
    }
    fn dev_run_once(&self, _state: &mut dyn DevState) -> anyhow::Result<DevAction> {
        Ok(DevAction::Continue)
    }
    fn dev_reload(&self, _ctx: &mut DevContext, _state: &mut dyn DevState) -> anyhow::Result<()> {
        Ok(())
    }
}

impl FreshPlugin {
    fn codegen_route_module(&self, _file_path: &str, route_info: Option<&RouteInfo>) -> anyhow::Result<String> {
        let path = route_info.map(|r| r.path.as_str()).unwrap_or("/");
        Ok(format!(r#"//! Route module for {path}
use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "page")
        .child(VNode::element("h1").child(VNode::text("Page: {path}")))
        .child(VNode::element("p").child(VNode::text("Generated by runts-fresh 0.1")))
}}
"#, path = path))
    }

    fn codegen_island_module(&self, file_path: &str) -> anyhow::Result<String> {
        let name = file_path.split('/').last().unwrap_or("Island").replace(".tsx", "").replace(".ts", "");
        Ok(format!(r#"//! Island: {name}
use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div").attr("class", "island-{name}").child(VNode::text("Island: {name}"))
}}
"#, name = name))
    }

    fn codegen_component_module(&self, file_path: &str) -> anyhow::Result<String> {
        let name = file_path.split('/').last().unwrap_or("Component").replace(".tsx", "").replace(".ts", "");
        Ok(format!(r#"//! Component: {name}
use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div").attr("class", "component-{name}").child(VNode::text("Component: {name}"))
}}
"#, name = name))
    }

    fn codegen_generic_module(&self) -> String {
        "// Generic module - auto-generated by runts-fresh 0.1\n".to_string()
    }

    fn generate_main_entry(&self, modules: &[runts_plugin::hir::Module]) -> anyhow::Result<String> {
        let routes = self.collect_routes(modules);
        let (imports, handlers, router_calls) = self.generate_route_code(&routes);
        self.format_main_rs(&imports, &handlers, &router_calls)
    }

    fn collect_routes<'a>(&self, modules: &'a [runts_plugin::hir::Module]) -> Vec<&'a RouteInfo> {
        let mut routes: Vec<&RouteInfo> = modules.iter().filter_map(|m| m.route_info.as_ref()).collect();
        routes.sort_by(|a, b| a.path.cmp(&b.path));
        routes
    }

    fn generate_route_code(&self, routes: &[&RouteInfo]) -> (String, String, String) {
        let mut imports = String::new();
        let mut handlers = String::new();
        let mut router_calls = String::new();

        for route in routes {
            let safe_name = self.module_name_from_path(&route.file_path);
            let axum_path = self.to_axum_path(&route.path);
            imports.push_str(&format!("mod {};\n", safe_name));
            handlers.push_str(&format!(
                "async fn {}_handler() -> axum::response::Html<String> {{ let v = {}::render(); axum::response::Html(v.to_html()) }}\n",
                safe_name, safe_name
            ));
            router_calls.push_str(&format!("        .route(\"{}\", axum::routing::get({}_handler))\n", axum_path, safe_name));
        }

        (imports, handlers, router_calls)
    }

    fn format_main_rs(&self, imports: &str, handlers: &str, router_calls: &str) -> anyhow::Result<String> {
        Ok(format!(r#"//! Auto-generated by runts-fresh plugin 0.1
use axum::Router;
use std::net::SocketAddr;

{}

{}

#[tokio::main]
async fn main() {{
    let app = Router::new()
{};
    let addr = SocketAddr::from(([0, 0, 0, 0], 8000));
    println!("Starting server on {{}}", addr);
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}}
"#, imports.trim(), handlers.trim(), router_calls.trim()))
    }

    fn module_name_from_path(&self, path: &str) -> String {
        // Convert path like "blog/[slug].tsx" or "blog/index.tsx" to Rust module name
        // Strip extension, remove brackets, replace slashes with __
        let without_ext = path.replace(".tsx", "").replace(".ts", "");
        let no_brackets = without_ext.replace("[", "").replace("]", "");
        let with_underscores = no_brackets.replace("/", "__");
        with_underscores.replace("-", "_").replace("\\", "__")
    }

    fn to_axum_path(&self, path: &str) -> String {
        let p = path.replace("[", ":").replace("]", "");
        if p.starts_with('/') { p } else { format!("/{}", p) }
    }
}
