const assert = require("assert");
const fs = require("fs");
const folder = fs.mkdtempSync("/tmp/quench-node-");
const file = `${folder}/file`;
fs.writeFileSync(file, "one");
fs.appendFileSync(file, "-two");
assert.strictEqual(fs.readFileSync(file, "utf8"), "one-two");
fs.accessSync(file);
assert.throws(() => fs.accessSync(`${folder}/missing`));
fs.unlinkSync(file);
fs.rmdirSync(folder);
