//! Basic module codegen

pub struct FreshCodegen {
    source_path: String,
}

impl FreshCodegen {
    pub fn new(source_path: &str) -> Self {
        Self { source_path: source_path.to_string() }
    }

    pub fn codegen_generic_module(&self) -> String {
        let content = "// Generic module - auto-generated by runts-fresh 0.1\n";
        content.to_string()
    }

    pub fn is_middleware_path(&self) -> bool {
        let path = &self.source_path;
        let in_routes = path.starts_with("routes/") || path.contains("/routes/");
        if !in_routes { return false; }
        let leaf = path.rsplit_once('/').map(|(_, l)| l).unwrap_or(path);
        leaf == "_middleware.ts" || leaf == "_middleware.tsx"
    }

    pub fn codegen_middleware_module(&self, _hir: &runts_plugin::hir::Module) -> Result<String, runts_plugin::PluginError> {
        let safe_name = self.source_path
            .rsplit_once('/').map(|(_, l)| l).unwrap_or(&self.source_path)
            .replace(".ts", "").replace(".tsx", "");

        Ok(format!(r#"//! Middleware: {path}
//! Generated by runts-fresh 0.1

use std::time::Instant;

pub async fn {safe_name}(
    req: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {{
    let start = Instant::now();
    let mut resp = next.run(req).await;
    let elapsed_ms = start.elapsed().as_millis();
    let _ = resp.headers_mut().insert(
        axum::http::HeaderName::from_static("x-response-time"),
        axum::http::HeaderValue::from_str(&format!("{{elapsed_ms}}ms")).unwrap_or_default(),
    );
    resp
}}
"#, safe_name = safe_name, path = self.source_path))
    }

    pub fn codegen_route_module(&self, route_info: Option<&RouteInfo>) -> Result<String, runts_plugin::PluginError> {
        let path = route_info.map(|r| r.path.as_str()).unwrap_or("/");
        let (page_type, page_desc) = classify_route(path);

        Ok(format!(r#"//! Route module for {path}
//! Generated by runts-fresh 0.1

use runts_lib::runtime::vdom::VNode;

pub fn render(route_param: Option<&str>) -> VNode {{
    let mut root = VNode::element("div")
        .attr("class", "page {page_type}")
        .child(VNode::element("h1").child(VNode::text("{page_desc}")));
    if let Some(p) = route_param {{
        root = root.child(VNode::element("p").child(VNode::text(p)));
    }}
    root
}}
"#, page_type = page_type, page_desc = page_desc, path = path))
    }

    pub fn codegen_island_module(&self) -> Result<String, runts_plugin::PluginError> {
        let name = self.source_path
            .rsplit_once('/').map(|(_, l)| l).unwrap_or(&self.source_path)
            .replace(".tsx", "").replace(".ts", "");

        Ok(format!(r#"//! Island module: {name}
//! Generated by runts-fresh 0.1

use runts_lib::runtime::vdom::VNode;

#[derive(Default)]
pub struct {name}Props {{}}

pub fn render(props: {name}Props) -> VNode {{
    VNode::element("div")
        .attr("class", "island island-{name}")
        .child(VNode::text("Island: {name}"))
}}
"#, name = name))
    }

    pub fn codegen_component_module(&self) -> Result<String, runts_plugin::PluginError> {
        let name = self.source_path
            .rsplit_once('/').map(|(_, l)| l).unwrap_or(&self.source_path)
            .replace(".tsx", "").replace(".ts", "");

        Ok(format!(r#"//! Component module: {name}
//! Generated by runts-fresh 0.1

use runts_lib::runtime::vdom::VNode;

pub fn render() -> VNode {{
    VNode::element("div")
        .attr("class", "component component-{name}")
        .child(VNode::element("span").child(VNode::text("Component: {name}")))
}}
"#, name = name))
    }
}

fn classify_route(path: &str) -> (&'static str, &'static str) {
    if path == "/" { ("home", "Home Page") }
    else if path.starts_with("/api/") { ("api", "API Endpoint") }
    else if path.contains('/') { ("dynamic", "Dynamic Page") }
    else { ("static", "Static Page") }
}

use runts_plugin::RouteInfo;
