//! Route and middleware codegen for Fresh plugin

mod codegen;
mod jsx;
mod routes;

pub use codegen::FreshCodegen;
pub use jsx::JsxHandler;
pub use routes::RouteHandler;

use runts_plugin::{CargoDep, Plugin, PluginError, RouteInfo};

use crate::codegen::{jsx_element, jsx_expr, jsx_fragment, jsx_text, page_component};

pub struct FreshPlugin;

impl Plugin for FreshPlugin {
    fn name(&self) -> &str { "fresh" }
    fn help_text(&self) -> &str { "Fresh/Preact web framework" }

    fn codegen_module(&self, module: &runts_hir::Module) -> Result<String, PluginError> {
        if let Some(jsx_code) = self.try_jsx_codegen(module) {
            return Ok(jsx_code);
        }
        self.codegen_fallback_module(module)
    }

    fn cargo_deps(&self) -> Vec<CargoDep> {
        vec![
            CargoDep { name: "axum".to_string(), version: Some("0.7".to_string()), path: None, features: vec!["macros".to_string()] },
            CargoDep { name: "tokio".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["full".to_string()] },
            CargoDep { name: "serde".to_string(), version: Some("1.0".to_string()), path: None, features: vec!["derive".to_string()] },
            CargoDep { name: "serde_json".to_string(), version: Some("1.0".to_string()), path: None, features: vec![] },
        ]
    }

    fn codegen_entry(&self, modules: &[runts_hir::Module]) -> Result<String, PluginError> {
        let routes = self.collect_routes(modules);
        let (imports, handlers, router_calls) = self.generate_route_code(&routes, modules);
        self.format_main_rs(&imports, &handlers, &router_calls)
    }

    fn dev_init(&self, ctx: &mut runts_plugin::DevContext) -> Result<Box<dyn runts_plugin::DevState>, PluginError> {
        use crate::dev_server::FreshDevState;
        Ok(Box::new(FreshDevState::new(ctx.root.clone())))
    }

    fn dev_run_once(&self, state: &mut dyn runts_plugin::DevState) -> Result<runts_plugin::DevAction, PluginError> {
        use crate::dev_server::FreshDevState;
        let dev_state = state.as_any().downcast_ref::<FreshDevState>()
            .ok_or_else(|| PluginError::new("fresh", "", "invalid dev state type"))?;
        dev_state.ensure_server_running()?;
        Ok(runts_plugin::DevAction::Continue)
    }

    fn dev_reload(&self, ctx: &mut runts_plugin::DevContext, state: &mut dyn runts_plugin::DevState) -> Result<(), PluginError> {
        use crate::dev_server::FreshDevState;
        let dev_state = state.as_any().downcast_ref::<FreshDevState>()
            .ok_or_else(|| PluginError::new("fresh", "", "invalid dev state type"))?;
        println!("File change detected, recompiling {} modules...", ctx.modules.len());
        dev_state.recompile(ctx.modules.len())?;
        println!("Modules rescanned: {} files", ctx.modules.len());
        Ok(())
    }
}

impl FreshPlugin {
    fn try_jsx_codegen(&self, hir: &runts_hir::Module) -> Option<String> {
        let items_json = serde_json::to_value(&hir.items).ok()?;
        let handler = JsxHandler::new();
        handler.try_codegen_jsx(&items_json, hir)
    }

    fn codegen_fallback_module(&self, hir: &runts_hir::Module) -> Result<String, PluginError> {
        let source_path = hir.source_path.as_deref().unwrap_or("");
        let route_info = hir.route_info.as_ref();
        let codegen = FreshCodegen::new(source_path);

        if route_info.is_some() {
            codegen.codegen_route_module(route_info)
        } else if source_path.contains("/islands/") {
            codegen.codegen_island_module()
        } else if source_path.contains("/components/") {
            codegen.codegen_component_module()
        } else if codegen.is_middleware_path() {
            codegen.codegen_middleware_module(hir)
        } else {
            Ok(codegen.codegen_generic_module())
        }
    }

    fn collect_routes<'a>(&self, modules: &'a [runts_hir::Module]) -> Vec<&'a RouteInfo> {
        let mut routes: Vec<&RouteInfo> = modules.iter().filter_map(|m| m.route_info.as_ref()).collect();
        routes.sort_by(|a, b| a.path.cmp(&b.path));
        routes
    }

    fn generate_route_code(&self, routes: &[&RouteInfo], modules: &[runts_hir::Module]) -> (String, String, String) {
        let handler = RouteHandler::new(modules);
        handler.generate_route_code(routes)
    }

    fn format_main_rs(&self, imports: &str, handlers: &str, router_calls: &str) -> Result<String, PluginError> {
        Ok(format!(r#"//! Main entry point
//! Generated by runts-fresh 0.1

use runts_lib::runtime::vdom::VNode;
{imports}
{handlers}
#[tokio::main]
async fn main() {{
    use axum::Router;
    let app = Router::new()
{router_calls}
        .layer(tower_http::cors::CorsLayer::permissive());
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("Fresh server running on http://localhost:3000");
    axum::serve(listener, app).await;
}}
"#))
    }
}
