//! Canonical HTTP/2 utility facts shared by the Rust host surfaces.

pub(crate) const HEADER_CONSTANTS: &[(&str, &str)] = &[
    ("HTTP2_HEADER_STATUS", ":status"),
    ("HTTP2_HEADER_METHOD", ":method"),
    ("HTTP2_HEADER_AUTHORITY", ":authority"),
    ("HTTP2_HEADER_SCHEME", ":scheme"),
    ("HTTP2_HEADER_PATH", ":path"),
    ("HTTP2_HEADER_PROTOCOL", ":protocol"),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS",
        "access-control-allow-credentials",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_MAX_AGE",
        "access-control-max-age",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_REQUEST_METHOD",
        "access-control-request-method",
    ),
    ("HTTP2_HEADER_AGE", "age"),
    ("HTTP2_HEADER_AUTHORIZATION", "authorization"),
    ("HTTP2_HEADER_CONTENT_ENCODING", "content-encoding"),
    ("HTTP2_HEADER_CONTENT_LANGUAGE", "content-language"),
    ("HTTP2_HEADER_CONTENT_LENGTH", "content-length"),
    ("HTTP2_HEADER_CONTENT_LOCATION", "content-location"),
    ("HTTP2_HEADER_CONTENT_MD5", "content-md5"),
    ("HTTP2_HEADER_CONTENT_RANGE", "content-range"),
    ("HTTP2_HEADER_CONTENT_TYPE", "content-type"),
    ("HTTP2_HEADER_DATE", "date"),
    ("HTTP2_HEADER_DNT", "dnt"),
    ("HTTP2_HEADER_ETAG", "etag"),
    ("HTTP2_HEADER_EXPIRES", "expires"),
    ("HTTP2_HEADER_FROM", "from"),
    ("HTTP2_HEADER_HOST", "host"),
    ("HTTP2_HEADER_IF_MATCH", "if-match"),
    ("HTTP2_HEADER_IF_MODIFIED_SINCE", "if-modified-since"),
    ("HTTP2_HEADER_IF_NONE_MATCH", "if-none-match"),
    ("HTTP2_HEADER_IF_RANGE", "if-range"),
    ("HTTP2_HEADER_IF_UNMODIFIED_SINCE", "if-unmodified-since"),
    ("HTTP2_HEADER_LAST_MODIFIED", "last-modified"),
    ("HTTP2_HEADER_LOCATION", "location"),
    ("HTTP2_HEADER_MAX_FORWARDS", "max-forwards"),
    ("HTTP2_HEADER_PROXY_AUTHORIZATION", "proxy-authorization"),
    ("HTTP2_HEADER_RANGE", "range"),
    ("HTTP2_HEADER_REFERER", "referer"),
    ("HTTP2_HEADER_RETRY_AFTER", "retry-after"),
    ("HTTP2_HEADER_TK", "tk"),
    (
        "HTTP2_HEADER_UPGRADE_INSECURE_REQUESTS",
        "upgrade-insecure-requests",
    ),
    ("HTTP2_HEADER_USER_AGENT", "user-agent"),
    (
        "HTTP2_HEADER_X_CONTENT_TYPE_OPTIONS",
        "x-content-type-options",
    ),
    ("HTTP2_HEADER_ACCEPT_CHARSET", "accept-charset"),
    ("HTTP2_HEADER_ACCEPT_ENCODING", "accept-encoding"),
    ("HTTP2_HEADER_ACCEPT_LANGUAGE", "accept-language"),
    ("HTTP2_HEADER_ACCEPT_RANGES", "accept-ranges"),
    ("HTTP2_HEADER_ACCEPT", "accept"),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_HEADERS",
        "access-control-allow-headers",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_METHODS",
        "access-control-allow-methods",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN",
        "access-control-allow-origin",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS",
        "access-control-expose-headers",
    ),
    (
        "HTTP2_HEADER_ACCESS_CONTROL_REQUEST_HEADERS",
        "access-control-request-headers",
    ),
    ("HTTP2_HEADER_ALLOW", "allow"),
    ("HTTP2_HEADER_CACHE_CONTROL", "cache-control"),
    ("HTTP2_HEADER_CONTENT_DISPOSITION", "content-disposition"),
    ("HTTP2_HEADER_COOKIE", "cookie"),
    ("HTTP2_HEADER_EXPECT", "expect"),
    ("HTTP2_HEADER_FORWARDED", "forwarded"),
    ("HTTP2_HEADER_LINK", "link"),
    ("HTTP2_HEADER_PREFER", "prefer"),
    ("HTTP2_HEADER_PROXY_AUTHENTICATE", "proxy-authenticate"),
    ("HTTP2_HEADER_REFRESH", "refresh"),
    ("HTTP2_HEADER_SERVER", "server"),
    ("HTTP2_HEADER_SET_COOKIE", "set-cookie"),
    (
        "HTTP2_HEADER_STRICT_TRANSPORT_SECURITY",
        "strict-transport-security",
    ),
    ("HTTP2_HEADER_TRAILER", "trailer"),
    ("HTTP2_HEADER_VARY", "vary"),
    ("HTTP2_HEADER_VIA", "via"),
    ("HTTP2_HEADER_WARNING", "warning"),
    ("HTTP2_HEADER_WWW_AUTHENTICATE", "www-authenticate"),
    ("HTTP2_HEADER_X_FRAME_OPTIONS", "x-frame-options"),
    ("HTTP2_HEADER_CONNECTION", "connection"),
    ("HTTP2_HEADER_UPGRADE", "upgrade"),
    ("HTTP2_HEADER_HTTP2_SETTINGS", "http2-settings"),
    ("HTTP2_HEADER_TE", "te"),
    ("HTTP2_HEADER_TRANSFER_ENCODING", "transfer-encoding"),
    ("HTTP2_HEADER_KEEP_ALIVE", "keep-alive"),
    ("HTTP2_HEADER_PROXY_CONNECTION", "proxy-connection"),
];

pub(crate) const OPTION_FIELDS: &[(&str, usize)] = &[
    ("maxDeflateDynamicTableSize", 0),
    ("maxReservedRemoteStreams", 1),
    ("maxSendHeaderBlockLength", 2),
    ("peerMaxConcurrentStreams", 3),
    ("paddingStrategy", 4),
    ("maxHeaderListPairs", 5),
    ("maxOutstandingPings", 6),
    ("maxOutstandingSettings", 7),
    ("maxSessionMemory", 8),
    ("maxSettings", 9),
    ("streamResetRate", 10),
    ("streamResetBurst", 11),
];

pub(crate) const CONNECTION_HEADERS: &[&str] = &[
    "connection",
    "upgrade",
    "http2-settings",
    "transfer-encoding",
    "proxy-connection",
    "keep-alive",
];

pub(crate) const SINGLE_VALUE_HEADERS: &[&str] = &[
    ":status",
    ":method",
    ":authority",
    ":scheme",
    ":path",
    "access-control-allow-credentials",
    "access-control-max-age",
    "access-control-request-method",
    "age",
    "authorization",
    "content-encoding",
    "content-language",
    "content-length",
    "content-location",
    "content-md5",
    "content-range",
    "content-type",
    "date",
    "dnt",
    "etag",
    "expires",
    "from",
    "host",
    "if-match",
    "if-modified-since",
    "if-none-match",
    "if-range",
    "if-unmodified-since",
    "last-modified",
    "location",
    "max-forwards",
    "proxy-authorization",
    "range",
    "referer",
    "retry-after",
    "tk",
    "upgrade-insecure-requests",
    "user-agent",
    "x-content-type-options",
];
