(function (deps) {
  'use strict';
  var origin=Date.now(), entries=[], observers=[];
  function now(){return Date.now()-origin;}
  function PerformanceEntry(name,type,start,duration){this.name=name;this.entryType=type;this.startTime=start;this.duration=duration;}
  function PerformanceResourceTiming(name,start,duration,opts){PerformanceEntry.call(this,name,'resource',start,duration);opts=opts||{};this.initiatorType=opts.initiatorType||'';this.nextHopProtocol=opts.nextHopProtocol||'';this.fetchStart=opts.fetchStart===undefined?start:opts.fetchStart;this.responseEnd=this.fetchStart+duration;this.transferSize=opts.transferSize||0;this.encodedBodySize=opts.encodedBodySize||0;this.decodedBodySize=opts.decodedBodySize||0;}
  PerformanceResourceTiming.prototype=Object.create(PerformanceEntry.prototype);
  function add(name,type,start,duration,extra){var e=type==='resource'?new PerformanceResourceTiming(name,start,duration,extra):new PerformanceEntry(name,type,start,duration),i,o;entries.push(e);for(i=0;i<observers.length;i++){o=observers[i];if(o.types&&o.types.indexOf(type)>=0)o.callback({getEntries:function(){return[e];},getEntriesByName:function(n){return n===e.name?[e]:[];},getEntriesByType:function(t){return t===e.entryType?[e]:[];}},o);}return e;}
  var performance={now:now,timeOrigin:origin,mark:function(n){return add(String(n),'mark',now(),0);},measure:function(n,s,en){var a=0,b=now(),i;if(s!==undefined)for(i=entries.length-1;i>=0;i--)if(entries[i].name===String(s)&&entries[i].entryType==='mark'){a=entries[i].startTime;break;}if(en!==undefined)for(i=entries.length-1;i>=0;i--)if(entries[i].name===String(en)&&entries[i].entryType==='mark'){b=entries[i].startTime;break;}return add(String(n),'measure',a,b-a);},getEntries:function(){return entries.slice();},getEntriesByName:function(n,t){return entries.filter(function(e){return e.name===String(n)&&(t===undefined||e.entryType===t);});},getEntriesByType:function(t){return entries.filter(function(e){return e.entryType===t;});},clearMarks:function(n){entries=entries.filter(function(e){return e.entryType!=='mark'||(n!==undefined&&e.name!==String(n));});},clearMeasures:function(n){entries=entries.filter(function(e){return e.entryType!=='measure'||(n!==undefined&&e.name!==String(n));});},clearResourceTimings:function(){entries=entries.filter(function(e){return e.entryType!=='resource';});},_addResource:function(n,d,o){return add(String(n),'resource',now(),Number(d)||0,o);}};
  function PerformanceObserver(cb){if(!(this instanceof PerformanceObserver))throw new TypeError('Illegal constructor');this.callback=cb;this.types=null;} PerformanceObserver.prototype.observe=function(o){this.types=(o&&o.entryTypes)||null;if(observers.indexOf(this)<0)observers.push(this);};PerformanceObserver.prototype.disconnect=function(){var i=observers.indexOf(this);if(i>=0)observers.splice(i,1);};PerformanceObserver.prototype.takeRecords=function(){return[];};
  function histogram(){var a=[];function q(n){if(!a.length)return 0;var b=a.slice().sort(function(x,y){return x-y;}),i=Math.min(b.length-1,Math.max(0,Math.ceil(n*b.length)-1));return b[i];}return{record:function(v){if(isFinite(v))a.push(Number(v));},reset:function(){a=[];},get min(){return a.length?Math.min.apply(Math,a):0;},get max(){return a.length?Math.max.apply(Math,a):0;},get mean(){return a.length?a.reduce(function(x,y){return x+y;},0)/a.length:0;},exceeds:function(v){return a.some(function(x){return x>v;});},percentile:function(n){return q(Number(n)/100);},percentiles:function(){return{};}};}
  function timerify(fn){return function(){var s=now(),r=fn.apply(this,arguments);if(r&&r.then)r.then(function(){add(fn.name||'','function',s,now()-s);});else add(fn.name||'','function',s,now()-s);return r;};}
  function elu(){return{idle:0,active:0,utilization:0};} function monitor(){var h=histogram();return{enable:function(){return this;},disable:function(){return this;},reset:function(){h.reset();},get min(){return h.min;},get max(){return h.max;},get mean(){return h.mean;},get stddev(){return 0;},percentile:function(n){return h.percentile(n);},percentiles:function(){return{};}};}
  return{performance:performance,PerformanceObserver:PerformanceObserver,PerformanceEntry:PerformanceEntry,PerformanceResourceTiming:PerformanceResourceTiming,PerformanceMark:PerformanceEntry,PerformanceMeasure:PerformanceEntry,monitorEventLoopDelay:monitor,createHistogram:histogram,constants:{NODE_PERFORMANCE_GC:1,NODE_PERFORMANCE_GC_MAJOR:4,NODE_PERFORMANCE_GC_MINOR:1,NODE_PERFORMANCE_GC_INCREMENTAL:8,NODE_PERFORMANCE_GC_WEAKCB:16},timerify:timerify,eventLoopUtilization:elu};
})