(function (deps) {
  'use strict';
  var origin=Date.now(), entries=[], observers=[];
  function now(){return Date.now()-origin;}
  function PerformanceEntry(name,type,start,duration,detail){this.name=name;this.entryType=type;this.startTime=start;this.duration=duration;this.detail=detail;}
  function PerformanceResourceTiming(name,start,duration,opts){PerformanceEntry.call(this,name,'resource',start,duration);opts=opts||{};this.initiatorType=opts.initiatorType||'';this.nextHopProtocol=opts.nextHopProtocol||'';this.fetchStart=opts.fetchStart===undefined?start:opts.fetchStart;this.responseEnd=this.fetchStart+duration;this.transferSize=opts.transferSize||0;this.encodedBodySize=opts.encodedBodySize||0;this.decodedBodySize=opts.decodedBodySize||0;}
  PerformanceResourceTiming.prototype=Object.create(PerformanceEntry.prototype);
  function add(name,type,start,duration,extra){var e=type==='resource'?new PerformanceResourceTiming(name,start,duration,extra):new PerformanceEntry(name,type,start,duration,extra&&extra.detail),i,o;entries.push(e);for(i=0;i<observers.length;i++){o=observers[i];if(o.types&&o.types.indexOf(type)>=0){o.records.push(e);o.callback({getEntries:function(){return o.records.slice();},getEntriesByName:function(n){return o.records.filter(function(x){return x.name===n;});},getEntriesByType:function(t){return o.records.filter(function(x){return x.entryType===t;});}},o);}}return e;}
  var performance={now:now,timeOrigin:origin,mark:function(n,o){o=o||{};var t=o.startTime===undefined?now():Number(o.startTime);if(!isFinite(t)||t<0)throw new TypeError('startTime must be a non-negative finite number');return add(String(n),'mark',t,0,{detail:o.detail});},measure:function(n,s,en,o){o=o||{};var a=0,b=now(),i;if(typeof s==='object'){o=s;s=o.start;en=o.end;}if(s!==undefined){for(i=entries.length-1;i>=0;i--)if(entries[i].name===String(s)&&entries[i].entryType==='mark'){a=entries[i].startTime;break;}if(i<0)throw new DOMException('The ["'+String(s)+'"] performance mark has not been set','SyntaxError');}if(en!==undefined){for(i=entries.length-1;i>=0;i--)if(entries[i].name===String(en)&&entries[i].entryType==='mark'){b=entries[i].startTime;break;}if(i<0)throw new DOMException('The ["'+String(en)+'"] performance mark has not been set','SyntaxError');}if(o.startTime!==undefined)a=Number(o.startTime);if(o.endTime!==undefined)b=Number(o.endTime);if(o.duration!==undefined)b=a+Number(o.duration);return add(String(n),'measure',a,b-a,{detail:o.detail});},getEntries:function(){return entries.slice();},getEntriesByName:function(n,t){return entries.filter(function(e){return e.name===String(n)&&(t===undefined||e.entryType===t);});},getEntriesByType:function(t){return entries.filter(function(e){return e.entryType===t;});},clearMarks:function(n){entries=entries.filter(function(e){return e.entryType!=='mark'||(n!==undefined&&e.name!==String(n));});},clearMeasures:function(n){entries=entries.filter(function(e){return e.entryType!=='measure'||(n!==undefined&&e.name!==String(n));});},clearResourceTimings:function(){entries=entries.filter(function(e){return e.entryType!=='resource';});},_addResource:function(n,d,o){return add(String(n),'resource',now(),Number(d)||0,o);}};
  function PerformanceObserver(cb){if(!(this instanceof PerformanceObserver))throw new TypeError('Illegal constructor');this.callback=cb;this.types=null;this.records=[];} PerformanceObserver.prototype.observe=function(o){this.types=(o&&o.entryTypes)||null;if(observers.indexOf(this)<0)observers.push(this);};PerformanceObserver.prototype.disconnect=function(){var i=observers.indexOf(this);if(i>=0)observers.splice(i,1);this.records=[];};PerformanceObserver.prototype.takeRecords=function(){var records=this.records;this.records=[];return records;};
  function histogram(){var a=[],last=0;function q(n){if(!a.length)return 0;var b=a.slice().sort(function(x,y){return x-y;}),i=Math.min(b.length-1,Math.max(0,Math.ceil(n*b.length)-1));return b[i];}function stats(){return{min:a.length?Math.min.apply(Math,a):0,max:a.length?Math.max.apply(Math,a):0,mean:a.length?a.reduce(function(x,y){return x+y;},0)/a.length:0,count:a.length};}return{record:function(v){v=Number(v);if(isFinite(v)&&v>=0)a.push(v);},reset:function(){a=[];last=0;},delta:function(){var d=a.slice(last),h=histogram(),i;for(i=0;i<d.length;i++)h.record(d[i]);last=a.length;return h;},add:function(other){var v=Number(other);if(isFinite(v)&&v>=0)a.push(v);else if(other&&typeof other.length==='number')for(var i=0;i<other.length;i++)this.record(other[i]);return this;},exceeds:function(v){v=Number(v);return a.filter(function(x){return x>v;}).length;},percentile:function(n){return q(Number(n)/100);},percentiles:function(){var r={},i;for(i=1;i<=100;i++)r[i]=q(i/100);return r;},get min(){return stats().min;},get max(){return stats().max;},get mean(){return stats().mean;},get count(){return a.length;},get stddev(){if(!a.length)return 0;var m=this.mean;return Math.sqrt(a.reduce(function(s,x){return s+(x-m)*(x-m);},0)/a.length);}};}
  function timerify(fn){if(typeof fn!=='function')throw new TypeError('fn must be a function');return function(){var self=this,args=arguments,s=now(),r;try{r=fn.apply(self,args);}catch(e){add(fn.name||'','function',s,now()-s);throw e;}if(r&&typeof r.then==='function'){return r.then(function(v){add(fn.name||'','function',s,now()-s);return v;},function(e){add(fn.name||'','function',s,now()-s);throw e;});}add(fn.name||'','function',s,now()-s);return r;};}
  function elu(){return{idle:0,active:0,utilization:0};} function monitor(options){options=options||{};var h=histogram(),resolution=Math.max(1,Number(options.resolution)||10),id=null,last=Date.now();function tick(){var t=Date.now(),delay=Math.max(0,t-last-resolution);last=t;h.record(delay);}var m={enable:function(){if(id===null){last=Date.now();id=setInterval(tick,resolution);id&&id.unref&&id.unref();}return this;},disable:function(){if(id!==null){clearInterval(id);id=null;}return this;},start:function(){return this.enable();},stop:function(){return this.disable();},reset:function(){h.reset();last=Date.now();return this;},delta:function(){return h.delta();},get min(){return h.min;},get max(){return h.max;},get mean(){return h.mean;},get stddev(){return h.stddev;},exceeds:function(v){return h.exceeds(v);},get count(){return h.count;},percentile:function(n){return h.percentile(n);},percentiles:function(){return h.percentiles();}};return m;}
  return{performance:performance,PerformanceObserver:PerformanceObserver,PerformanceEntry:PerformanceEntry,PerformanceResourceTiming:PerformanceResourceTiming,PerformanceMark:PerformanceEntry,PerformanceMeasure:PerformanceEntry,monitorEventLoopDelay:monitor,createHistogram:histogram,constants:{NODE_PERFORMANCE_GC:1,NODE_PERFORMANCE_GC_MAJOR:4,NODE_PERFORMANCE_GC_MINOR:1,NODE_PERFORMANCE_GC_INCREMENTAL:8,NODE_PERFORMANCE_GC_WEAKCB:16},timerify:timerify,eventLoopUtilization:elu};
})