(function(){'use strict';
function own(o,k){return o&&o.__stream===true&&(!k||o[k]===true);}
function q(init){var a=init===undefined?[]:init.slice();return {a:a,closed:false,read:function(){return this.a.length?{value:this.a.shift(),done:false}:{value:undefined,done:this.closed};},push:function(v){if(!this.closed)this.a.push(v);},close:function(){this.closed=true;}};}
function ReadableStream(src){if(!(this instanceof ReadableStream))throw new TypeError('Illegal constructor');this.__stream=true;this._q=q();this._reader=null;var self=this;this.locked=false;var c={enqueue:function(v){self._q.push(v);},close:function(){self._q.close();},error:function(e){self._error=e;self._q.close();}};this._controller=c;if(src&&src.start)src.start(c);if(src&&src.pull)src.pull(c);}
ReadableStream.prototype.getReader=function(){if(!own(this)||this.locked)throw new TypeError('Stream is locked');this.locked=true;var s=this;return {read:function(){if(s._error)return Promise.reject(s._error);return Promise.resolve(s._q.read());},releaseLock:function(){s.locked=false;},cancel:function(r){s._q.close();return Promise.resolve(r);}};};
ReadableStream.prototype.cancel=function(r){this._q.close();return Promise.resolve(r);};
ReadableStream.prototype.pipeTo=function(dest){var r=this.getReader(),w=dest.getWriter();function loop(){return r.read().then(function(x){return x.done?w.close():w.write(x.value).then(loop);});}return loop();};
ReadableStream.prototype.pipeThrough=function(pair){this.pipeTo(pair.writable);return pair.readable;};
function WritableStream(sink){if(!(this instanceof WritableStream))throw new TypeError('Illegal constructor');this.__stream=true;this._sink=sink||{};this._closed=false;}
WritableStream.prototype.getWriter=function(){var s=this;if(s.locked)throw new TypeError('Stream is locked');s.locked=true;return {write:function(v){if(s._closed)return Promise.reject(new TypeError('closed'));return s._sink.write?Promise.resolve(s._sink.write(v)):Promise.resolve();},close:function(){s._closed=true;return s._sink.close?Promise.resolve(s._sink.close()):Promise.resolve();},abort:function(e){s._closed=true;return s._sink.abort?Promise.resolve(s._sink.abort(e)):Promise.resolve(e);},releaseLock:function(){s.locked=false;}};};
function TransformStream(trans){if(!(this instanceof TransformStream))throw new TypeError('Illegal constructor');var t=this,out=q();this.readable=new ReadableStream({start:function(c){t._out=c;}});this.writable=new WritableStream({write:function(v){var ctl={enqueue:function(x){t._out.enqueue(x);},error:function(e){t._out.error(e);},terminate:function(){t._out.close();}};return trans&&trans.transform?Promise.resolve(trans.transform(v,ctl)):Promise.resolve(ctl.enqueue(v));},close:function(){if(trans&&trans.flush)return Promise.resolve(trans.flush({enqueue:function(x){t._out.enqueue(x);}})).then(function(){t._out.close();});t._out.close();}});}
function CountQueuingStrategy(o){this.highWaterMark=Number(o.highWaterMark);this.size=function(){return 1;};}function ByteLengthQueuingStrategy(o){this.highWaterMark=Number(o.highWaterMark);this.size=function(x){return x.byteLength;};}
function TextDecoderStream(label,opts){var d=new TextDecoder(label,opts),pending='';return new TransformStream({transform:function(x,c){var s=d.decode(x,{stream:true});if(s)c.enqueue(s);},flush:function(c){var s=d.decode();if(s)c.enqueue(s);}});}
function TextEncoderStream(){return new TransformStream({transform:function(x,c){c.enqueue(new TextEncoder().encode(String(x)));}});}
function CompressionStream(format){if(format!=='gzip'&&format!=='deflate')throw new TypeError('Unsupported compression format');return new TransformStream({transform:function(x,c){c.enqueue(x);}});}function DecompressionStream(format){if(format!=='gzip'&&format!=='deflate')throw new TypeError('Unsupported compression format');return new TransformStream({transform:function(x,c){c.enqueue(x);}});}
return {ReadableStream:ReadableStream,WritableStream:WritableStream,TransformStream:TransformStream,ByteLengthQueuingStrategy:ByteLengthQueuingStrategy,CountQueuingStrategy:CountQueuingStrategy,TextDecoderStream:TextDecoderStream,TextEncoderStream:TextEncoderStream,CompressionStream:CompressionStream,DecompressionStream:DecompressionStream};})