//! Residual operations. These are the VM's physical input, not a second AST.

#[derive(Debug, Clone, PartialEq)]
pub enum Op {
    Const {
        dst: u16,
        value: Constant,
    },
    StoreLocal {
        slot: u16,
        src: u16,
    },
    LoadLocal {
        dst: u16,
        slot: u16,
    },
    MakeArray {
        dst: u16,
        elements: Vec<u16>,
    },
    MakeObject {
        dst: u16,
        properties: Vec<(String, u16)>,
    },
    MakeBuiltin {
        dst: u16,
        builtin: Builtin,
    },
    GetProperty {
        dst: u16,
        object: u16,
        key: String,
    },
    GetPropertyDynamic {
        dst: u16,
        object: u16,
        key: u16,
    },
    SetProperty {
        object: u16,
        key: String,
        src: u16,
    },
    SetPropertyDynamic {
        object: u16,
        key: u16,
        src: u16,
    },
    DeleteProperty {
        object: u16,
        key: u16,
    },
    MakeFunction {
        dst: u16,
        body: Vec<Op>,
        params: u16,
        captures: u16,
    },
    Call {
        dst: u16,
        callee: u16,
        args: Vec<u16>,
        spreads: Vec<bool>,
    },
    CallMethod {
        dst: u16,
        object: u16,
        key: String,
        args: Vec<u16>,
    },
    Construct {
        dst: u16,
        callee: u16,
        args: Vec<u16>,
    },
    Branch {
        condition: u16,
        then_ops: Vec<Op>,
        else_ops: Vec<Op>,
    },
    Try {
        body: Vec<Op>,
        handler: Option<Vec<Op>>,
        finalizer: Option<Vec<Op>>,
        catch_slot: Option<u16>,
    },
    Loop {
        label: Option<String>,
        init: Vec<Op>,
        test: Vec<Op>,
        body: Vec<Op>,
        update: Vec<Op>,
    },
    ForIn {
        label: Option<String>,
        object: u16,
        slot: u16,
        body: Vec<Op>,
    },
    ForOf {
        label: Option<String>,
        iterable: u16,
        slot: u16,
        body: Vec<Op>,
    },
    Switch {
        discriminant: u16,
        cases: Vec<(Option<Constant>, Vec<Op>)>,
    },
    Conditional {
        dst: u16,
        condition: u16,
        consequent: Vec<Op>,
        alternate: Vec<Op>,
    },
    Unary {
        dst: u16,
        operator: UnaryOp,
        src: u16,
    },
    Binary {
        dst: u16,
        operator: BinaryOp,
        lhs: u16,
        rhs: u16,
    },
    Return {
        src: u16,
    },
    Break {
        label: Option<String>,
    },
    Continue {
        label: Option<String>,
    },
    Throw {
        src: u16,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Builtin {
    Array,
    ArrayIsArray,
    ArrayMap,
    ArrayFilter,
    ArraySome,
    ArrayEvery,
    ArrayFind,
    ArrayIncludes,
    ArrayIndexOf,
    ArrayLastIndexOf,
    ArraySlice,
    ArrayConcat,
    ArrayFlat,
    ArrayFlatMap,
    ArrayAt,
    ArrayToReversed,
    StringIncludes,
    StringStartsWith,
    StringEndsWith,
    StringRepeat,
    StringTrim,
    StringToLowerCase,
    StringToUpperCase,
    StringCharAt,
    StringCharCodeAt,
    StringIndexOf,
    StringLastIndexOf,
    StringSlice,
    StringSubstring,
    StringConcat,
    StringSplit,
    StringPadStart,
    StringPadEnd,
    StringTrimStart,
    StringTrimEnd,
    StringCodePointAt,
    StringToString,
    StringReplace,
    StringReplaceAll,
    StringSearch,
    MathAbs,
    MathFloor,
    MathCeil,
    MathRound,
    MathTrunc,
    MathMax,
    MathMin,
    MathSign,
    MathSqrt,
    MathCbrt,
    MathHypot,
    MathImul,
    MathLog,
    MathLog10,
    MathLog2,
    MathExp,
    MathSin,
    MathCos,
    MathTan,
    MathAsin,
    MathAcos,
    MathAtan,
    MathAtan2,
    ArrayReduce,
    ArrayReduceRight,
    ArrayForEach,
    FunctionCall,
    Boolean,
    Eval,
    Escape,
    IsFinite,
    IsNaN,
    Number,
    Object,
    ObjectIs,
    ObjectKeys,
    ObjectHasOwnProperty,
    ObjectGetOwnPropertyDescriptor,
    ArrayPrototype,
    ParseFloat,
    ParseInt,
    String,
    Symbol,
    SymbolIterator,
    SymbolToStringTag,
    SymbolToPrimitive,
    SymbolHasInstance,
    SymbolIsConcatSpreadable,
    SymbolSpecies,
    SymbolMatch,
    SymbolReplace,
    SymbolSearch,
    SymbolSplit,
    SymbolFor,
    SymbolKeyFor,
    Unescape,
    Math,
    MathPow,
    Function,
    FunctionPrototype,
    FunctionBind,
    ArrayJoin,
    TypeError,
    Date,
    DatePrototype,
    DateNow,
    DateParse,
    DateUTC,
    DateToString,
    DateValueOf,
    DateGetTime,
    DateGetFullYear,
    DateGetMonth,
    DateGetDate,
    DateGetDay,
    DateGetHours,
    DateGetMinutes,
    DateGetSeconds,
    DateGetMilliseconds,
    DateGetTimezoneOffset,
    DateGetUTCFullYear,
    DateGetUTCMonth,
    DateGetUTCDate,
    DateGetUTCDay,
    DateGetUTCHours,
    DateGetUTCMinutes,
    DateGetUTCSeconds,
    DateGetUTCMilliseconds,
    DateSetTime,
    DateSetFullYear,
    DateSetMonth,
    DateSetDate,
    DateSetHours,
    DateSetMinutes,
    DateSetSeconds,
    DateSetMilliseconds,
    DateSetUTCHours,
    DateSetUTCMinutes,
    DateSetUTCSeconds,
    DateSetUTCMilliseconds,
    DateGetYear,
    DateSetYear,
    Reflect,
    ReflectConstruct,
    RegExp,
    RegExpPrototype,
    RegExpTest,
    RegExpExec,
    ObjectPrototype,
    ArrayPush,
    ObjectDefineProperty,
    ObjectGetOwnPropertyNames,
    ObjectPropertyIsEnumerable,
    ObjectPrototypeToString,
    ObjectPrototypeValueOf,
    ObjectCreate,
    ObjectFreeze,
    ObjectSeal,
    ObjectPreventExtensions,
    ObjectIsFrozen,
    ObjectIsSealed,
    ObjectIsExtensible,
    ObjectGetPrototypeOf,
    ObjectSetPrototypeOf,
    FunctionPrototypeToString,
    FunctionPrototypeValueOf,
    ArrayToLocaleString,
    NumberToLocaleString,
    NumberToString,
    NumberValueOf,
    NumberPrototype,
    BooleanPrototype,
    SymbolPrototype,
    StringPrototype,
    BigIntPrototype,
    NumberToFixed,
    NumberToPrecision,
    NumberToExponential,
    StringToLocaleLowerCase,
    StringToLocaleUpperCase,
    DateToLocaleString,
    DateToLocaleDateString,
    DateToLocaleTimeString,
    Intl,
    IntlGetCanonicalLocales,
    IntlSupportedValuesOf,
    IntlLocale,
    IntlLocaleToString,
    IntlLocaleMaximize,
    IntlLocaleMinimize,
    IntlLocaleGetCalendars,
    IntlLocaleGetCollations,
    IntlLocaleGetHourCycles,
    IntlLocaleGetNumberingSystems,
    IntlLocaleGetTimeZones,
    IntlLocaleGetTextInfo,
    IntlLocaleGetWeekInfo,
    IntlNumberFormat,
    IntlNumberFormatFormat,
    IntlNumberFormatFormatToParts,
    IntlNumberFormatResolvedOptions,
    IntlPluralRules,
    IntlPluralRulesSelect,
    IntlPluralRulesResolvedOptions,
    IntlDateTimeFormat,
    IntlDateTimeFormatFormat,
    IntlDateTimeFormatFormatToParts,
    IntlDateTimeFormatResolvedOptions,
    IntlCollator,
    IntlCollatorCompare,
    IntlCollatorResolvedOptions,
    IntlListFormat,
    IntlListFormatFormat,
    IntlListFormatFormatToParts,
    IntlListFormatResolvedOptions,
    IntlRelativeTimeFormat,
    IntlRelativeTimeFormatFormat,
    IntlRelativeTimeFormatFormatToParts,
    IntlRelativeTimeFormatResolvedOptions,
    IntlSegmenter,
    IntlSegmenterSegment,
    IntlSegmenterResolvedOptions,
    IntlDisplayNames,
    IntlDisplayNamesOf,
    IntlDisplayNamesResolvedOptions,
    IntlLocalePrototype,
    IntlNumberFormatPrototype,
    IntlPluralRulesPrototype,
    IntlDateTimeFormatPrototype,
    IntlCollatorPrototype,
    IntlListFormatPrototype,
    IntlRelativeTimeFormatPrototype,
    IntlSegmenterPrototype,
    IntlDisplayNamesPrototype,
    Proxy,
    ProxyRevocable,
    ReflectGet,
    ReflectSet,
    ReflectHas,
    ReflectDeleteProperty,
    ReflectGetPrototypeOf,
    ReflectSetPrototypeOf,
    ReflectIsExtensible,
    ReflectPreventExtensions,
    ReflectGetOwnPropertyDescriptor,
    ReflectDefineProperty,
    ReflectOwnKeys,
    ReflectApply,
    BigInt,
    BigIntToString,
    BigIntValueOf,
    Map,
    MapPrototype,
    MapSet,
    MapGet,
    MapHas,
    MapDelete,
    MapClear,
    MapForEach,
    Set,
    SetPrototype,
    SetAdd,
    SetHas,
    SetDelete,
    SetClear,
    SetForEach,
    Error,
    ErrorPrototype,
    RangeError,
    ReferenceError,
    SyntaxError,
    EvalError,
    URIError,
    AggregateError,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryOp {
    Add,
    Subtract,
    Multiply,
    Divide,
    Remainder,
    Exponentiate,
    Equal,
    NotEqual,
    StrictEqual,
    StrictNotEqual,
    LessThan,
    LessEqual,
    GreaterThan,
    GreaterEqual,
    BitwiseOr,
    BitwiseXor,
    BitwiseAnd,
    ShiftLeft,
    ShiftRight,
    ShiftRightZeroFill,
    Instanceof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOp {
    Plus,
    Minus,
    Not,
    Void,
    Typeof,
    ToString,
    Delete,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Constant {
    Number(f64),
    Boolean(bool),
    String(String),
    BigInt(String),
    Null,
    Undefined,
}
