//! `fs` capability dispatch table — one arm per operation.

use crate::dispatch_handlers::CallHandler;
use crate::modules::{fs_async, fs_promises, fs_stats, fs_sync};
use crate::registry::*;

pub fn fs_dispatch(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_READFILE => fs_async::read_file,
        CAP_FS_WRITEFILE => fs_async::write_file,
        CAP_FS_STAT => fs_async::stat,
        CAP_FS_READDIR => fs_async::readdir,
        CAP_FS_EXISTS => fs_async::exists,
        CAP_FS_MKDIR => fs_async::mkdir,
        CAP_FS_UNLINK => fs_async::unlink,
        CAP_FS_READFILESYNC => fs_sync::read_file_sync,
        CAP_FS_WRITEFILESYNC => fs_sync::write_file_sync,
        CAP_FS_STATSYNC => fs_sync::stat_sync,
        CAP_FS_READDIRSYNC => fs_sync::readdir_sync,
        CAP_FS_EXISTSSYNC => fs_sync::exists_sync,
        CAP_FS_REALSYNC => fs_sync::realpath_sync,
        CAP_FS_WATCH => crate::modules::fs::validate_watch_options,
        CAP_FS_WATCH_CLOSE => crate::modules::fs::close_watch,
        CAP_FS_READSTREAM => crate::modules::fs::validate_stream_options,
        CAP_FS_WRITESTREAM => crate::modules::fs::validate_stream_options,
        CAP_FS_CREATE_READSTREAM => crate::modules::fs::create_read_stream,
        CAP_FS_READSTREAM_OPEN => crate::modules::fs::read_stream_open,
        CAP_FS_OPEN => crate::modules::fs::open,
        CAP_FS_OPENDIR => crate::modules::fs::validate_directory_options,
        CAP_FS_OPENDIRSYNC => crate::modules::fs::validate_directory_options,
        CAP_FS_OPENSYNC => crate::modules::fs::open_sync,
        CAP_FS_CLOSESYNC => crate::modules::fs::close_sync,
        CAP_FS_READSYNC => crate::modules::fs::read_sync,
        CAP_FS_WRITESYNC => crate::modules::fs::write_sync,
        CAP_FS_READ => crate::modules::fs::read,
        CAP_FS_WRITE => crate::modules::fs::write,
        CAP_FS_FSTAT_SYNC => crate::modules::fs::fstat_sync,
        CAP_FS_FTRUNCATE_SYNC => crate::modules::fs::ftruncate_sync,
        CAP_FS_FSYNC_SYNC => crate::modules::fs::fsync_sync,
        CAP_FS_FDATASYNC_SYNC => crate::modules::fs::fsync_sync,
        CAP_FSP_OPEN => crate::modules::fs::promises_open,
        CAP_FS_HANDLE_READ => crate::modules::fs::file_handle_read,
        CAP_FS_HANDLE_CLOSE => crate::modules::fs::file_handle_close,
        CAP_FS_HANDLE_WRITE => crate::modules::fs::file_handle_write,
        CAP_FS_CLOSE => crate::modules::fs::close,
        CAP_FS_HANDLE_READFILE => crate::modules::fs::file_handle_read_file,
        CAP_FS_READSTREAM_CLOSE => crate::modules::fs::read_stream_close,
        CAP_FS_READSTREAM_DESTROY => crate::modules::fs::read_stream_destroy,
        _ => return fs_dispatch_more(cap),
    })
}

fn fs_dispatch_more(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_LSTAT => fs_async::lstat,
        CAP_FS_ACCESS => fs_async::access,
        CAP_FS_RMDIR => fs_async::rmdir,
        CAP_FS_RM => fs_async::rm,
        CAP_FS_RENAME => fs_async::rename,
        CAP_FS_APPENDFILE => fs_async::append_file,
        CAP_FS_COPYFILE => fs_async::copy_file,
        CAP_FS_MKDTEMP => fs_async::mkdtemp,
        CAP_FS_READLINK => fs_async::readlink,
        CAP_FS_CHMOD => fs_async::chmod,
        CAP_FS_TRUNCATE => fs_async::truncate,
        CAP_FS_LSTATSYNC => fs_sync::lstat_sync,
        CAP_FS_ACCESSSYNC => fs_sync::access_sync,
        CAP_FS_RMDIRSYNC => fs_sync::rmdir_sync,
        CAP_FS_RMSYNC => fs_sync::rm_sync,
        CAP_FS_RENAMESYNC => fs_sync::rename_sync,
        CAP_FS_APPENDFILESYNC => fs_sync::append_file_sync,
        CAP_FS_COPYFILESYNC => fs_sync::copy_file_sync,
        CAP_FS_MKDTEMPSYNC => fs_sync::mkdtemp_sync,
        CAP_FS_READLINKSYNC => fs_sync::readlink_sync,
        CAP_FS_CHMODSYNC => fs_sync::chmod_sync,
        CAP_FS_TRUNCATESYNC => fs_sync::truncate_sync,
        CAP_FS_MKDIRSYNC => fs_sync::mkdir_sync,
        CAP_FS_UNLINKSYNC => fs_sync::unlink_sync,
        CAP_FS_SYMLINKSYNC => fs_sync::symlink_sync,
        CAP_FS_STAT_ISFILE => fs_stats::is_file,
        CAP_FS_STAT_ISDIR => fs_stats::is_dir,
        CAP_FS_STAT_ISSYMLINK => fs_stats::is_symlink,
        CAP_FS_STAT_ISBLOCK => fs_stats::is_block,
        CAP_FS_STAT_ISCHAR => fs_stats::is_char,
        CAP_FS_STAT_ISFIFO => fs_stats::is_fifo,
        CAP_FS_STAT_ISSOCKET => fs_stats::is_socket,
        _ => return fs_dispatch_promises(cap),
    })
}

fn fs_dispatch_promises(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_REALPATH => fs_async::realpath,
        CAP_FSP_READFILE => fs_promises::read_file,
        CAP_FSP_WRITEFILE => fs_promises::write_file,
        CAP_FSP_APPENDFILE => fs_promises::append_file,
        CAP_FSP_STAT => fs_promises::stat,
        CAP_FSP_LSTAT => fs_promises::lstat,
        CAP_FSP_READDIR => fs_promises::readdir,
        CAP_FSP_MKDIR => fs_promises::mkdir,
        CAP_FSP_UNLINK => fs_promises::unlink,
        CAP_FSP_RMDIR => fs_promises::rmdir,
        CAP_FSP_RM => fs_promises::rm,
        CAP_FSP_RENAME => fs_promises::rename,
        CAP_FSP_COPYFILE => fs_promises::copy_file,
        CAP_FSP_ACCESS => fs_promises::access,
        CAP_FSP_MKDTEMP => fs_promises::mkdtemp,
        CAP_FSP_READLINK => fs_promises::readlink,
        CAP_FSP_CHMOD => fs_promises::chmod,
        CAP_FSP_TRUNCATE => fs_promises::truncate,
        CAP_FSP_REALPATH => fs_promises::realpath,
        _ => return crate::dispatch::assert_dispatch(cap),
    })
}
