//! `fs` capability dispatch table — one arm per operation.

use crate::dispatch_handlers::CallHandler;
use crate::modules::{fs_async, fs_promises, fs_stats, fs_sync};
use crate::registry::*;

pub fn fs_dispatch(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_READFILE => fs_async::read_file,
        CAP_FS_WRITEFILE => fs_async::write_file,
        CAP_FS_STAT => fs_async::stat,
        CAP_FS_READDIR => fs_async::readdir,
        CAP_FS_EXISTS => fs_async::exists,
        CAP_FS_MKDIR => fs_async::mkdir,
        CAP_FS_UNLINK => fs_async::unlink,
        CAP_FS_READFILESYNC => fs_sync::read_file_sync,
        CAP_FS_WRITEFILESYNC => fs_sync::write_file_sync,
        CAP_FS_STATSYNC => fs_sync::stat_sync,
        CAP_FS_READDIRSYNC => fs_sync::readdir_sync,
        CAP_FS_EXISTSSYNC => fs_sync::exists_sync,
        CAP_FS_REALSYNC => fs_sync::realpath_sync,
        CAP_FS_REALSYNC_NATIVE => fs_sync::realpath_native_sync,
        CAP_FS_OPENASBLOB => crate::modules::fs::open_as_blob,
        CAP_FS_WATCH => crate::modules::fs::validate_watch_options,
        CAP_FS_WATCH_CLOSE => crate::modules::fs::close_watch,
        CAP_FS_WATCHFILE => crate::modules::fs::watch_file,
        CAP_FS_UNWATCHFILE => crate::modules::fs::unwatch_file,
        // `ReadStream(...)` is callable in Node in addition to being
        // constructable; both forms share the real Rust stream state machine.
        CAP_FS_READSTREAM => crate::modules::fs::create_read_stream,
        CAP_FS_WRITESTREAM => crate::modules::fs::validate_write_stream_options,
        CAP_FS_CREATE_READSTREAM => crate::modules::fs::create_read_stream_factory,
        CAP_FS_READSTREAM_OPEN => crate::modules::fs::read_stream_open,
        CAP_FS_OPEN => crate::modules::fs::open,
        CAP_FS_OPENDIR => crate::modules::fs::opendir,
        CAP_FS_OPENDIRSYNC => crate::modules::fs::opendir_sync,
        CAP_FS_STATFS => crate::modules::fs::statfs,
        CAP_FS_STATFSSYNC => crate::modules::fs::statfs_sync,
        CAP_FS_STATS => crate::modules::fs::stats_call,
        CAP_FS_OPENSYNC => crate::modules::fs::open_sync,
        CAP_FS_CLOSESYNC => crate::modules::fs::close_sync,
        CAP_FS_READSYNC => crate::modules::fs::read_sync,
        CAP_FS_WRITESYNC => crate::modules::fs::write_sync,
        CAP_FS_READ => crate::modules::fs::read,
        CAP_FS_WRITE => crate::modules::fs::write,
        CAP_FS_FSTAT => crate::modules::fs::fstat,
        CAP_FS_FTRUNCATE => crate::modules::fs::ftruncate,
        CAP_FS_FCHMOD => crate::modules::fs::fchmod,
        CAP_FS_FCHOWN => crate::modules::fs::fchown,
        CAP_FS_FUTIMES => crate::modules::fs::futimes,
        CAP_FS_FDATASYNC => crate::modules::fs::fdatasync,
        CAP_FS_READV => crate::modules::fs::readv,
        CAP_FS_WRITEV => crate::modules::fs::writev,
        CAP_FS_FSTAT_SYNC => crate::modules::fs::fstat_sync,
        CAP_FS_FTRUNCATE_SYNC => crate::modules::fs::ftruncate_sync,
        CAP_FS_FSYNC_SYNC => crate::modules::fs::fsync_sync,
        CAP_FS_FSYNC => crate::modules::fs::fsync,
        CAP_FS_WRITE_STREAM_WRITE => crate::modules::fs::write_stream_write,
        CAP_FS_WRITE_STREAM_OPEN => crate::modules::fs::write_stream_open,
        CAP_FS_WRITE_STREAM_CLOSE => crate::modules::fs::write_stream_close,
        CAP_FS_DIR_READ_SYNC => crate::modules::fs::dir_read_sync,
        CAP_FS_DIR_READ => crate::modules::fs::dir_read,
        CAP_FS_DIR_CLOSE_SYNC => crate::modules::fs::dir_close_sync,
        CAP_FS_DIR_CLOSE => crate::modules::fs::dir_close,
        CAP_FS_DIR_PATH_GET => crate::modules::fs::dir_path_get,
        CAP_FS_FDATASYNC_SYNC => crate::modules::fs::fdatasync_sync,
        CAP_FSP_OPEN => crate::modules::fs::promises_open,
        CAP_FS_HANDLE_READ => crate::modules::fs::file_handle_read,
        CAP_FS_HANDLE_CLOSE => crate::modules::fs::file_handle_close,
        CAP_FS_HANDLE_WRITE => crate::modules::fs::file_handle_write,
        CAP_FS_CLOSE => crate::modules::fs::close,
        CAP_FS_CP => crate::dispatch_handlers::fs_cp,
        CAP_FS_CP_SYNC => crate::dispatch_handlers::fs_cp_sync,
        CAP_FSP_CP => crate::dispatch_handlers::fs_cp_promise,
        CAP_FS_CP_FILTER_FULFILLED => crate::modules::fs::fs_cp_filter_fulfilled,
        CAP_FS_CP_FILTER_REJECTED => crate::modules::fs::fs_cp_filter_rejected,
        CAP_FS_GLOB => crate::modules::fs::glob,
        CAP_FS_GLOB_SYNC => crate::modules::fs::glob_sync,
        CAP_FS_HANDLE_READFILE => crate::modules::fs::file_handle_read_file,
        CAP_FS_HANDLE_FD => crate::modules::fs::file_handle_fd,
        CAP_FS_READSTREAM_CLOSE => crate::modules::fs::read_stream_close,
        CAP_FS_READSTREAM_DESTROY => crate::modules::fs::read_stream_destroy,
        _ => return fs_dispatch_more(cap),
    })
}

fn fs_dispatch_more(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_LSTAT => fs_async::lstat,
        CAP_FS_ACCESS => fs_async::access,
        CAP_FS_RMDIR => fs_async::rmdir,
        CAP_FS_RM => fs_async::rm,
        CAP_FS_RENAME => fs_async::rename,
        CAP_FS_APPENDFILE => fs_async::append_file,
        CAP_FS_COPYFILE => fs_async::copy_file,
        CAP_FS_MKDTEMP => fs_async::mkdtemp,
        CAP_FS_READLINK => fs_async::readlink,
        CAP_FS_CHMOD => fs_async::chmod,
        CAP_FS_TRUNCATE => fs_async::truncate,
        CAP_FS_LSTATSYNC => fs_sync::lstat_sync,
        CAP_FS_ACCESSSYNC => fs_sync::access_sync,
        CAP_FS_RMDIRSYNC => fs_sync::rmdir_sync,
        CAP_FS_RMSYNC => fs_sync::rm_sync,
        CAP_FS_RENAMESYNC => fs_sync::rename_sync,
        CAP_FS_APPENDFILESYNC => fs_sync::append_file_sync,
        CAP_FS_COPYFILESYNC => fs_sync::copy_file_sync,
        CAP_FS_MKDTEMPSYNC => fs_sync::mkdtemp_sync,
        CAP_FS_READLINKSYNC => fs_sync::readlink_sync,
        CAP_FS_CHMODSYNC => fs_sync::chmod_sync,
        CAP_FS_LCHMODSYNC => fs_sync::lchmod_sync,
        CAP_FS_TRUNCATESYNC => fs_sync::truncate_sync,
        CAP_FS_MKDIRSYNC => fs_sync::mkdir_sync,
        CAP_FS_UNLINKSYNC => fs_sync::unlink_sync,
        CAP_FS_SYMLINKSYNC => fs_sync::symlink_sync,
        CAP_FS_LINKSYNC => fs_sync::link_sync,
        CAP_FS_LINK => fs_async::link,
        CAP_FS_SYMLINK => fs_async::symlink,
        CAP_FS_CHOWN => fs_async::chown,
        CAP_FS_LCHMOD => fs_async::lchmod,
        CAP_FS_LCHOWN => fs_async::lchown,
        CAP_FS_UTIMES => fs_async::utimes,
        CAP_FS_LUTIMES => fs_async::lutimes,
        CAP_FS_CHOWNSYNC => fs_sync::chown_sync,
        CAP_FS_LCHOWNSYNC => fs_sync::lchown_sync,
        CAP_FS_UTIMESSYNC => fs_sync::utimes_sync,
        CAP_FS_LUTIMESSYNC => fs_sync::lutimes_sync,
        CAP_FS_FCHMODSYNC => crate::modules::fs::fchmod_sync,
        CAP_FS_FCHOWNSYNC => crate::modules::fs::fchown_sync,
        CAP_FS_FUTIMESSYNC => crate::modules::fs::futimes_sync,
        CAP_FS_READVSYNC => crate::modules::fs::readv_sync,
        CAP_FS_WRITEVSYNC => crate::modules::fs::writev_sync,
        CAP_FS_STAT_ISFILE => fs_stats::is_file,
        CAP_FS_STAT_ISDIR => fs_stats::is_dir,
        CAP_FS_STAT_ISSYMLINK => fs_stats::is_symlink,
        CAP_FS_STAT_ISBLOCK => fs_stats::is_block,
        CAP_FS_STAT_ISCHAR => fs_stats::is_char,
        CAP_FS_STAT_ISFIFO => fs_stats::is_fifo,
        CAP_FS_STAT_ISSOCKET => fs_stats::is_socket,
        CAP_FS_TO_UNIX_TIMESTAMP => crate::modules::fs::to_unix_timestamp,
        _ => return fs_dispatch_promises(cap),
    })
}

fn fs_dispatch_promises(cap: u16) -> Option<CallHandler> {
    Some(match cap {
        CAP_FS_REALPATH => fs_async::realpath,
        CAP_FS_REALPATH_NATIVE => fs_async::realpath_native,
        CAP_FSP_READFILE => fs_promises::read_file,
        CAP_FSP_WRITEFILE => fs_promises::write_file,
        CAP_FSP_APPENDFILE => fs_promises::append_file,
        CAP_FSP_STAT => fs_promises::stat,
        CAP_FSP_LSTAT => fs_promises::lstat,
        CAP_FSP_READDIR => fs_promises::readdir,
        CAP_FSP_MKDIR => fs_promises::mkdir,
        CAP_FSP_UNLINK => fs_promises::unlink,
        CAP_FSP_RMDIR => fs_promises::rmdir,
        CAP_FSP_RM => fs_promises::rm,
        CAP_FSP_RENAME => fs_promises::rename,
        CAP_FSP_COPYFILE => fs_promises::copy_file,
        CAP_FSP_ACCESS => fs_promises::access,
        CAP_FSP_MKDTEMP => fs_promises::mkdtemp,
        CAP_FSP_READLINK => fs_promises::readlink,
        CAP_FSP_CHMOD => fs_promises::chmod,
        CAP_FSP_LCHMOD => fs_promises::lchmod,
        CAP_FSP_TRUNCATE => fs_promises::truncate,
        CAP_FSP_REALPATH => fs_promises::realpath,
        CAP_FSP_CHOWN => fs_promises::chown,
        CAP_FSP_LCHOWN => fs_promises::lchown,
        CAP_FSP_OPENDIR => fs_promises::opendir,
        CAP_FSP_SYMLINK => fs_promises::symlink,
        CAP_FSP_UTIMES => fs_promises::utimes,
        CAP_FSP_LUTIMES => fs_promises::lutimes,
        CAP_FSP_STATFS => fs_promises::statfs,
        CAP_FSP_LINK => fs_promises::link,
        _ => return crate::dispatch::assert_dispatch(cap),
    })
}
