fn require_crypto_module(name: &str) -> Option<Value> {
    if name == "node:crypto" || name == "crypto" {
            return Some(Value::object(vec![
                (
                    "createHash".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::CreateHash)),
                ),
                (
                    "hash".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoHashOneShot,
                    )),
                ),
                (
                    "createHmac".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateHmac,
                    )),
                ),
                (
                    "createSign".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateSign,
                    )),
                ),
                (
                    "createVerify".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateVerify,
                    )),
                ),
                (
                    "sign".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoSignDirect,
                    )),
                ),
                (
                    "verify".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoVerifyDirect,
                    )),
                ),
                (
                    "privateEncrypt".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoPrivateEncrypt,
                    )),
                ),
                (
                    "publicDecrypt".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoPublicDecrypt,
                    )),
                ),
                ("Certificate".into(), certificate_constructor()),
                (
                    "createPrivateKey".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreatePrivateKey,
                    )),
                ),
                (
                    "createPublicKey".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreatePublicKey,
                    )),
                ),
                (
                    "generateKeyPairSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGenerateKeyPairSync,
                    )),
                ),
                (
                    "generateKeySync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGenerateKeySync,
                    )),
                ),
                (
                    "diffieHellman".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoDiffieHellman,
                    )),
                ),
                (
                    "createCipheriv".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateCipheriv,
                    )),
                ),
                (
                    "createDecipheriv".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateCipheriv,
                    )),
                ),
                (
                    "Cipheriv".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                (
                    "Decipheriv".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                (
                    "getHashes".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetHashes,
                    )),
                ),
                (
                    "getCiphers".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetCiphers,
                    )),
                ),
                (
                    "getCipherInfo".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetCipherInfo,
                    )),
                ),
                (
                    "getCurves".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetCurves,
                    )),
                ),
                (
                    "Hash".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                (
                    "Hmac".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                (
                    "Sign".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                (
                    "Verify".into(),
                    Value::Builtin(quench_runtime::ops::Builtin::Object),
                ),
                ("DiffieHellmanGroup".into(), dh_group_constructor()),
                ("DiffieHellman".into(), dh_constructor()),
                ("ECDH".into(), ecdh_constructor()),
                (
                    "createECDH".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateEcdh,
                    )),
                ),
                (
                    "constants".into(),
                    quench_runtime::host_api::object(vec![
                        ("RSA_PKCS1_PADDING".into(), Value::Number(1.0)),
                        ("RSA_PKCS1_PSS_PADDING".into(), Value::Number(6.0)),
                    ]),
                ),
                (
                    "getDiffieHellman".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetDiffieHellman,
                    )),
                ),
                (
                    "createDiffieHellman".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoCreateDiffieHellman,
                    )),
                ),
                (
                    "createDiffieHellmanGroup".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoGetDiffieHellman,
                    )),
                ),
                (
                    "randomBytes".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoRandomBytes,
                    )),
                ),
                (
                    "randomFillSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoRandomFillSync,
                    )),
                ),
                (
                    "pbkdf2Sync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::CryptoPbkdf2Sync,
                    )),
                ),
                (
                    "pbkdf2".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::CryptoPbkdf2)),
                ),
            ]));
    }
    None
}
