fn fs_promises_surface() -> Value {
    Value::object(vec![
        (
            "cp".into(),
            crate::host::capability(crate::registry::SPEC_FS_CP),
        ),
        (
            "writeFile".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsWritePromise)),
        ),
        (
            "readFile".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadPromise)),
        ),
        (
            "appendFile".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsAppendPromise)),
        ),
        (
            "readdir".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsReaddirPromise)),
        ),
        (
            "unlink".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsUnlinkPromise)),
        ),
        (
            "opendir".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpendirPromise)),
        ),
        (
            "readv".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadvPromise)),
        ),
        (
            "link".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsLinkPromise)),
        ),
        (
            "stat".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsStatPromise)),
        ),
        (
            "utimes".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsUtimesPromise)),
        ),
        (
            "open".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpenPromise)),
        ),
        (
            "mkdir".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdirPromise)),
        ),
        (
            "rm".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsRmPromise)),
        ),
        (
            "rename".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsRenamePromise)),
        ),
        (
            "access".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsAccessPromise)),
        ),
        (
            "chmod".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsChmodPromise)),
        ),
        (
            "readlink".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadlinkPromise)),
        ),
        (
            "realpath".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsRealpathPromise)),
        ),
        (
            "symlink".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsSymlinkPromise)),
        ),
        (
            "mkdtemp".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdtempPromise)),
        ),
        (
            "lstat".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsLstatPromise)),
        ),
        (
            "truncate".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsTruncatePromise)),
        ),
        (
            "copyFile".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsCopyFilePromise)),
        ),
        (
            "glob".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsGlob)),
        ),
        (
            "globSync".into(),
            capability_function(HostCapabilityKind::Custom(CapabilityName::FsGlobSync)),
        ),
    ])
}

fn require_fs_module(name: &str) -> Option<Value> {
    if name == "node:fs" || name == "fs" {
            let realpath_sync = quench_runtime::execute::set_property(
                capability_function(HostCapabilityKind::Custom(CapabilityName::FsRealpathSync)),
                "native",
                capability_function(HostCapabilityKind::Custom(CapabilityName::FsRealpathSync)),
            );
            let module = Value::object(vec![
                (
                    "readFileSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::ReadFileSync)),
                ),
                (
                    "readSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadSyncFd)),
                ),
                (
                    "readvSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadvSync)),
                ),
                (
                    "writeFileSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsWriteFileSync,
                    )),
                ),
                (
                    "appendFileSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsAppendFileSync,
                    )),
                ),
                (
                    "appendFile".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsAppendBytes)),
                ),
                (
                    "accessSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsAccessSync)),
                ),
                (
                    "unlinkSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsUnlinkSync)),
                ),
                (
                    "unlink".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsUnlink)),
                ),
                (
                    "linkSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLinkSync)),
                ),
                (
                    "link".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLinkAsync)),
                ),
                (
                    "fsyncSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsFsyncSync)),
                ),
                (
                    "fdatasyncSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsFdatasyncSync,
                    )),
                ),
                (
                    "rmdirSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsRmdirSync)),
                ),
                (
                    "mkdtemp".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdtempAsync)),
                ),
                (
                    "mkdtempSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdtemp)),
                ),
                (
                    "realpath".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsRealpath)),
                ),
                (
                    "realpathSync".into(), realpath_sync),
                (
                    "openSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpenSync)),
                ),
                (
                    "closeSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsCloseSync)),
                ),
                (
                    "fchmod".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsFchmod)),
                ),
                (
                    "fchmodSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsFchmod)),
                ),
                (
                    "ftruncateSync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsFtruncateSync,
                    )),
                ),
                (
                    "fstatSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsFstatSync)),
                ),
                (
                    "statSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsStatSync)),
                ),
                (
                    "lstatSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLstatSync)),
                ),
                (
                    "symlink".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsSymlink)),
                ),
                (
                    "symlinkSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsSymlinkSync)),
                ),
                (
                    "readlink".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadlink)),
                ),
                (
                    "readlinkSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadlinkSync)),
                ),
                (
                    "stat".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsStatAsync)),
                ),
                (
                    "lstat".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLstatAsync)),
                ),
                (
                    "chmodSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsChmodSync)),
                ),
                (
                    "cpSync".into(),
                    crate::host::capability(crate::registry::SPEC_FS_CP_SYNC),
                ),
                (
                    "cp".into(),
                    crate::host::capability(crate::registry::SPEC_FS_CP),
                ),
                (
                    "mkdirSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdirSync)),
                ),
                (
                    "mkdir".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsMkdirAsync)),
                ),
                (
                    "_toUnixTimestamp".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsToUnixTimestamp,
                    )),
                ),
                (
                    "renameSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsRenameSync)),
                ),
                (
                    "rm".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsRm)),
                ),
                (
                    "rmSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsRmSync)),
                ),
                (
                    "utimesSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsUtimesSync)),
                ),
                (
                    "lutimesSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLutimesSync)),
                ),
                (
                    "utimes".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsUtimesAsync)),
                ),
                (
                    "lutimes".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsLutimesAsync)),
                ),
                (
                    "readdirSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReaddirSync)),
                ),
                (
                    "opendirSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpendirSync)),
                ),
                (
                    "access".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsAccessAsync)),
                ),
                (
                    "truncate".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsTruncateAsync,
                    )),
                ),
                (
                    "truncateSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsTruncateSync)),
                ),
                (
                    "constants".into(),
                    quench_runtime::host_api::object(vec![
                        ("\0prototype".into(), Value::Null),
                        ("O_RDONLY".into(), Value::Number(0.0)),
                        ("S_IFDIR".into(), Value::Number(0o40000 as f64)),
                        ("S_IRUSR".into(), Value::Number(0o400 as f64)),
                        ("S_IWUSR".into(), Value::Number(0o200 as f64)),
                        ("R_OK".into(), Value::Number(4.0)),
                        ("W_OK".into(), Value::Number(2.0)),
                        ("X_OK".into(), Value::Number(1.0)),
                        ("F_OK".into(), Value::Number(0.0)),
                        ("COPYFILE_EXCL".into(), Value::Number(1.0)),
                        ("COPYFILE_FICLONE".into(), Value::Number(2.0)),
                        ("COPYFILE_FICLONE_FORCE".into(), Value::Number(4.0)),
                        ("UV_FS_COPYFILE_EXCL".into(), Value::Number(1.0)),
                        ("UV_FS_COPYFILE_FICLONE".into(), Value::Number(2.0)),
                        ("UV_FS_COPYFILE_FICLONE_FORCE".into(), Value::Number(4.0)),
                    ]),
                ),
                (
                    "existsSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsExistsSync)),
                ),
                (
                    "exists".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsExists)),
                ),
                (
                    "writeFile".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsWriteAsync)),
                ),
                (
                    "readFile".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadAsync)),
                ),
                (
                    "read".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadFdAsync)),
                ),
                (
                    "readv".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReadvAsync)),
                ),
                (
                    "writeSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsWriteSyncFd)),
                ),
                (
                    "writevSync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsWritevSync)),
                ),
                (
                    "readdir".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsReaddirAsync)),
                ),
                (
                    "opendir".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpendirAsync)),
                ),
                (
                    "open".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsOpenAsync)),
                ),
                (
                    "fsync".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsFsyncAsync)),
                ),
                (
                    "fdatasync".into(),
                    capability_function(HostCapabilityKind::Custom(
                        CapabilityName::FsFdatasyncAsync,
                    )),
                ),
                (
                    "close".into(),
                    capability_function(HostCapabilityKind::Custom(CapabilityName::FsCloseAsync)),
                ),
                (
                    "promises".into(),
                    fs_promises_surface(),
                ),
            ]);
            return Some(module);
        }
        if name == "node:fs/promises" || name == "fs/promises" {
            return Some(fs_promises_surface());
        }
        if let Some(module) = require_crypto_module(name) {
            return Some(module);
    }
    None
}
