fn validate_catalog_declaration(declaration: &RegionDeclaration) {
    let byte_len = declaration
        .x86_bytes
        .len()
        .max(declaration.aarch64_bytes.len())
        .max(declaration.portable_bytes.len());
    validate_holes(declaration, byte_len, declaration.holes, "");
    validate_holes(
        declaration,
        declaration.aarch64_bytes.len(),
        declaration.aarch64_holes,
        "AArch64 ",
    );
    assert!(
        has_single_external_entry(declaration.entry, declaration.external_entries),
        "stencil {} has an external edge into its interior",
        declaration.name
    );
    if let Some(recipe) = rust_assembly_recipe(declaration) {
        assert!(
            recipe
                .bindings()
                .iter()
                .all(|binding| binding.valid_for(declaration.operations.len())),
            "stencil {} has an invalid physical operand binding",
            declaration.name
        );
        assert!(
            recipe
                .outputs()
                .iter()
                .all(|output| output.valid_for(declaration.operations.len())),
            "stencil {} has an invalid physical output destination",
            declaration.name
        );
    }
}

fn validate_holes(
    declaration: &RegionDeclaration,
    byte_len: usize,
    holes: &[(u16, usize, &'static str)],
    target: &str,
) {
    for (offset, width, _) in holes {
        assert!(
            usize::from(*offset) + *width <= byte_len,
            "stencil {} has an out-of-range {target}hole",
            declaration.name
        );
    }
}

fn stable_region_id(name: &str) -> u32 {
    name.bytes().fold(0x811c_9dc5, |hash, byte| {
        (hash ^ u32::from(byte)).wrapping_mul(0x0100_0193)
    })
}

fn assert_unique_region_ids(declarations: &[RegionDeclaration]) {
    let mut ids = std::collections::BTreeMap::new();
    for declaration in declarations {
        let id = stable_region_id(declaration.name);
        if let Some(previous) = ids.insert(id, declaration.name) {
            panic!("region ID collision: {previous} and {}", declaration.name);
        }
    }
}

fn has_single_external_entry(entry: u32, external_entries: &[u32]) -> bool {
    external_entries.len() == 1 && external_entries[0] == entry
}

/// Keep the build-time stencil catalog tied to the canonical data modules.
/// The generated bytes remain data; executable-memory effects are confined to
/// the runtime arena.
fn validate_stencil_declarations(declarations: &[RegionDeclaration]) {
    let facts = fs::read_to_string("src/stencil_fact.rs").expect("read stencil facts");
    let selector = fs::read_to_string("src/stencil_select.rs").expect("read stencil selector");
    let ir = fs::read_to_string("src/ir.rs").expect("read canonical opcode declaration");
    for required in ["RegionKey", "HoleKind", "PatchValues", "BoxingFact"] {
        assert!(facts.contains(required), "stencil facts missing {required}");
    }
    for required in [
        "select_stencil",
        "has_single_entry_point",
        "reduce_type_checks",
    ] {
        assert!(
            selector.contains(required),
            "stencil selector missing {required}"
        );
    }
    assert!(
        selector.contains("promotion_admitted"),
        "stencil promotion predicate missing"
    );
    for declaration in declarations {
        for operation in declaration.operations {
            assert!(
                ir.contains(&format!("{operation} =")),
                "region {} names unknown opcode {operation}",
                declaration.name
            );
        }
    }
    println!("cargo:rerun-if-changed=src/stencil_fact.rs");
    println!("cargo:rerun-if-changed=src/stencil_select.rs");
}

fn generate_op_names() {
    let source = fs::read_to_string("src/ops_op.rs").expect("read canonical Op declaration");
    let variants = extract_op_variants(&source);
    assert!(variants.len() >= 90, "incomplete Op variant extraction");
    let arms = variants
        .iter()
        .map(op_name_arm)
        .collect::<Vec<_>>()
        .join("\n");
    let generated = format!(
        "impl Op {{\n    pub const fn variant_name(&self) -> &'static str {{\n        match self {{\n{arms}\n        }}\n    }}\n}}\n"
    );
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(output.join("op_variant_name.rs"), generated).expect("write Op names");
    println!("cargo:rerun-if-changed=src/ops_op.rs");
}

fn extract_op_variants(source: &str) -> Vec<(&str, &str, Option<&str>)> {
    const PREFIX: &str = "    ";
    let body = source
        .split_once("pub enum Op {")
        .expect("Op declaration")
        .1;
    let mut variants = Vec::new();
    let mut cfg = None;
    for line in body.lines().take_while(|line| *line != "}") {
        let Some(rest) = line.strip_prefix(PREFIX) else {
            continue;
        };
        if rest.starts_with("#[cfg(") {
            cfg = Some(rest);
            continue;
        }
        if rest.starts_with(' ') {
            continue;
        }
        let Some(end) =
            rest.find(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        else {
            continue;
        };
        let name = &rest[..end];
        if !name.is_empty()
            && name
                .chars()
                .next()
                .is_some_and(|value| value.is_ascii_uppercase())
        {
            variants.push((name, rest, cfg.take()));
        }
    }
    variants
}

fn op_name_arm((name, declaration, cfg): &(&str, &str, Option<&str>)) -> String {
    let tail = declaration[name.len()..].trim_start();
    let pattern = if tail.starts_with('{') {
        format!("Self::{name} {{ .. }}")
    } else if tail.starts_with('(') {
        format!("Self::{name} (..)")
    } else {
        format!("Self::{name}")
    };
    let cfg = cfg.map_or(String::new(), |cfg| format!("            {cfg}\n"));
    format!("{cfg}            {pattern} => \"{name}\",")
}
