const LEAF_REGION_DECLARATIONS: &[RegionDeclaration] = &[
    RegionDeclaration {
        name: "loop",
        operations: &["Add", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_LOOP_BYTES,
        aarch64_bytes: &AARCH64_LOOP_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "property",
        operations: &["GetN"],
        abi: DeclAbi::PropertyGuard,
        // The physical entry validates live layout/metadata facts and loads
        // the admitted slot without repeating semantic key/descriptor scans.
        x86_bytes: &X86_PROPERTY_BYTES,
        aarch64_bytes: &AARCH64_PROPERTY_GUARD_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "prototype_property",
        operations: &["GetN"],
        abi: DeclAbi::PropertyGuard,
        x86_bytes: &[0xC3],
        aarch64_bytes: &AARCH64_PROTOTYPE_PROPERTY_GUARD_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "move",
        operations: &["Move"],
        abi: DeclAbi::TaggedWord,
        // A pure Move leaf copies one canonical tagged word.  RegisterFile
        // performs the retain/release edge after this raw load returns.
        x86_bytes: &X86_MOVE_BYTES,
        aarch64_bytes: &AARCH64_MOVE_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "fallthrough",
        operations: &["Add", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_FALLTHROUGH_BYTES,
        // AArch64 uses a direct B/imm26 branch to the aligned return tail;
        // x86 keeps its rel32 form. Both are patched only after the two pieces
        // have been placed in one arena.
        aarch64_bytes: &AARCH64_FALLTHROUGH_BYTES,
        portable_bytes: &[0xC3],
        holes: &[(5, 4, "Rel32")],
        aarch64_holes: &[(4, 4, "Branch26"), (8, 4, "Branch26")],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "subtract",
        operations: &["Sub", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_SUBTRACT_BYTES,
        aarch64_bytes: &AARCH64_SUBTRACT_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "multiply",
        operations: &["Mul", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_MULTIPLY_BYTES,
        aarch64_bytes: &AARCH64_MULTIPLY_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "divide",
        operations: &["Div", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_DIVIDE_BYTES,
        aarch64_bytes: &AARCH64_DIVIDE_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "add_const",
        operations: &["AddConst", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_ADD_CONST_BYTES,
        // ldr d1, #16; fadd d0, d0, d1; ret; padding; <literal f64>
        aarch64_bytes: &AARCH64_ADD_CONST_BYTES,
        portable_bytes: &[0xC3],
        holes: &[(13, 8, "Literal64")],
        aarch64_holes: &[(16, 8, "Literal64")],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_equal",
        // Numeric equality is safe only after both operands are proven
        // Numbers; all coercive/string/BigInt cases remain canonical Binary.
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_not_equal",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_NOT_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_NOT_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_equal_word",
        // Identity equality is valid only for non-string tagged values:
        // Bool/null/undefined and heap object identities. Numbers, I31 and
        // heap strings stay on the canonical comparison path.
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarWordPairBool,
        x86_bytes: &X86_WORD_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_WORD_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_not_equal_word",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarWordPairBool,
        x86_bytes: &X86_WORD_NOT_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_WORD_NOT_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_less",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_LESS_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_LESS_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_less_equal",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_LESS_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_LESS_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_greater",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_GREATER_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_GREATER_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "compare_greater_equal",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarBool,
        x86_bytes: &X86_COMPARE_GREATER_EQUAL_BYTES,
        aarch64_bytes: &AARCH64_COMPARE_GREATER_EQUAL_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "bitwise_and",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_BITWISE_AND_BYTES,
        aarch64_bytes: &AARCH64_BITWISE_AND_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "bitwise_or",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_BITWISE_OR_BYTES,
        aarch64_bytes: &AARCH64_BITWISE_OR_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "bitwise_xor",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_BITWISE_XOR_BYTES,
        aarch64_bytes: &AARCH64_BITWISE_XOR_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "shift_left",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_SHIFT_LEFT_BYTES,
        aarch64_bytes: &AARCH64_SHIFT_LEFT_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "shift_right",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_SHIFT_RIGHT_BYTES,
        aarch64_bytes: &AARCH64_SHIFT_RIGHT_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "shift_right_zero",
        operations: &["Binary", "Return"],
        abi: DeclAbi::ScalarU32,
        x86_bytes: &X86_SHIFT_RIGHT_ZERO_BYTES,
        aarch64_bytes: &AARCH64_SHIFT_RIGHT_ZERO_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "bitwise_not",
        operations: &["Unary", "Return"],
        abi: DeclAbi::ScalarI32,
        x86_bytes: &X86_BITWISE_NOT_BYTES,
        aarch64_bytes: &AARCH64_BITWISE_NOT_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "negate",
        operations: &["Unary", "Return"],
        abi: DeclAbi::Scalar,
        x86_bytes: &X86_NEGATE_BYTES,
        aarch64_bytes: &AARCH64_NEGATE_BYTES,
        portable_bytes: &[0xC3],
        holes: &[(16, 8, "Literal64")],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
];
