const LEAF_ASSEMBLY_DECLARATIONS: &[RegionDeclaration] = &[
    RegionDeclaration {
        name: "property",
        operations: &["GetN"],
        abi: DeclAbi::PropertyGuard,
        x86_bytes: &X86_PROPERTY_BYTES,
        aarch64_bytes: &AARCH64_PROPERTY_GUARD_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "prototype_property",
        operations: &["GetN"],
        abi: DeclAbi::PropertyGuard,
        x86_bytes: &[0xC3],
        aarch64_bytes: &AARCH64_PROTOTYPE_PROPERTY_GUARD_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "move",
        operations: &["Move"],
        abi: DeclAbi::TaggedWord,
        x86_bytes: &X86_MOVE_BYTES,
        aarch64_bytes: &AARCH64_MOVE_BYTES,
        portable_bytes: &[0xC3],
        holes: &[],
        aarch64_holes: &[],
        entry: 0,
        external_entries: &[0],
    },
    RegionDeclaration {
        name: "fallthrough",
        operations: &["Add", "Return"],
        abi: DeclAbi::ScalarF64Binary,
        x86_bytes: &X86_FALLTHROUGH_BYTES,
        aarch64_bytes: &AARCH64_FALLTHROUGH_BYTES,
        portable_bytes: &[0xC3],
        holes: &[(5, 4, "Rel32")],
        aarch64_holes: &[(4, 4, "Branch26"), (8, 4, "Branch26")],
        entry: 0,
        external_entries: &[0],
    },
];
