#!/usr/bin/env bash
# Enforce the repository-wide 500 physical-line limit for source files,
# skipping polyfill content (which is generated/extracted data, not logic).
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

# Paths that are exempt from the 500-line cap (polyfill data files
# generated by the all-Rust migration are auto-generated data).
EXEMPT_PATTERNS=(
  "crates/quench-node/src/polyfill"
  "crates/quench-node/src/polyfills"
)

result_code=0
while IFS= read -r -d '' file; do
  exempt=0
  for pattern in "${EXEMPT_PATTERNS[@]}"; do
    if [[ "$file" == *"$pattern"* ]]; then
      exempt=1
      break
    fi
  done
  if (( exempt )); then continue; fi

  lines=$(wc -l < "$file")
  if (( lines > 500 )); then
    printf 'ERROR: %s has %d lines (maximum is 500)\n' "$file" "$lines" >&2
    result_code=1
  fi
done < <(find . -path './.git' -prune -o -path './tests/node' -prune -o \
  -path './target' -prune -o -path './node_modules' -prune -o \
  \( -name '*.js' -o -name '*.mjs' -o -name '*.rs' \) -type f -print0)

exit "$result_code"
