// Generated by runts
//! Static components (no JavaScript shipped to client)
//!
//! Components are defined here for reference. In production,
//! these would be generated from TSX files by `runts build`.
