// Generated by runts
//! Islands manifest

use serde::{Serialize, Deserialize};

/// Island entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Island {
    pub name: &'static str,
    pub file: &'static str,
    pub props_type: Option<&'static str>,
}

/// All islands
pub fn islands() -> Vec<Island> {
    vec![
        Island {
            name: "Counter",
            file: "Counter.tsx",
            props_type: None,
        },
    ]
}

/// Island renderer
pub async fn render_island(name: &str, props: serde_json::Value) -> String {
    // Island rendering is handled by the SSR system
    // This function would be called to render specific islands
    format!("<div data-island=\"{}\">{{</div>", name)
}
