// Generated by runts
//! Islands manifest

use serde::{Serialize, Deserialize};

/// Island entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Island {
    pub name: &'static str,
    pub file: &'static str,
    pub props_type: Option<&'static str>,
}

/// All islands
pub fn islands() -> Vec<Island> {
    vec![
        Island {
            name: "Counter",
            file: "Counter.tsx",
            props_type: None,
        },
        Island {
            name: "CounterSimple",
            file: "CounterSimple.tsx",
            props_type: None,
        },
        Island {
            name: "TodoList",
            file: "TodoList.tsx",
            props_type: None,
        },
    ]
}

/// Re-export generated island components
pub use crate::gen::islands::counter;
pub use crate::gen::islands::counter_simple;
pub use crate::gen::islands::todo_list;

/// Island renderer
pub async fn render_island(name: &str, _props: serde_json::Value) -> String {
    format!("<div data-island=\"{}\">\n</div>", name)
}
