// Generated by runts
//! Application library

pub mod routes;
pub mod islands;
pub mod components;

// Re-export commonly used items
pub use routes::{routes, build_router, Route, Method};
pub use islands::{islands, render_island, Island};

// Re-export runtime
pub use runts_lib::runtime::prelude::*;
