// Generated by runts
//! Application library

pub mod gen;
pub mod routes;
pub mod islands;
pub mod components;

// Re-export commonly used items
pub use routes::build_router;
pub use islands::{islands, Island};

// Re-export runtime
pub use runts_lib::runtime::prelude::*;
