// Generated by runts
//! Application library

pub mod gen;
pub mod routes;
pub mod islands;
pub mod components;

// Re-export commonly used items
pub use routes::build_router;
pub use islands::{islands, Island};

// Re-export runtime
pub use runts_lib::runtime::prelude::*;

/// Register all components for SSR rendering.
/// Call this before starting the server.
pub fn register_components() {
    runts_lib::runtime::vdom::register_island("Counter", |props, _children| {
        let parsed = serde_json::from_value(serde_json::json!(props)).unwrap_or_default();
        Some(crate::gen::islands::counter::counter(parsed))
    });
    runts_lib::runtime::vdom::register_island("CounterSimple", |props, _children| {
        let parsed = serde_json::from_value(serde_json::json!(props)).unwrap_or_default();
        Some(crate::gen::islands::counter_simple::counter_simple(parsed))
    });
    runts_lib::runtime::vdom::register_island("TodoList", |props, _children| {
        let parsed = serde_json::from_value(serde_json::json!(props)).unwrap_or_default();
        Some(crate::gen::islands::todo_list::todo_list(parsed))
    });
    runts_lib::runtime::vdom::register_component("Header", |props, _children| {
        let parsed = serde_json::from_value(serde_json::json!(props)).unwrap_or_default();
        Some(crate::gen::components::header::header(parsed))
    });
}
