// Generated by runts
//! Route table for the application

use axum::{Router, routing::{get, post, put, delete}};

use crate::gen::about as about;
use crate::gen::blog::_layout as blog__layout;
use crate::gen::blog::index as blog_index;
use crate::gen::blog::slug as blog_slug;
use crate::gen::index as index;

/// Build Axum router from routes
pub fn build_router() -> Router {
    let mut router = Router::new();

    //  (index.tsx)
    router = router.route("", index::handle_get);

    // /blog (blog/index.tsx)
    router = router.route("/blog", blog_index::handle_get);

    // /blog/_layout (blog/_layout.tsx)
    router = router.route("/blog/_layout", blog__layout::handle_get);

    // /blog/:slug (blog/[slug].tsx)
    router = router.route("/blog/:slug", blog_slug::handle_get);

    // /about (about.tsx)
    router = router.route("/about", about::handle_get);

    router
}
