// Generated by runts
//! Route table for the application

use axum::{Router, routing::{get, post, put, delete}, response::IntoResponse};
use serde::{Serialize, Deserialize};

/// HTTP method
#[derive(Debug, Clone)]
pub enum Method {
    GET,
    POST,
    PUT,
    DELETE,
}

/// Route entry
#[derive(Debug, Clone)]
pub struct Route {
    pub pattern: &'static str,
    pub methods: Vec<Method>,
    pub params: Vec<&'static str>,
}

/// All routes
pub fn routes() -> Vec<Route> {
    vec![
        Route {
            pattern: "",
            methods: vec![Method::GET],
            params: vec![],
        },
        Route {
            pattern: "/blog",
            methods: vec![Method::GET],
            params: vec![],
        },
        Route {
            pattern: "/blog/_layout",
            methods: vec![Method::GET],
            params: vec![],
        },
        Route {
            pattern: "/blog/:slug",
            methods: vec![Method::GET],
            params: vec!["slug"],
        },
    ]
}

/// Build Axum router from routes
pub fn build_router() -> Router {
    let mut router = Router::new();

    //  (index.tsx)
    router = router.route("", index_get);

    // /blog (blog/index.tsx)
    router = router.route("/blog", blog_index_get);

    // /blog/_layout (blog/_layout.tsx)
    router = router.route("/blog/_layout", blog__layout_get);

    // /blog/:slug (blog/[slug].tsx)
    router = router.route("/blog/:slug", blog_slug_get);


    router
}
