// Generated by runts
//! Route table for the application
//!
//! Note: Full route generation requires running `runts build` first.
//! This file demonstrates the expected route structure.

use axum::{Router, routing::get, response::IntoResponse};

/// Home page handler
pub async fn home_handler() -> impl IntoResponse {
    Html(r#"<div><h1>Welcome to runts</h1><p>A Fresh/Preact to Rust compiler</p></div>"#.to_string())
}

/// Blog index handler
pub async fn blog_handler() -> impl IntoResponse {
    Html(r#"<div><h1>Blog</h1><p>Coming soon...</p></div>"#.to_string())
}

/// Blog post handler
pub async fn blog_post_handler(axum::extract::Path(slug): axum::extract::Path<String>) -> impl IntoResponse {
    Html(format!(r#"<div><h1>Post: {}</h1><p>This is a placeholder for the blog post content.</p></div>"#, slug))
}

/// Build Axum router from routes
pub fn build_router() -> Router {
    Router::new()
        .route("/", get(home_handler))
        .route("/blog", get(blog_handler))
        .route("/blog/:slug", get(blog_post_handler))
}

/// HTML response wrapper
pub struct Html(pub String);

impl IntoResponse for Html {
    fn into_response(self) -> axum::response::Response {
        axum::response::Html(self.0).into_response()
    }
}
