//! Ratatui plugin implementation - real widget codegen from HIR.
//!
//! Parses TSX HIR JSON and converts JSX elements to Ratatui widget code.

use quote::quote;

use runts_plugin::{
    CargoDep, DevAction, DevContext, DevState, Plugin, PluginError,
};

use crate::codegen;

/// Ratatui plugin for runts.
///
/// Provides TUI rendering using Ratatui library.
pub struct RatatuiPlugin;

impl RatatuiPlugin {
    /// Try to generate widget code from HIR items JSON.
    /// Returns Some(code) if JSX was detected, None otherwise.
    pub(crate) fn try_codegen_jsx(items: &serde_json::Value) -> Option<String> {
        codegen::try_codegen_jsx(items)
    }

    /// Get mutable reference to RatatuiDevState from dyn DevState.
    fn get_state_mut(state: &mut dyn DevState) -> Result<&mut RatatuiDevState, PluginError> {
        let st_any = state.as_any_mut();
        match st_any.downcast_mut::<RatatuiDevState>() {
            Some(s) => Ok(s),
            None => Err(PluginError::dev("ratatui", "unexpected DevState type")),
        }
    }

    /// Read source file contents.
    fn read_source(module_path: &std::path::Path) -> Result<String, DevAction> {
        match std::fs::read_to_string(module_path) {
            Ok(s) => Ok(s),
            Err(e) => {
                eprintln!("HIR render: read {} failed: {e}", module_path.display());
                Err(DevAction::Continue)
            }
        }
    }

    /// Fallback stub when no JSX is detected.
    fn codegen_stub_with_source(source_path: &str) -> Result<String, PluginError> {
        let code = quote! {
            //! Fallback Ink entry: generated by runts-ratatui 0.1.
            //!
            //! No JSX was detected in the HIR for
            //! `#source_path`. Emits a placeholder
            //! Text so the build still produces a
            //! runnable binary that links
            //! `runts-ink`.

            use runts_ink;

            fn main() -> anyhow::Result<()> {
                let root: runts_ink::VNode =
                    runts_ink::Text::new(
                        String::from("Ratatui widget (source: ")
                            + #source_path
                            + ")",
                    )
                    .into();
                let rendered = runts_ink::render_to_string(
                    root,
                    runts_ink::RenderOptions::default(),
                )?;
                print!("{rendered}");
                Ok(())
            }
        };
        Ok(code.to_string())
    }

    /// Try lowering the first module's HIR to a real runts-ink expression.
    fn first_ink_codegen(modules: &[runts_hir::Module]) -> Option<String> {
        for module in modules {
            let items_json = serde_json::to_value(&module.items).ok()?;
            if let Some(code) = codegen::try_codegen_jsx(&items_json) {
                return Some(code);
            }
        }
        None
    }
}

impl Plugin for RatatuiPlugin {
    fn name(&self) -> &str {
        "ratatui"
    }

    fn help_text(&self) -> &str {
        "Ratatui TUI framework"
    }

    fn codegen_module(&self, module: &runts_hir::Module) -> Result<String, PluginError> {
        let source_path = module.source_path.as_deref().unwrap_or("unknown");
        let items_json = serde_json::to_value(&module.items).map_err(|e| {
            PluginError::codegen("ratatui", source_path, format!("failed to serialize HIR items: {e}"))
        })?;
        if let Some(code) = Self::try_codegen_jsx(&items_json) {
            return Ok(code);
        }
        Self::codegen_stub_with_source(source_path)
    }

    fn cargo_deps(&self) -> Vec<CargoDep> {
        vec![
            CargoDep {
                name: "ratatui".to_string(),
                version: Some("0.26".to_string()),
                path: None,
                features: vec!["crossterm".to_string()],
            },
            CargoDep {
                name: "crossterm".to_string(),
                version: Some("0.27".to_string()),
                path: None,
                features: vec![],
            },
            CargoDep {
                name: "anyhow".to_string(),
                version: Some("1.0".to_string()),
                path: None,
                features: vec![],
            },
            CargoDep {
                name: "runts-ink".to_string(),
                version: None,
                path: Some(find_runts_ink_path()),
                features: vec![],
            },
        ]
    }

    fn codegen_entry(&self, modules: &[runts_hir::Module]) -> Result<String, PluginError> {
        // Try the new runts-ink JSX codegen first.
        if let Some(code) = Self::first_ink_codegen(modules) {
            return Ok(code);
        }

        // Aggregate widgets from all modules.
        let mut has_widgets = false;
        let mut widget_count = 0;

        for module in modules {
            if let Some(source_path) = &module.source_path {
                if source_path.ends_with(".tsx") || source_path.ends_with(".rs") {
                    if !module.items.is_empty() {
                        has_widgets = true;
                        widget_count += 1;
                    }
                }
            }
        }

        if has_widgets {
            let app_body = crate::codegen::widget_text(&format!(
                "Ratatui app with {} widget module(s)",
                widget_count
            ));
            let entry = crate::codegen::tui_main(app_body);
            Ok(entry.to_string())
        } else {
            let source_info = modules
                .first()
                .and_then(|m| m.source_path.as_deref())
                .unwrap_or("no modules");
            let app_body =
                crate::codegen::widget_text(&format!("Hello from Ratatui! (source: {})", source_info));
            let entry = crate::codegen::tui_main(app_body);
            Ok(entry.to_string())
        }
    }

    fn dev_init(&self, ctx: &mut DevContext) -> Result<Box<dyn DevState>, PluginError> {
        let module = ctx
            .modules
            .iter()
            .find(|m| m.ends_with(".tsx") || m.ends_with(".ts"))
            .cloned();
        Ok(Box::new(RatatuiDevState { module, dirty: true }))
    }

    fn dev_run_once(&self, state: &mut dyn DevState) -> Result<DevAction, PluginError> {
        let st = Self::get_state_mut(state)?;
        if !st.dirty {
            return Ok(DevAction::Continue);
        }
        st.dirty = false;

        let Some(module_path) = st.module.clone() else {
            return Ok(DevAction::Continue);
        };

        let _source = match Self::read_source(std::path::Path::new(&module_path)) {
            Ok(s) => s,
            Err(e) => return Ok(e),
        };
        // TODO(task-024): Wire rquickjs dev path here.
        // The HIR interpreter has been removed; dev rendering will
        // transpile TSX -> JS and eval through rquickjs + bridge.
        Ok(DevAction::Continue)
    }

    fn dev_reload(&self, _ctx: &mut DevContext, state: &mut dyn DevState) -> Result<(), PluginError> {
        if let Some(s) = state.as_any_mut().downcast_mut::<RatatuiDevState>() {
            s.dirty = true;
        }
        Ok(())
    }
}

/// Per-session dev state for the ratatui plugin.
struct RatatuiDevState {
    /// Path to the .tsx module being rendered.
    module: Option<String>,
    /// `true` when the source has changed and needs re-evaluation.
    dirty: bool,
}

impl DevState for RatatuiDevState {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
    fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
        self
    }
}

/// Locate the `runts-ink` crate on disk.
fn find_runts_ink_path() -> std::path::PathBuf {
    let manifest = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest.parent().map(|p| p.join("runts-ink")).unwrap_or_else(|| manifest.join("runts-ink"))
}
